# Generated by Django 6.0 on 2025-12-25 02:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('web_visits', models.PositiveIntegerField(default=0)),
                ('app_visits', models.PositiveIntegerField(default=0)),
                ('mobile_visits', models.PositiveIntegerField(default=0)),
                ('desktop_visits', models.PositiveIntegerField(default=0)),
                ('top_pages', models.JSONField(default=dict)),
                ('top_countries', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('source', models.CharField(choices=[('web', 'Website'), ('app', 'Application')], db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], db_index=True, max_length=10)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_page_views',
                'ordering': ['-created_at'],
            },
        ),
    ]
