# Generated by Django 6.0 on 2025-12-30 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['source', 'date'], name='analytics_p_source_846f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['date', 'country'], name='analytics_p_date_8b60df_idx'),
        ),
    ]
