# Generated by Django 5.2.8 on 2025-11-07 07:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('field_key', models.CharField(db_index=True, help_text='کلید یکتا برای فیلد (مثال: name, email, phone)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='کلید فیلد باید حداقل 2 کاراکتر باشد')], verbose_name='کلید فیلد')),
                ('field_type', models.CharField(choices=[('text', 'متن'), ('email', 'ایمیل'), ('phone', 'شماره تلفن'), ('textarea', 'متن چندخطی'), ('select', 'انتخابی'), ('checkbox', 'چک باکس'), ('radio', 'رادیو'), ('number', 'عدد'), ('date', 'تاریخ'), ('url', 'لینک')], db_index=True, default='text', help_text='نوع فیلد (متن، ایمیل، انتخابی و غیره)', max_length=20, verbose_name='نوع فیلد')),
                ('label', models.CharField(help_text='برچسب فارسی فیلد که به کاربر نمایش داده می\u200cشود', max_length=200, verbose_name='برچسب')),
                ('placeholder', models.CharField(blank=True, help_text='متن راهنمای داخل فیلد (اختیاری)', max_length=200, null=True, verbose_name='متن راهنما')),
                ('required', models.BooleanField(db_index=True, default=True, help_text='آیا این فیلد الزامی است؟', verbose_name='الزامی')),
                ('platforms', models.JSONField(default=list, help_text="لیست پلتفرم\u200cهایی که این فیلد در آن\u200cها نمایش داده می\u200cشود: ['website', 'mobile_app']", verbose_name='پلتفرم\u200cها')),
                ('options', models.JSONField(blank=True, default=list, help_text="گزینه\u200cهای فیلد انتخابی: [{'value': 'option1', 'label': 'گزینه 1'}]", verbose_name='گزینه\u200cها')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text="قوانین اعتبارسنجی: {'min_length': 3, 'max_length': 100, 'pattern': '...'}", verbose_name='قوانین اعتبارسنجی')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش فیلد در فرم (اعداد کمتر اول نمایش داده می\u200cشوند)', verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'فیلد فرم تماس',
                'verbose_name_plural': 'فیلدهای فرم تماس',
                'db_table': 'form_contact_fields',
                'ordering': ['order', 'field_key'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='form_contac_is_acti_93798d_idx'), models.Index(fields=['field_type', 'is_active'], name='form_contac_field_t_e68d1d_idx'), models.Index(fields=['platforms'], name='form_contac_platfor_99fbd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('form_data', models.JSONField(help_text="داده\u200cهای ارسال شده از فرم به صورت JSON: {'field_key': 'value'}", verbose_name='داده\u200cهای فرم')),
                ('platform', models.CharField(choices=[('website', 'وب\u200cسایت'), ('mobile_app', 'اپلیکیشن موبایل')], db_index=True, default='website', help_text='پلتفرمی که فرم از آن ارسال شده', max_length=20, verbose_name='پلتفرم')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('archived', 'آرشیو شده')], db_index=True, default='new', help_text='وضعیت فعلی ارسال', max_length=20, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='آدرس IP فرستنده', null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, help_text='اطلاعات مرورگر یا اپلیکیشن فرستنده', null=True, verbose_name='User Agent')),
                ('reply_message', models.TextField(blank=True, help_text='پاسخ ادمین به این ارسال', null=True, verbose_name='پاسخ ادمین')),
                ('replied_at', models.DateTimeField(blank=True, db_index=True, help_text='زمانی که پاسخ ارسال شد', null=True, verbose_name='تاریخ پاسخ')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='زمانی که ارسال خوانده شد', null=True, verbose_name='تاریخ خواندن')),
                ('replied_by', models.ForeignKey(blank=True, help_text='ادمینی که پاسخ را ارسال کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ داده شده توسط')),
            ],
            options={
                'verbose_name': 'ارسال فرم تماس',
                'verbose_name_plural': 'ارسال\u200cهای فرم تماس',
                'db_table': 'form_contact_submissions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'created_at'], name='form_contac_status_5dd4f8_idx'), models.Index(fields=['platform', 'created_at'], name='form_contac_platfor_514859_idx'), models.Index(fields=['status', 'platform'], name='form_contac_status_abd14e_idx'), models.Index(fields=['ip_address'], name='form_contac_ip_addr_190396_idx')],
            },
        ),
    ]
