# Generated by Django 5.2.8 on 2025-11-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormSubmission',
        ),
    ]
