# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_delete_contactformsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformfield',
            options={'ordering': ['order', 'field_key'], 'verbose_name': 'Contact Form Field', 'verbose_name_plural': 'Contact Form Fields'},
        ),
        migrations.RemoveIndex(
            model_name='contactformfield',
            name='form_contac_platfor_99fbd0_idx',
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='field_key',
            field=models.CharField(db_index=True, help_text='Unique key for the field (e.g., name, email, phone)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Field key must be at least 2 characters.')], verbose_name='Field Key'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('number', 'Number'), ('date', 'Date'), ('url', 'URL')], db_index=True, default='text', help_text='Type of field (text, email, select, etc.)', max_length=20, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='label',
            field=models.CharField(help_text='Field label displayed to users', max_length=200, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="Options for select field: [{'value': 'option1', 'label': 'Option 1'}]", verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in form (lower numbers appear first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text inside the field (optional)', max_length=200, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='platforms',
            field=models.JSONField(default=list, help_text="List of platforms where this field is displayed: ['website', 'mobile_app']", verbose_name='Platforms'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='required',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this field is required', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='contactformfield',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Validation rules: {'min_length': 3, 'max_length': 100, 'pattern': '...'}", verbose_name='Validation Rules'),
        ),
    ]
