# Generated by Django 6.0 on 2025-12-25 02:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelSettings',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('panel_title', models.CharField(db_index=True, default='Admin Panel', help_text='Title displayed in the admin panel', max_length=100, verbose_name='Panel Title')),
                ('favicon', models.ForeignKey(blank=True, help_text='Panel favicon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_favicon', to='media.imagemedia', verbose_name='Favicon')),
                ('logo', models.ForeignKey(blank=True, help_text='Panel logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_logo', to='media.imagemedia', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Panel Settings',
                'verbose_name_plural': 'Panel Settings',
                'db_table': 'panel_settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
