# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Panel Settings', 'verbose_name_plural': 'Panel Settings'},
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Panel favicon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_favicon', to='media.imagemedia', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Panel logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_logo', to='media.imagemedia', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='panelsettings',
            name='panel_title',
            field=models.CharField(db_index=True, default='Admin Panel', help_text='Title displayed in the admin panel', max_length=100, verbose_name='Panel Title'),
        ),
    ]
