from .base import BASE_PERMISSIONS
from .media import MEDIA_PERMISSIONS
from .users import USERS_PERMISSIONS
from .blog import BLOG_PERMISSIONS
from .portfolio import PORTFOLIO_PERMISSIONS
from .email import EMAIL_PERMISSIONS
from .ticket import TICKET_PERMISSIONS
from .ai import AI_PERMISSIONS
from .analytics import ANALYTICS_PERMISSIONS
from .management import MANAGEMENT_PERMISSIONS
from .real_estate import REAL_ESTATE_PERMISSIONS
from .real_estate_projects import REAL_ESTATE_PROJECTS_PERMISSIONS

__all__ = [
    'BASE_PERMISSIONS',
    'MEDIA_PERMISSIONS',
    'USERS_PERMISSIONS',
    'BLOG_PERMISSIONS',
    'PORTFOLIO_PERMISSIONS',
    'EMAIL_PERMISSIONS',
    'TICKET_PERMISSIONS',
    'AI_PERMISSIONS',
    'ANALYTICS_PERMISSIONS',
    'MANAGEMENT_PERMISSIONS',
    'REAL_ESTATE_PERMISSIONS',
    'REAL_ESTATE_PROJECTS_PERMISSIONS',
]
