PORTFOLIO_PERMISSIONS = {
    'portfolio.read': {
        'module': 'portfolio',
        'action': 'read',
        'display_name': 'View Portfolios',
        'description': 'Allow viewing portfolio items list and details',
    },
    'portfolio.create': {
        'module': 'portfolio',
        'action': 'create',
        'display_name': 'Create Portfolio',
        'description': 'Allow creating new portfolio items',
    },
    'portfolio.update': {
        'module': 'portfolio',
        'action': 'update',
        'display_name': 'Update Portfolio',
        'description': 'Allow updating portfolio items',
    },
    'portfolio.delete': {
        'module': 'portfolio',
        'action': 'delete',
        'display_name': 'Delete Portfolio',
        'description': 'Allow deleting portfolio items',
    },
    'portfolio.category.read': {
        'module': 'portfolio',
        'action': 'read',
        'display_name': 'View Portfolio Categories',
        'description': 'Allow viewing portfolio categories',
    },
    'portfolio.category.create': {
        'module': 'portfolio',
        'action': 'create',
        'display_name': 'Create Portfolio Category',
        'description': 'Allow creating portfolio categories',
    },
    'portfolio.category.update': {
        'module': 'portfolio',
        'action': 'update',
        'display_name': 'Update Portfolio Category',
        'description': 'Allow updating portfolio categories',
    },
    'portfolio.category.delete': {
        'module': 'portfolio',
        'action': 'delete',
        'display_name': 'Delete Portfolio Category',
        'description': 'Allow deleting portfolio categories',
    },
    'portfolio.tag.read': {
        'module': 'portfolio',
        'action': 'read',
        'display_name': 'View Portfolio Tags',
        'description': 'Allow viewing portfolio tags',
    },
    'portfolio.tag.create': {
        'module': 'portfolio',
        'action': 'create',
        'display_name': 'Create Portfolio Tag',
        'description': 'Allow creating portfolio tags',
    },
    'portfolio.tag.update': {
        'module': 'portfolio',
        'action': 'update',
        'display_name': 'Update Portfolio Tag',
        'description': 'Allow updating portfolio tags',
    },
    'portfolio.tag.delete': {
        'module': 'portfolio',
        'action': 'delete',
        'display_name': 'Delete Portfolio Tag',
        'description': 'Allow deleting portfolio tags',
    },
    'portfolio.option.read': {
        'module': 'portfolio',
        'action': 'read',
        'display_name': 'View Portfolio Options',
        'description': 'Allow viewing portfolio options',
    },
    'portfolio.option.create': {
        'module': 'portfolio',
        'action': 'create',
        'display_name': 'Create Portfolio Option',
        'description': 'Allow creating portfolio options',
    },
    'portfolio.option.update': {
        'module': 'portfolio',
        'action': 'update',
        'display_name': 'Update Portfolio Option',
        'description': 'Allow updating portfolio options',
    },
    'portfolio.option.delete': {
        'module': 'portfolio',
        'action': 'delete',
        'display_name': 'Delete Portfolio Option',
        'description': 'Allow deleting portfolio options',
    },
}
