REAL_ESTATE_PROJECTS_PERMISSIONS = {
    "real_estate_projects.project.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Real Estate Projects",
        "description": "Allow viewing real estate projects list and details",
    },
    "real_estate_projects.project.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Real Estate Project",
        "description": "Allow creating real estate projects",
    },
    "real_estate_projects.project.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Real Estate Project",
        "description": "Allow updating real estate projects",
    },
    "real_estate_projects.project.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Real Estate Project",
        "description": "Allow deleting real estate projects",
    },
    "real_estate_projects.offer.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Project Offers",
        "description": "Allow viewing project market offers",
    },
    "real_estate_projects.offer.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Project Offer",
        "description": "Allow creating project market offers",
    },
    "real_estate_projects.offer.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Project Offer",
        "description": "Allow updating project market offers",
    },
    "real_estate_projects.offer.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Project Offer",
        "description": "Allow deleting project market offers",
    },
    "real_estate_projects.type.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Project Types",
        "description": "Allow viewing project types",
    },
    "real_estate_projects.type.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Project Type",
        "description": "Allow creating project types",
    },
    "real_estate_projects.type.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Project Type",
        "description": "Allow updating project types",
    },
    "real_estate_projects.type.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Project Type",
        "description": "Allow deleting project types",
    },
    "real_estate_projects.state.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Project States",
        "description": "Allow viewing project states",
    },
    "real_estate_projects.state.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Project State",
        "description": "Allow creating project states",
    },
    "real_estate_projects.state.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Project State",
        "description": "Allow updating project states",
    },
    "real_estate_projects.state.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Project State",
        "description": "Allow deleting project states",
    },
    "real_estate_projects.offer_state.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Offer States",
        "description": "Allow viewing offer states",
    },
    "real_estate_projects.offer_state.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Offer State",
        "description": "Allow creating offer states",
    },
    "real_estate_projects.offer_state.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Offer State",
        "description": "Allow updating offer states",
    },
    "real_estate_projects.offer_state.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Offer State",
        "description": "Allow deleting offer states",
    },
    "real_estate_projects.label.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Project Labels",
        "description": "Allow viewing project labels",
    },
    "real_estate_projects.label.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Project Label",
        "description": "Allow creating project labels",
    },
    "real_estate_projects.label.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Project Label",
        "description": "Allow updating project labels",
    },
    "real_estate_projects.label.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Project Label",
        "description": "Allow deleting project labels",
    },
    "real_estate_projects.feature.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Project Features",
        "description": "Allow viewing project features",
    },
    "real_estate_projects.feature.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Project Feature",
        "description": "Allow creating project features",
    },
    "real_estate_projects.feature.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Project Feature",
        "description": "Allow updating project features",
    },
    "real_estate_projects.feature.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Project Feature",
        "description": "Allow deleting project features",
    },
    "real_estate_projects.tag.read": {
        "module": "real_estate_projects",
        "action": "read",
        "display_name": "View Project Tags",
        "description": "Allow viewing project tags",
    },
    "real_estate_projects.tag.create": {
        "module": "real_estate_projects",
        "action": "create",
        "display_name": "Create Project Tag",
        "description": "Allow creating project tags",
    },
    "real_estate_projects.tag.update": {
        "module": "real_estate_projects",
        "action": "update",
        "display_name": "Update Project Tag",
        "description": "Allow updating project tags",
    },
    "real_estate_projects.tag.delete": {
        "module": "real_estate_projects",
        "action": "delete",
        "display_name": "Delete Project Tag",
        "description": "Allow deleting project tags",
    },
}
