# Generated by Django 6.0 on 2025-12-30 10:58

import django.utils.timezone
import src.ai.models.ai_provider
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProviderSettings',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('personal_api_key', models.TextField(blank=True, help_text='Encrypted personal API key for this admin', verbose_name='Personal API Key (Encrypted)')),
                ('use_shared_api', models.BooleanField(db_index=True, default=True, help_text='Whether to use shared API key instead of personal', verbose_name='Use Shared API')),
                ('monthly_limit', models.IntegerField(default=1000, help_text='Monthly request limit for this admin', verbose_name='Monthly Limit')),
                ('monthly_usage', models.IntegerField(default=0, help_text='Current monthly usage count', verbose_name='Monthly Usage')),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total number of requests made by this admin', verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Date and time when provider was last used by this admin', null=True, verbose_name='Last Used')),
            ],
            options={
                'verbose_name': 'Admin Provider Settings',
                'verbose_name_plural': 'Admin Provider Settings',
                'db_table': 'ai_admin_provider_settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, src.ai.models.ai_provider.EncryptedAPIKeyMixin),
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Model identifier name', max_length=150, verbose_name='Model Name')),
                ('model_id', models.CharField(help_text="API model identifier (e.g., 'gpt-4', 'claude-3.5-sonnet')", max_length=200, verbose_name='Model ID')),
                ('display_name', models.CharField(help_text='Human-readable model name', max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Model description', verbose_name='Description')),
                ('capabilities', models.JSONField(default=list, help_text='List of model capabilities', verbose_name='Capabilities')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional model configuration', verbose_name='Configuration')),
                ('pricing_input', models.DecimalField(blank=True, decimal_places=6, help_text='Price per million input tokens', max_digits=10, null=True, verbose_name='Input Price ($/1M tokens)')),
                ('pricing_output', models.DecimalField(blank=True, decimal_places=6, help_text='Price per million output tokens', max_digits=10, null=True, verbose_name='Output Price ($/1M tokens)')),
                ('max_tokens', models.IntegerField(blank=True, help_text='Maximum tokens per request', null=True, verbose_name='Max Tokens')),
                ('context_window', models.IntegerField(blank=True, help_text='Maximum context window size in tokens', null=True, verbose_name='Context Window')),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total number of requests made to this model', verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Date and time when model was last used', null=True, verbose_name='Last Used')),
                ('sort_order', models.IntegerField(db_index=True, default=0, help_text='Order for displaying models within provider', verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'ordering': ['provider', 'sort_order', 'name'],
                'abstract': False,
            },
            bases=(models.Model, src.ai.models.ai_provider.CacheMixin),
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text="Unique provider identifier (e.g., 'openai', 'gemini')", max_length=100, unique=True, verbose_name='Provider Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the provider', max_length=100, unique=True, verbose_name='URL Slug')),
                ('display_name', models.CharField(help_text='Human-readable provider name', max_length=150, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Provider description', verbose_name='Description')),
                ('website', models.URLField(blank=True, help_text='Provider website URL', verbose_name='Website')),
                ('api_base_url', models.URLField(blank=True, help_text='Base URL for API requests', verbose_name='API Base URL')),
                ('provider_class', models.CharField(blank=True, help_text='Python class path (e.g., src.ai.providers.openai.OpenAIProvider)', max_length=200, verbose_name='Provider Class Path')),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='\n        Provider capabilities configuration:\n        {\n            "chat": {"supported": true, "has_dynamic_models": false, "models": [...]},\n            "content": {"supported": true, "has_dynamic_models": false},\n            "image": {"supported": true, "has_dynamic_models": true},\n            "audio": {"supported": false}\n        }\n        ', verbose_name='Capabilities')),
                ('allow_personal_keys', models.BooleanField(db_index=True, default=True, help_text='Whether admins can use personal API keys', verbose_name='Allow Personal Keys')),
                ('allow_shared_for_normal_admins', models.BooleanField(db_index=True, default=False, help_text='Whether normal admins can use shared API key', verbose_name='Allow Shared for Normal Admins')),
                ('shared_api_key', models.TextField(blank=True, help_text='Encrypted shared API key for the provider', verbose_name='Shared API Key (Encrypted)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional provider configuration', verbose_name='Configuration')),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total number of API requests made', verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Date and time when provider was last used', null=True, verbose_name='Last Used')),
                ('sort_order', models.IntegerField(db_index=True, default=0, help_text='Order for displaying providers', verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'db_table': 'ai_providers',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
            bases=(models.Model, src.ai.models.ai_provider.EncryptedAPIKeyMixin, src.ai.models.ai_provider.CacheMixin),
        ),
    ]
