# Generated by Django 5.2.7 on 2025-11-01 23:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageProvider',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('provider_name', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI DALL-E'), ('huggingface', 'Hugging Face Stable Diffusion')], max_length=50, unique=True, verbose_name='Provider Name')),
                ('api_key', models.TextField(blank=True, help_text='API key for the provider (stored encrypted)', null=True, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=False, help_text='Is this provider active for image generation?', verbose_name='Active')),
                ('config', models.JSONField(blank=True, default=dict, help_text="Additional provider settings (e.g., model version, parameters) - Example: {'model_version': 'v1', 'max_resolution': '1024x1024'}", verbose_name='Additional Settings')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Date and time of last API usage', null=True, verbose_name='Last Used')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this API has been used', verbose_name='Usage Count')),
            ],
            options={
                'verbose_name': 'AI Provider Settings',
                'verbose_name_plural': 'AI Provider Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]

