# Generated by Django 5.2.8 on 2025-11-28 10:45

import django.db.models.deletion
import django.utils.timezone
import src.ai.models.ai_provider
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProviderSettings',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('personal_api_key', models.TextField(blank=True, verbose_name='Personal API Key (Encrypted)')),
                ('use_shared_api', models.BooleanField(db_index=True, default=True, verbose_name='Use Shared API')),
                ('monthly_limit', models.IntegerField(default=1000, verbose_name='Monthly Limit')),
                ('monthly_usage', models.IntegerField(default=0, verbose_name='Monthly Usage')),
                ('total_requests', models.BigIntegerField(default=0, verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_settings', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'Admin Provider Settings',
                'verbose_name_plural': 'Admin Provider Settings',
                'db_table': 'ai_admin_provider_settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, src.ai.models.ai_provider.EncryptedAPIKeyMixin),
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Model Name')),
                ('model_id', models.CharField(max_length=200, verbose_name='Model ID')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capabilities', models.JSONField(default=list, verbose_name='Capabilities')),
                ('pricing_input', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Input Price ($/1M tokens)')),
                ('pricing_output', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Output Price ($/1M tokens)')),
                ('max_tokens', models.IntegerField(blank=True, null=True, verbose_name='Max Tokens')),
                ('context_window', models.IntegerField(blank=True, null=True, verbose_name='Context Window')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('total_requests', models.BigIntegerField(default=0, verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'ordering': ['provider', 'sort_order', 'name'],
                'abstract': False,
            },
            bases=(models.Model, src.ai.models.ai_provider.CacheMixin),
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Provider Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('display_name', models.CharField(max_length=150, verbose_name='Display Name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('api_base_url', models.URLField(blank=True, verbose_name='API Base URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('shared_api_key', models.TextField(blank=True, verbose_name='Shared API Key (Encrypted)')),
                ('allow_personal_keys', models.BooleanField(default=True, verbose_name='Allow Personal Keys')),
                ('allow_shared_for_normal_admins', models.BooleanField(db_index=True, default=False, verbose_name='Allow Shared for Normal Admins')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('total_requests', models.BigIntegerField(default=0, verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'db_table': 'ai_providers',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
            bases=(models.Model, src.ai.models.ai_provider.EncryptedAPIKeyMixin, src.ai.models.ai_provider.CacheMixin),
        ),
        migrations.DeleteModel(
            name='AIImageProvider',
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['public_id'], name='ai_provider_public__cbfe07_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['is_active', 'created_at'], name='ai_provider_is_acti_077493_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['slug', 'is_active'], name='ai_provider_slug_bef250_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['is_active', 'sort_order'], name='ai_provider_is_acti_28c1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['allow_shared_for_normal_admins'], name='ai_provider_allow_s_3832f8_idx'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiprovider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='adminprovidersettings',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to='ai.aiprovider', verbose_name='Provider'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['public_id'], name='ai_models_public__f0aa3c_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active', 'created_at'], name='ai_models_is_acti_fbdb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['provider', 'is_active'], name='ai_models_provide_31dc69_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active', 'sort_order'], name='ai_models_is_acti_9be97b_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['name'], name='ai_models_name_475fb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('provider', 'model_id')},
        ),
        migrations.AddIndex(
            model_name='adminprovidersettings',
            index=models.Index(fields=['public_id'], name='ai_admin_pr_public__5841ec_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprovidersettings',
            index=models.Index(fields=['is_active', 'created_at'], name='ai_admin_pr_is_acti_89fb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprovidersettings',
            index=models.Index(fields=['admin', 'provider'], name='ai_admin_pr_admin_i_62e2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprovidersettings',
            index=models.Index(fields=['admin', 'is_active'], name='ai_admin_pr_admin_i_f5b9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprovidersettings',
            index=models.Index(fields=['use_shared_api'], name='ai_admin_pr_use_sha_838e5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adminprovidersettings',
            unique_together={('admin', 'provider')},
        ),
    ]
