# Generated by Django 5.2.7 on 2025-11-03 07:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_migrate_data_from_media'),
    ]

    operations = [
        # Rename AIImageProvider to AIImageGeneration (model rename, table stays same)
        migrations.RenameModel(
            old_name='AIImageProvider',
            new_name='AIImageGeneration',
        ),
        # Alter the model to use the same table name explicitly
        migrations.AlterModelTable(
            name='aiimagegeneration',
            table='ai_aiimageprovider',
        ),
        # Update model options (verbose_name stays same, just ensuring consistency)
        migrations.AlterModelOptions(
            name='aiimagegeneration',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Provider Settings', 'verbose_name_plural': 'AI Provider Settings'},
        ),
        # Update field help texts
        migrations.AlterField(
            model_name='aiimagegeneration',
            name='api_key',
            field=models.TextField(blank=True, help_text='API key for the provider (stored encrypted). This key can be used for both image and content generation.', null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='aiimagegeneration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this provider active? (for both image and content generation)', verbose_name='Active'),
        ),
        # Create AIContentGeneration model
        migrations.CreateModel(
            name='AIContentGeneration',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('cache_key', models.CharField(db_index=True, help_text='Hash of prompt + provider + settings for fast lookup', max_length=255, unique=True, verbose_name='Cache Key')),
                ('prompt', models.TextField(help_text='Original user prompt/topic', verbose_name='Prompt')),
                ('provider_name', models.CharField(help_text='AI provider used (gemini, openai)', max_length=50, verbose_name='Provider')),
                ('title', models.CharField(help_text='Main title (H1)', max_length=200, verbose_name='Title')),
                ('meta_title', models.CharField(help_text='SEO meta title (50-60 characters)', max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.TextField(help_text='SEO meta description (150-160 characters)', max_length=160, verbose_name='Meta Description')),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=200, verbose_name='Slug')),
                ('content', models.TextField(help_text='Main content body (~500 words, SEO optimized)', verbose_name='Content')),
                ('h1', models.CharField(blank=True, help_text='Main heading (if different from title)', max_length=200, null=True, verbose_name='H1')),
                ('h2_list', models.JSONField(blank=True, default=list, help_text='List of H2 headings', verbose_name='H2 Headings')),
                ('h3_list', models.JSONField(blank=True, default=list, help_text='List of H3 headings', verbose_name='H3 Headings')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='SEO keywords extracted from content', verbose_name='Keywords')),
                ('word_count', models.IntegerField(default=0, help_text='Approximate word count', verbose_name='Word Count')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Settings used (word_count, tone, language, etc.)', verbose_name='Generation Settings')),
                ('generation_time_ms', models.IntegerField(default=0, help_text='Time taken to generate content in milliseconds', verbose_name='Generation Time (ms)')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this cached content was used', verbose_name='Usage Count')),
            ],
            options={
                'verbose_name': 'AI Generated Content',
                'verbose_name_plural': 'AI Generated Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aicontentgeneration',
            index=models.Index(fields=['cache_key'], name='ai_aiconten_cache_k_7fbf00_idx'),
        ),
        migrations.AddIndex(
            model_name='aicontentgeneration',
            index=models.Index(fields=['provider_name', '-created_at'], name='ai_aiconten_provide_e3dd57_idx'),
        ),
        migrations.AddIndex(
            model_name='aicontentgeneration',
            index=models.Index(fields=['slug'], name='ai_aiconten_slug_fa2a3c_idx'),
        ),
    ]
