# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_adminprovidersettings_aimodel_aiprovider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminprovidersettings',
            name='ai_admin_pr_public__5841ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprovidersettings',
            name='ai_admin_pr_is_acti_89fb2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprovidersettings',
            name='ai_admin_pr_use_sha_838e5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='aimodel',
            name='ai_models_public__f0aa3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='aimodel',
            name='ai_models_is_acti_fbdb9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='aimodel',
            name='ai_models_provide_31dc69_idx',
        ),
        migrations.RemoveIndex(
            model_name='aimodel',
            name='ai_models_is_acti_9be97b_idx',
        ),
        migrations.RemoveIndex(
            model_name='aimodel',
            name='ai_models_name_475fb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiprovider',
            name='ai_provider_public__cbfe07_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiprovider',
            name='ai_provider_is_acti_077493_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiprovider',
            name='ai_provider_allow_s_3832f8_idx',
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='admin',
            field=models.ForeignKey(help_text='Admin user these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_settings', to=settings.AUTH_USER_MODEL, verbose_name='Admin User'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when provider was last used by this admin', null=True, verbose_name='Last Used'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='monthly_limit',
            field=models.IntegerField(default=1000, help_text='Monthly request limit for this admin', verbose_name='Monthly Limit'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='monthly_usage',
            field=models.IntegerField(default=0, help_text='Current monthly usage count', verbose_name='Monthly Usage'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='personal_api_key',
            field=models.TextField(blank=True, help_text='Encrypted personal API key for this admin', verbose_name='Personal API Key (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='provider',
            field=models.ForeignKey(help_text='AI provider these settings are for', on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to='ai.aiprovider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='total_requests',
            field=models.BigIntegerField(default=0, help_text='Total number of requests made by this admin', verbose_name='Total Requests'),
        ),
        migrations.AlterField(
            model_name='adminprovidersettings',
            name='use_shared_api',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether to use shared API key instead of personal', verbose_name='Use Shared API'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='capabilities',
            field=models.JSONField(default=list, help_text='List of model capabilities', verbose_name='Capabilities'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional model configuration', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='context_window',
            field=models.IntegerField(blank=True, help_text='Maximum context window size in tokens', null=True, verbose_name='Context Window'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(blank=True, help_text='Model description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='display_name',
            field=models.CharField(help_text='Human-readable model name', max_length=200, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when model was last used', null=True, verbose_name='Last Used'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='max_tokens',
            field=models.IntegerField(blank=True, help_text='Maximum tokens per request', null=True, verbose_name='Max Tokens'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(help_text="API model identifier (e.g., 'gpt-4', 'claude-3.5-sonnet')", max_length=200, verbose_name='Model ID'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(db_index=True, help_text='Model identifier name', max_length=150, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pricing_input',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price per million input tokens', max_digits=10, null=True, verbose_name='Input Price ($/1M tokens)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pricing_output',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price per million output tokens', max_digits=10, null=True, verbose_name='Output Price ($/1M tokens)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(help_text='AI provider that owns this model', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiprovider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Order for displaying models within provider', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='total_requests',
            field=models.BigIntegerField(default=0, help_text='Total number of requests made to this model', verbose_name='Total Requests'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='allow_personal_keys',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether admins can use personal API keys', verbose_name='Allow Personal Keys'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='allow_shared_for_normal_admins',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether normal admins can use shared API key', verbose_name='Allow Shared for Normal Admins'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='api_base_url',
            field=models.URLField(blank=True, help_text='Base URL for API requests', verbose_name='API Base URL'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional provider configuration', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='description',
            field=models.TextField(blank=True, help_text='Provider description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='display_name',
            field=models.CharField(help_text='Human-readable provider name', max_length=150, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when provider was last used', null=True, verbose_name='Last Used'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(db_index=True, help_text="Unique provider identifier (e.g., 'openai', 'gemini')", max_length=100, unique=True, verbose_name='Provider Name'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='shared_api_key',
            field=models.TextField(blank=True, help_text='Encrypted shared API key for the provider', verbose_name='Shared API Key (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the provider', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Order for displaying providers', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='total_requests',
            field=models.BigIntegerField(default=0, help_text='Total number of API requests made', verbose_name='Total Requests'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='website',
            field=models.URLField(blank=True, help_text='Provider website URL', verbose_name='Website'),
        ),
        migrations.AddIndex(
            model_name='adminprovidersettings',
            index=models.Index(fields=['use_shared_api', 'is_active'], name='ai_admin_pr_use_sha_74fe66_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['provider', 'is_active', 'sort_order'], name='ai_models_provide_2d3f36_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprovider',
            index=models.Index(fields=['allow_shared_for_normal_admins', 'is_active'], name='ai_provider_allow_s_cefcb5_idx'),
        ),
        # اضافه کردن Constraint برای تضمین یک مدل فعال به ازای هر provider+capability
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(
                fields=['provider', 'capabilities'],
                condition=models.Q(is_active=True),
                name='unique_active_model_per_provider_capability',
                violation_error_message='فقط یک مدل می‌تواند برای هر provider و capability فعال باشد'
            ),
        ),
    ]
