# Generated by Django 5.2.7 on 2025-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aicontentgeneration_aiimagegeneration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimagegeneration',
            name='provider_name',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI DALL-E'), ('huggingface', 'Hugging Face Stable Diffusion'), ('deepseek', 'DeepSeek AI')], max_length=50, unique=True, verbose_name='Provider Name'),
        ),
    ]
