# Generated by Django 6.0 on 2025-12-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_remove_adminprovidersettings_ai_admin_pr_public__5841ec_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aimodel',
            name='unique_active_model_per_provider_capability',
        ),
    ]
