# Generated by Django 5.2.7 on 2025-11-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_aiimagegeneration_provider_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIContentGeneration',
        ),
    ]
