# Generated by Django 5.2.8 on 2025-11-21 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_remove_aicontentgeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAISettings',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('provider_name', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek AI')], max_length=50, verbose_name='Provider Name')),
                ('api_key', models.TextField(blank=True, help_text='API key شخصی این ادمین (رمزنگاری شده)', null=True, verbose_name='Personal API Key')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این API Key فعال است؟', verbose_name='Active')),
                ('use_shared_api', models.BooleanField(default=True, help_text='اگر True باشد، از API مشترک استفاده می\u200cکند. اگر False باشد، از API شخصی استفاده می\u200cکند.', verbose_name='Use Shared API')),
                ('usage_count', models.IntegerField(default=0, help_text='تعداد دفعات استفاده از این API', verbose_name='Usage Count')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='آخرین زمان استفاده', null=True, verbose_name='Last Used')),
                ('monthly_limit', models.IntegerField(default=1000, help_text='محدودیت ماهانه استفاده (تعداد request)', verbose_name='Monthly Limit')),
                ('monthly_usage', models.IntegerField(default=0, help_text='تعداد استفاده در ماه جاری', verbose_name='Monthly Usage')),
                ('admin', models.ForeignKey(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'Admin AI Settings',
                'verbose_name_plural': 'Admin AI Settings',
                'db_table': 'ai_admin_settings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'provider_name'], name='ai_admin_se_admin_i_3417e4_idx'), models.Index(fields=['admin', 'is_active'], name='ai_admin_se_admin_i_3713dc_idx')],
                'unique_together': {('admin', 'provider_name')},
            },
        ),
    ]
