# Generated by Django 6.0 on 2026-02-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_ai_capability_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicapabilitymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at'),
        ),
        migrations.AlterField(
            model_name='aicapabilitymodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is active?'),
        ),
        migrations.AlterField(
            model_name='aicapabilitymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at'),
        ),
    ]
