# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
        ('ticket', '0001_initial'),
        ('user', '0002_alter_adminprofile_phone_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_priority_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_admin_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_active_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketattachment',
            new_name='ticket_atta_ticket__7cc71b_idx',
            old_name='ticket_attach_msg_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='ticket_mess_ticket__80bcb6_idx',
            old_name='ticket_msg_ticket_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='ticket_mess_sender__a30cf9_idx',
            old_name='ticket_msg_sender_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='ticket_mess_is_read_072b3a_idx',
            old_name='ticket_msg_read_created_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to handle this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='user.adminprofile', verbose_name='Assigned Admin'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Detailed description of the ticket issue', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_replied_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when ticket was last replied to', null=True, verbose_name='Last Replied At'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', help_text='Priority level of the ticket', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', help_text='Current status of the ticket', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(db_index=True, help_text='Ticket subject', max_length=500, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='audio',
            field=models.ForeignKey(blank=True, help_text='Audio attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.audiomedia', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.documentmedia', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.imagemedia', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket_message',
            field=models.ForeignKey(help_text='Ticket message this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.ticketmessage', verbose_name='Ticket Message'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Video attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.videomedia', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this message has been read', verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(help_text='Message content', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who sent this message (if sender_type is admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to='user.adminprofile', verbose_name='Sender Admin'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, help_text='Type of sender (user or admin)', max_length=10, verbose_name='Sender Type'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='User who sent this message (if sender_type is user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender User'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='Ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='tickets_status_1fe48b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'user', '-created_at'], name='tickets_status_65c924_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'assigned_admin', '-created_at'], name='tickets_status_771a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_active'], name='tickets_status_0790f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', False), ('video__isnull', True), ('audio__isnull', True), ('document__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', False), ('audio__isnull', True), ('document__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', True), ('audio__isnull', False), ('document__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', True), ('audio__isnull', True), ('document__isnull', False)), _connector='OR'), name='exactly_one_media_type_required'),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
        migrations.AlterModelTable(
            name='ticketattachment',
            table='ticket_attachments',
        ),
        migrations.AlterModelTable(
            name='ticketmessage',
            table='ticket_messages',
        ),
    ]
