# Generated by Django 6.0 on 2025-12-28 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('ticket', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to handle this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='user.adminprofile', verbose_name='Assigned Admin'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='audio',
            field=models.ForeignKey(blank=True, help_text='Audio attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.audiomedia', verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.documentmedia', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.imagemedia', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Video attachment (exactly one media type must be selected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='media.videomedia', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who sent this message (if sender_type is admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to='user.adminprofile', verbose_name='Sender Admin'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='User who sent this message (if sender_type is user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender User'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket_message',
            field=models.ForeignKey(help_text='Ticket message this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.ticketmessage', verbose_name='Ticket Message'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='tickets_status_1fe48b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'user', '-created_at'], name='tickets_status_65c924_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'assigned_admin', '-created_at'], name='tickets_status_771a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_active'], name='tickets_status_0790f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='ticket_mess_ticket__80bcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['sender_type', 'created_at'], name='ticket_mess_sender__a30cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='ticket_mess_is_read_072b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket_message', 'created_at'], name='ticket_atta_ticket__7cc71b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', False), ('video__isnull', True), ('audio__isnull', True), ('document__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', False), ('audio__isnull', True), ('document__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', True), ('audio__isnull', False), ('document__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', True), ('audio__isnull', True), ('document__isnull', False)), _connector='OR'), name='exactly_one_media_type_required'),
        ),
    ]
