# Generated by Django 6.0 on 2026-01-05 11:01

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='TicketStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_created', models.PositiveIntegerField(default=0)),
                ('total_closed', models.PositiveIntegerField(default=0)),
                ('avg_response_time_minutes', models.PositiveIntegerField(default=0)),
                ('priority_distribution', models.JSONField(blank=True, default=dict)),
                ('status_distribution', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Ticket Statistics',
                'verbose_name_plural': 'Ticket Statistics',
                'db_table': 'ticket_statistics',
                'ordering': ['-date'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='ticket_stat_date_915bbb_brin')],
            },
        ),
    ]
