# Generated by Django 6.0 on 2025-12-29 21:56

import django.core.validators
import django.utils.timezone
import src.email.models.email_attachment
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename', max_length=255, verbose_name='Filename')),
                ('file', models.FileField(help_text='Attachment file', upload_to=src.email.models.email_attachment.email_attachment_upload_path, verbose_name='File')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes', verbose_name='File Size')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100, verbose_name='Content Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when attachment was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'db_table': 'email_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived'), ('draft', 'Draft')], db_index=True, default='new', help_text='Status of the email message', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('email', 'Direct Email'), ('api', 'API')], db_index=True, default='website', help_text='Source where the email message originated from', max_length=50, verbose_name='Source')),
                ('subject', models.CharField(blank=True, db_index=True, help_text='Email message subject', max_length=300, null=True, verbose_name='Subject')),
                ('name', models.CharField(blank=True, db_index=True, help_text="Sender's name", max_length=200, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, db_index=True, help_text="Sender's email address", max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text="Sender's phone number", max_length=20, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True, help_text='Email message content', null=True, verbose_name='Message')),
                ('reply_message', models.TextField(blank=True, help_text='Reply message content', null=True, verbose_name='Reply Message')),
                ('dynamic_fields', models.JSONField(blank=True, default=dict, help_text='Additional dynamic fields data', verbose_name='Dynamic Fields')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the sender', null=True, verbose_name='User Agent')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when message was read', null=True, verbose_name='Read At')),
                ('replied_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when message was replied', null=True, verbose_name='Replied At')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'db_table': 'email_messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
