# Generated by Django 5.2.7 on 2025-11-06 21:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import src.email.models.email_attachment
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='نام فرستنده پیام', max_length=200, verbose_name='نام')),
                ('email', models.EmailField(db_index=True, help_text='آدرس ایمیل فرستنده', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, help_text='شماره تلفن فرستنده (اختیاری)', max_length=20, null=True, verbose_name='تلفن')),
                ('subject', models.CharField(db_index=True, help_text='موضوع پیام', max_length=300, verbose_name='موضوع')),
                ('message', models.TextField(help_text='متن پیام', verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('archived', 'آرشیو شده')], db_index=True, default='new', help_text='وضعیت فعلی پیام', max_length=20, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('website', 'وب\u200cسایت'), ('mobile_app', 'اپلیکیشن موبایل'), ('email', 'ایمیل مستقیم'), ('api', 'API')], db_index=True, default='website', help_text='منبع ارسال پیام', max_length=50, verbose_name='منبع')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP فرستنده', null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, help_text='اطلاعات مرورگر یا اپلیکیشن فرستنده', null=True, verbose_name='User Agent')),
                ('reply_message', models.TextField(blank=True, help_text='پاسخ ادمین به این پیام', null=True, verbose_name='پاسخ ادمین')),
                ('replied_at', models.DateTimeField(blank=True, db_index=True, help_text='زمانی که پاسخ ارسال شد', null=True, verbose_name='تاریخ پاسخ')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='زمانی که پیام خوانده شد', null=True, verbose_name='تاریخ خواندن')),
                ('replied_by', models.ForeignKey(blank=True, help_text='ادمینی که پاسخ را ارسال کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ داده شده توسط')),
            ],
            options={
                'verbose_name': 'پیام ایمیل',
                'verbose_name_plural': 'پیام\u200cهای ایمیل',
                'db_table': 'email_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل ضمیمه', upload_to=src.email.models.email_attachment.email_attachment_upload_path, verbose_name='فایل')),
                ('filename', models.CharField(help_text='نام اصلی فایل', max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(help_text='حجم فایل به بایت', verbose_name='حجم فایل (بایت)')),
                ('content_type', models.CharField(blank=True, help_text='MIME type فایل', max_length=100, verbose_name='نوع فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email.emailmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'ضمیمه ایمیل',
                'verbose_name_plural': 'ضمیمه\u200cهای ایمیل',
                'db_table': 'email_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['email'], name='email_messa_email_b06907_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'created_at'], name='email_messa_status_50c6df_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['source', 'created_at'], name='email_messa_source_ad1075_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'source'], name='email_messa_status_5543ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['message', 'created_at'], name='email_attac_message_a107f8_idx'),
        ),
    ]
