# Generated by Django 5.2.7 on 2025-11-07 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='ادمینی که این ایمیل/پیش\u200cنویس را ایجاد کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('archived', 'آرشیو شده'), ('draft', 'پیش\u200cنویس')], db_index=True, default='new', help_text='وضعیت فعلی پیام', max_length=20, verbose_name='وضعیت'),
        ),
    ]
