# Generated by Django 6.0 on 2025-12-30 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who replied to this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='Replied By'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='message',
            field=models.ForeignKey(help_text='Email message this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email.emailmessage', verbose_name='Email Message'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', '-created_at'], name='email_messa_status_0c85f8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['source', 'status', '-created_at'], name='email_messa_source_839260_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'created_by', '-created_at'], name='email_messa_status_610939_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['message', 'created_at'], name='email_attac_message_a107f8_idx'),
        ),
    ]
