# Generated by Django 5.2.8 on 2025-12-01 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_emailmessage_created_by_alter_emailmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, help_text='فیلدهای ساخته شده در فرم\u200cساز پنل ادمین', verbose_name='فیلدهای دینامیک'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='آدرس ایمیل فرستنده', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message',
            field=models.TextField(blank=True, help_text='متن پیام', null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='نام فرستنده پیام', max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, db_index=True, help_text='موضوع پیام', max_length=300, null=True, verbose_name='موضوع'),
        ),
    ]
