# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import src.email.models.email_attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0003_emailmessage_dynamic_fields_alter_emailmessage_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Attachment', 'verbose_name_plural': 'Email Attachments'},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Message', 'verbose_name_plural': 'Email Messages'},
        ),
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='email_messa_email_b06907_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='email_messa_status_50c6df_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='email_messa_source_ad1075_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='email_messa_status_5543ab_idx',
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when attachment was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(help_text='Attachment file', upload_to=src.email.models.email_attachment.email_attachment_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='file_size',
            field=models.PositiveIntegerField(help_text='File size in bytes', verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='filename',
            field=models.CharField(help_text='Original filename', max_length=255, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='message',
            field=models.ForeignKey(help_text='Email message this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email.emailmessage', verbose_name='Email Message'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional dynamic fields data', verbose_name='Dynamic Fields'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text="Sender's email address", max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message',
            field=models.TextField(blank=True, help_text='Email message content', null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text="Sender's name", max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='phone',
            field=models.CharField(blank=True, help_text="Sender's phone number", max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when message was read', null=True, verbose_name='Read At'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when message was replied', null=True, verbose_name='Replied At'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who replied to this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='Replied By'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='reply_message',
            field=models.TextField(blank=True, help_text='Reply message content', null=True, verbose_name='Reply Message'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('email', 'Direct Email'), ('api', 'API')], db_index=True, default='website', help_text='Source where the email message originated from', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived'), ('draft', 'Draft')], db_index=True, default='new', help_text='Status of the email message', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, db_index=True, help_text='Email message subject', max_length=300, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string of the sender', null=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', '-created_at'], name='email_messa_status_0c85f8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['source', 'status', '-created_at'], name='email_messa_source_839260_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'created_by', '-created_at'], name='email_messa_status_610939_idx'),
        ),
    ]
