# Generated by Django 6.0 on 2025-12-28 03:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data')),
                ('hreflang_data', models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data')),
                ('title', models.CharField(db_index=True, default='About Us', help_text='About page title', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters.')], verbose_name='Page Title')),
                ('short_description', models.CharField(blank=True, help_text='Short summary of page content (for preview display)', max_length=500, null=True, verbose_name='Short Description')),
                ('content', models.TextField(blank=True, help_text='Main content of about page (HTML supported)', null=True, verbose_name='Page Content')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Main page image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_pages', to='media.imagemedia', verbose_name='Featured Image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'db_table': 'pages_about',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data')),
                ('hreflang_data', models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data')),
                ('title', models.CharField(db_index=True, default='Terms and Conditions', help_text='Terms and conditions page title', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters.')], verbose_name='Page Title')),
                ('short_description', models.CharField(blank=True, help_text='Short summary of page content (for preview display)', max_length=500, null=True, verbose_name='Short Description')),
                ('content', models.TextField(blank=True, help_text='Main content of terms page (HTML supported)', null=True, verbose_name='Page Content')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Main page image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_pages', to='media.imagemedia', verbose_name='Featured Image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
            ],
            options={
                'verbose_name': 'Terms Page',
                'verbose_name_plural': 'Terms Pages',
                'db_table': 'pages_terms',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
