# Generated by Django 5.2.8 on 2025-11-07 07:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0009_remove_aiimageprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(blank=True, default='index,follow', max_length=50, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict, null=True)),
                ('hreflang_data', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(default='درباره ما', help_text='عنوان صفحه درباره ما', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='عنوان باید حداقل 3 کاراکتر باشد')], verbose_name='عنوان صفحه')),
                ('content', models.TextField(blank=True, help_text='متن اصلی صفحه درباره ما (پشتیبانی از HTML)', null=True, verbose_name='محتوای صفحه')),
                ('short_description', models.TextField(blank=True, help_text='خلاصه کوتاه از محتوای صفحه (برای نمایش در پیش\u200cنمایش)', max_length=500, null=True, verbose_name='توضیح کوتاه')),
                ('featured_image', models.ForeignKey(blank=True, help_text='تصویر اصلی صفحه (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_pages', to='media.imagemedia', verbose_name='تصویر شاخص')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
                'db_table': 'pages_about',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['meta_title'], name='pages_about_meta_ti_163ecc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(blank=True, default='index,follow', max_length=50, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict, null=True)),
                ('hreflang_data', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(default='قوانین و مقررات', help_text='عنوان صفحه قوانین و مقررات', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='عنوان باید حداقل 3 کاراکتر باشد')], verbose_name='عنوان صفحه')),
                ('content', models.TextField(blank=True, help_text='متن اصلی صفحه قوانین و مقررات (پشتیبانی از HTML)', null=True, verbose_name='محتوای صفحه')),
                ('short_description', models.TextField(blank=True, help_text='خلاصه کوتاه از محتوای صفحه (برای نمایش در پیش\u200cنمایش)', max_length=500, null=True, verbose_name='توضیح کوتاه')),
                ('featured_image', models.ForeignKey(blank=True, help_text='تصویر اصلی صفحه (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_pages', to='media.imagemedia', verbose_name='تصویر شاخص')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
            ],
            options={
                'verbose_name': 'صفحه قوانین و مقررات',
                'verbose_name_plural': 'صفحه قوانین و مقررات',
                'db_table': 'pages_terms',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['meta_title'], name='pages_terms_meta_ti_6cbd7c_idx')],
            },
        ),
    ]
