# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-created_at'], 'verbose_name': 'About Page', 'verbose_name_plural': 'About Pages'},
        ),
        migrations.AlterModelOptions(
            name='termspage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Terms Page', 'verbose_name_plural': 'Terms Pages'},
        ),
        migrations.RemoveIndex(
            model_name='aboutpage',
            name='pages_about_meta_ti_163ecc_idx',
        ),
        migrations.RemoveIndex(
            model_name='termspage',
            name='pages_terms_meta_ti_6cbd7c_idx',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of about page (HTML supported)', null=True, verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Main page image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_pages', to='media.imagemedia', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short summary of page content (for preview display)', max_length=500, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(db_index=True, default='About Us', help_text='About page title', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters.')], verbose_name='Page Title'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of terms page (HTML supported)', null=True, verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Main page image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_pages', to='media.imagemedia', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short summary of page content (for preview display)', max_length=500, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='title',
            field=models.CharField(db_index=True, default='Terms and Conditions', help_text='Terms and conditions page title', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters.')], verbose_name='Page Title'),
        ),
    ]
