# Generated by Django 5.2.7 on 2025-10-09 01:06

import django.db.models.deletion
import django.utils.timezone
import src.media.models.media
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio')], db_index=True, help_text='Type of media file', max_length=10, verbose_name='Media Type')),
                ('file', models.FileField(help_text='Uploaded media file', upload_to=src.media.models.media.upload_media_path, verbose_name='File')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, help_text='Size of the file in bytes', null=True, verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(blank=True, editable=False, help_text='Media file MIME type', max_length=100, null=True, verbose_name='MIME Type')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility and SEO', max_length=255, verbose_name='ALT Text')),
                ('etag', models.CharField(blank=True, editable=False, help_text='Used for HTTP caching', max_length=40, null=True, verbose_name='ETag')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Cover image for non-image media types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_media', to='media.media', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'abstract': False,
                'indexes': [models.Index(fields=['public_id'], name='media_public__024af4_idx'), models.Index(fields=['is_active', 'created_at'], name='media_is_acti_a4adce_idx'), models.Index(fields=['media_type', 'is_active'], name='media_media_t_187f1d_idx'), models.Index(fields=['created_at'], name='media_created_3b0875_idx')],
            },
        ),
    ]
