# Generated by Django 5.2.7 on 2025-10-11 11:38

import django.db.models.deletion
import django.utils.timezone
import src.media.models.media
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.ImageField(upload_to=src.media.models.media.upload_media_path)),
            ],
            options={
                'verbose_name': 'Image Media',
                'verbose_name_plural': 'Image Media',
                'db_table': 'media_images',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentMedia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=src.media.models.media.upload_media_path)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Cover image for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_documents', to='media.imagemedia')),
            ],
            options={
                'verbose_name': 'Document Media',
                'verbose_name_plural': 'Document Media',
                'db_table': 'media_documents',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioMedia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=src.media.models.media.upload_media_path)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Cover image for this audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_audios', to='media.imagemedia')),
            ],
            options={
                'verbose_name': 'Audio Media',
                'verbose_name_plural': 'Audio Media',
                'db_table': 'media_audios',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=src.media.models.media.upload_media_path)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Cover image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_videos', to='media.imagemedia')),
            ],
            options={
                'verbose_name': 'Video Media',
                'verbose_name_plural': 'Video Media',
                'db_table': 'media_videos',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
