# Generated by Django 5.2.7 on 2025-10-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_fix_existing_media_paths'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiomedia',
            index=models.Index(fields=['public_id'], name='media_audio_public__6258b0_idx'),
        ),
        migrations.AddIndex(
            model_name='audiomedia',
            index=models.Index(fields=['is_active', 'created_at'], name='media_audio_is_acti_a95424_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedia',
            index=models.Index(fields=['public_id'], name='media_docum_public__462207_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedia',
            index=models.Index(fields=['is_active', 'created_at'], name='media_docum_is_acti_cfc5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemedia',
            index=models.Index(fields=['public_id'], name='media_image_public__f9db91_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemedia',
            index=models.Index(fields=['is_active', 'created_at'], name='media_image_is_acti_1b383e_idx'),
        ),
        migrations.AddIndex(
            model_name='videomedia',
            index=models.Index(fields=['public_id'], name='media_video_public__8d014b_idx'),
        ),
        migrations.AddIndex(
            model_name='videomedia',
            index=models.Index(fields=['is_active', 'created_at'], name='media_video_is_acti_88843f_idx'),
        ),
    ]
