# Generated by Django 5.2.7 on 2025-11-01 23:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_audiomedia_media_audio_public__6258b0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageProvider',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('provider_name', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI DALL-E'), ('stable_diffusion', 'Stable Diffusion'), ('midjourney', 'Midjourney'), ('leonardo', 'Leonardo AI')], max_length=50, unique=True, verbose_name='نام مدل')),
                ('api_key', models.TextField(help_text='کلید API مدل (رمزنگاری شده ذخیره می\u200cشود)', verbose_name='API Key')),
                ('is_active', models.BooleanField(default=False, help_text='آیا این مدل برای تولید تصویر فعال است؟', verbose_name='فعال')),
                ('config', models.JSONField(blank=True, default=dict, help_text="تنظیمات اضافی مدل (مثل مدل نسخه، پارامترها و...) - مثال: {'model_version': 'v1', 'max_resolution': '1024x1024'}", verbose_name='تنظیمات اضافی')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='تاریخ و زمان آخرین استفاده از این API', null=True, verbose_name='آخرین استفاده')),
                ('usage_count', models.IntegerField(default=0, help_text='تعداد دفعات استفاده از این API', verbose_name='تعداد استفاده')),
            ],
            options={
                'verbose_name': 'تنظیمات مدل AI',
                'verbose_name_plural': 'تنظیمات مدل\u200cهای AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
