# Generated by Django 5.2.7 on 2025-11-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_aiimageprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimageprovider',
            name='api_key',
            field=models.TextField(blank=True, help_text='کلید API مدل (رمزنگاری شده ذخیره می\u200cشود)', null=True, verbose_name='API Key'),
        ),
    ]
