# Generated by Django 5.2.7 on 2025-11-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_aiimageprovider_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimageprovider',
            name='provider_name',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI DALL-E'), ('huggingface', 'Hugging Face Stable Diffusion (رایگان)'), ('stable_diffusion', 'Stable Diffusion'), ('midjourney', 'Midjourney'), ('leonardo', 'Leonardo AI')], max_length=50, unique=True, verbose_name='نام مدل'),
        ),
    ]
