# Generated by Django 5.2.7 on 2025-11-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_aiimageprovider_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimageprovider',
            name='provider_name',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI DALL-E'), ('huggingface', 'Hugging Face Stable Diffusion (رایگان)')], max_length=50, unique=True, verbose_name='نام مدل'),
        ),
    ]
