# Generated by Django 5.2.8 on 2025-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_remove_aiimageprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audio Media', 'verbose_name_plural': 'Audio Media'},
        ),
        migrations.AlterModelOptions(
            name='documentmedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document Media', 'verbose_name_plural': 'Document Media'},
        ),
        migrations.AlterModelOptions(
            name='imagemedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image Media', 'verbose_name_plural': 'Image Media'},
        ),
        migrations.AlterModelOptions(
            name='videomedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Media', 'verbose_name_plural': 'Video Media'},
        ),
        migrations.RemoveIndex(
            model_name='audiomedia',
            name='media_audio_public__6258b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentmedia',
            name='media_docum_public__462207_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagemedia',
            name='media_image_public__f9db91_idx',
        ),
        migrations.RemoveIndex(
            model_name='videomedia',
            name='media_video_public__8d014b_idx',
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='audiomedia',
            index=models.Index(fields=['created_at'], name='media_audio_created_e54f71_idx'),
        ),
        migrations.AddIndex(
            model_name='audiomedia',
            index=models.Index(fields=['title'], name='media_audio_title_26e1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedia',
            index=models.Index(fields=['created_at'], name='media_docum_created_cee31f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedia',
            index=models.Index(fields=['title'], name='media_docum_title_a71125_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemedia',
            index=models.Index(fields=['created_at'], name='media_image_created_712d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemedia',
            index=models.Index(fields=['title'], name='media_image_title_128d72_idx'),
        ),
        migrations.AddIndex(
            model_name='videomedia',
            index=models.Index(fields=['created_at'], name='media_video_created_106bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='videomedia',
            index=models.Index(fields=['title'], name='media_video_title_33398c_idx'),
        ),
    ]
