# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
import src.media.models.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_alter_audiomedia_options_alter_documentmedia_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='audiomedia',
            name='media_audio_is_acti_a95424_idx',
        ),
        migrations.RemoveIndex(
            model_name='audiomedia',
            name='media_audio_created_e54f71_idx',
        ),
        migrations.RemoveIndex(
            model_name='audiomedia',
            name='media_audio_title_26e1a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentmedia',
            name='media_docum_is_acti_cfc5ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentmedia',
            name='media_docum_created_cee31f_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentmedia',
            name='media_docum_title_a71125_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagemedia',
            name='media_image_is_acti_1b383e_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagemedia',
            name='media_image_created_712d5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagemedia',
            name='media_image_title_128d72_idx',
        ),
        migrations.RemoveIndex(
            model_name='videomedia',
            name='media_video_is_acti_88843f_idx',
        ),
        migrations.RemoveIndex(
            model_name='videomedia',
            name='media_video_created_106bc9_idx',
        ),
        migrations.RemoveIndex(
            model_name='videomedia',
            name='media_video_title_33398c_idx',
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_audios', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Audio duration in seconds', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='etag',
            field=models.CharField(blank=True, editable=False, help_text='Entity tag for cache validation', max_length=40, verbose_name='ETag'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='file',
            field=models.FileField(help_text='Audio file', upload_to=src.media.models.media.upload_media_path, verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, help_text='MIME type of the file', max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Media file title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_documents', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='etag',
            field=models.CharField(blank=True, editable=False, help_text='Entity tag for cache validation', max_length=40, verbose_name='ETag'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='file',
            field=models.FileField(help_text='Document file', upload_to=src.media.models.media.upload_media_path, verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, help_text='MIME type of the file', max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='documentmedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Media file title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='etag',
            field=models.CharField(blank=True, editable=False, help_text='Entity tag for cache validation', max_length=40, verbose_name='ETag'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='file',
            field=models.ImageField(help_text='Image file', upload_to=src.media.models.media.upload_media_path, verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, help_text='MIME type of the file', max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Media file title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_videos', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='etag',
            field=models.CharField(blank=True, editable=False, help_text='Entity tag for cache validation', max_length=40, verbose_name='ETag'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='file',
            field=models.FileField(help_text='Video file', upload_to=src.media.models.media.upload_media_path, verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='File size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, help_text='MIME type of the file', max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Media file title', max_length=200, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='audiomedia',
            index=models.Index(fields=['is_active', '-created_at'], name='media_audio_is_acti_f9f3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmedia',
            index=models.Index(fields=['is_active', '-created_at'], name='media_docum_is_acti_c29474_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemedia',
            index=models.Index(fields=['is_active', '-created_at'], name='media_image_is_acti_e2af4b_idx'),
        ),
        migrations.AddIndex(
            model_name='videomedia',
            index=models.Index(fields=['is_active', '-created_at'], name='media_video_is_acti_e3716e_idx'),
        ),
    ]
