# Generated by Django 5.2.7 on 2025-10-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, unique=True),
        ),
    ]
