# Generated by Django 5.2.7 on 2025-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, unique=True),
        ),
    ]
