# Generated by Django 5.2.7 on 2025-10-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfoliocategory_slug_alter_portfoliotag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliooption',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, unique=True),
        ),
    ]
