# Generated by Django 5.2.7 on 2025-10-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfoliooption_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='portfolio_options', to='portfolio.portfoliooption'),
        ),
    ]
