# Generated by Django 5.2.7 on 2025-10-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliooption',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_options', to='portfolio.portfolio'),
        ),
    ]
