# Generated by Django 5.2.7 on 2025-10-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfoliooption_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliooption',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
