# Generated by Django 5.2.7 on 2025-11-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_remove_aiimageprovider'),
        ('portfolio', '0007_remove_portfoliooption_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioaudio',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='کاور خاص برای این فایل صوتی در این نمونه\u200cکار. اگر تنظیم نشود، از کاور فایل صوتی استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_audio_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='portfoliodocument',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='کاور خاص برای این سند در این نمونه\u200cکار. اگر تنظیم نشود، از کاور سند استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_document_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='کاور خاص برای این ویدیو در این نمونه\u200cکار. اگر تنظیم نشود، از کاور ویدیو استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_video_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
    ]
