# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
        ('portfolio', '0008_portfolioaudio_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfolioaudio',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Audio', 'verbose_name_plural': 'Portfolio Audios'},
        ),
        migrations.AlterModelOptions(
            name='portfoliodocument',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Document', 'verbose_name_plural': 'Portfolio Documents'},
        ),
        migrations.AlterModelOptions(
            name='portfoliooption',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio Option', 'verbose_name_plural': 'Portfolio Options'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotag',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio Tag', 'verbose_name_plural': 'Portfolio Tags'},
        ),
        migrations.AlterModelOptions(
            name='portfoliovideo',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Video', 'verbose_name_plural': 'Portfolio Videos'},
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_status_d0b4a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_title_375942_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_slug_7d8eaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_public__928d3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_is_feat_f033e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_created_8fae84_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_l_meta_ti_951c2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliocategory',
            name='portfolio_c_name_f8c29a_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliocategory',
            name='portfolio_c_slug_e26007_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliocategory',
            name='portfolio_c_public__3c181f_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliocategory',
            name='portfolio_c_is_publ_c4cf1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliocategory',
            name='portfolio_c_meta_ti_8322ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliooption',
            name='portfolio_o_name_064e09_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliooption',
            name='portfolio_o_slug_610bd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliooption',
            name='portfolio_o_public__788b62_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliooption',
            name='portfolio_o_is_publ_079a0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliooption',
            name='portfolio_o_meta_ti_5465f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliotag',
            name='portfolio_t_name_d5a699_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliotag',
            name='portfolio_t_slug_d5dd1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliotag',
            name='portfolio_t_public__9acb2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliotag',
            name='portfolio_t_is_publ_6565df_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliotag',
            name='portfolio_t_meta_ti_878534_idx',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories associated with this portfolio item', related_name='portfolio_categories', to='portfolio.portfoliocategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, help_text='Full content of the portfolio item', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this portfolio item is featured', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this portfolio item is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='Options associated with this portfolio item', related_name='portfolio_options', to='portfolio.portfoliooption', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief summary of the portfolio item', max_length=300, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the portfolio item', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Publication status of the portfolio item', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this portfolio item', related_name='portfolio_tags', to='portfolio.portfoliotag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(db_index=True, help_text='Portfolio item title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='audio',
            field=models.ForeignKey(help_text='Audio media file', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='media.audiomedia', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Whether the audio should autoplay', verbose_name='Autoplay'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_audio_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='loop',
            field=models.BooleanField(default=False, help_text='Whether the audio should loop', verbose_name='Loop'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this audio should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='portfolioaudio',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio item this audio belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='portfolio.portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main image for this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_category_images', to='media.imagemedia', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this category is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(db_index=True, help_text='Category name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the category', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_document_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='document',
            field=models.ForeignKey(help_text='Document media file', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='media.documentmedia', verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this document should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio item this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portfolio.portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title for this document (optional)', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ForeignKey(help_text='Image media file', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='media.imagemedia', verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this is the main image for the portfolio item', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this image should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='description',
            field=models.TextField(blank=True, help_text='Option description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this option is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='name',
            field=models.CharField(db_index=True, help_text='Option name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the option', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='description',
            field=models.TextField(blank=True, help_text='Tag description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this tag is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='name',
            field=models.CharField(db_index=True, help_text='Tag name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the tag', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='portfoliotag',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Whether the video should autoplay', verbose_name='Autoplay'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_video_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='mute',
            field=models.BooleanField(default=True, help_text='Whether the video should be muted by default', verbose_name='Mute'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this video should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio item this video belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='show_cover',
            field=models.BooleanField(default=True, help_text='Whether to show the cover image before playback', verbose_name='Show Cover'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='video',
            field=models.ForeignKey(help_text='Video media file', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='media.videomedia', verbose_name='Video File'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['status', 'is_public', '-created_at'], name='portfolio_l_status_909bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_featured', 'status', '-created_at'], name='portfolio_l_is_feat_cebe00_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliocategory',
            index=models.Index(fields=['is_public', 'path'], name='portfolio_c_is_publ_aaebb1_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliooption',
            index=models.Index(fields=['is_public', 'name'], name='portfolio_o_is_publ_11f18a_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotag',
            index=models.Index(fields=['is_public', 'name'], name='portfolio_t_is_publ_9fbe88_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioaudio',
            constraint=models.UniqueConstraint(fields=('portfolio', 'audio'), name='unique_portfolio_audio'),
        ),
        migrations.AddConstraint(
            model_name='portfoliodocument',
            constraint=models.UniqueConstraint(fields=('portfolio', 'document'), name='unique_portfolio_document'),
        ),
        migrations.AddConstraint(
            model_name='portfolioimage',
            constraint=models.UniqueConstraint(fields=('portfolio', 'image'), name='unique_portfolio_image'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovideo',
            constraint=models.UniqueConstraint(fields=('portfolio', 'video'), name='unique_portfolio_video'),
        ),
    ]
