PUBLIC_PROPERTY_LIST_TTL = 120
PUBLIC_PROPERTY_DETAIL_TTL = 300
PUBLIC_PROPERTY_FEATURED_TTL = 120
PUBLIC_PROPERTY_RELATED_TTL = 180

PUBLIC_TAXONOMY_LIST_TTL = 900
PUBLIC_TAXONOMY_DETAIL_TTL = 1800
PUBLIC_TAXONOMY_POPULAR_TTL = 1800

PUBLIC_AGENT_LIST_TTL = 180
PUBLIC_AGENT_DETAIL_TTL = 300
PUBLIC_AGENT_STATS_TTL = 300

PUBLIC_AGENCY_LIST_TTL = 180
PUBLIC_AGENCY_DETAIL_TTL = 300
PUBLIC_AGENCY_STATS_TTL = 300
PUBLIC_AGENCY_WITH_AGENTS_TTL = 180

PUBLIC_FLOOR_PLAN_LIST_TTL = 300
PUBLIC_FLOOR_PLAN_DETAIL_TTL = 600

ADMIN_TYPE_ROOTS_TTL = 300
ADMIN_TYPE_TREE_TTL = 900
ADMIN_TYPE_POPULAR_TTL = 600
ADMIN_TYPE_STATS_TTL = 300
ADMIN_TAXONOMY_LIST_TTL = 20

ADMIN_TAG_DETAIL_TTL = 3600
ADMIN_TAG_POPULAR_TTL = 3600

ADMIN_PROPERTY_LIST_TTL = 20
ADMIN_PROPERTY_YEAR_CHOICES_TTL = 3600
ADMIN_PROPERTY_SEO_REPORT_TTL = 600
ADMIN_PROPERTY_STATISTICS_TTL = 600
