import type { RouteRule } from "../types";

const ID_SEGMENT = "[0-9a-zA-Z-]+";
const createRule = (config: RouteRule): RouteRule => config;

export const realEstateRoutes: RouteRule[] = [
  createRule({
    id: "property-statistics",
    pattern: /^\/real-estate\/statistics\/?$/,
    module: 'real_estate.property',
    action: "read",
    description: "آمار املاک",
  }),
  createRule({
    id: "property-list",
    pattern: /^\/real-estate\/properties\/?$/,
    module: 'real_estate.property',
    action: "read",
    description: "لیست املاک",
  }),
  createRule({
    id: "property-create",
    pattern: /^\/real-estate\/properties\/create\/?$/,
    module: 'real_estate.property',
    action: "create",
    description: "ایجاد ملک",
  }),
  createRule({
    id: "property-edit",
    pattern: new RegExp(`^/real-estate/properties/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.property',
    action: "update",
    description: "ویرایش ملک",
  }),
  createRule({
    id: "property-view",
    pattern: new RegExp(`^/real-estate/properties/${ID_SEGMENT}/view/?$`),
    module: 'real_estate.property',
    action: "read",
    description: "مشاهده ملک",
  }),
  createRule({
    id: "property-types",
    pattern: /^\/real-estate\/types\/?$/,
    module: 'real_estate.type',
    action: "read",
    description: "لیست نوع‌های ملک",
  }),
  createRule({
    id: "property-type-create",
    pattern: /^\/real-estate\/types\/create\/?$/,
    module: 'real_estate.type',
    action: "create",
    description: "ایجاد نوع ملک",
  }),
  createRule({
    id: "property-type-edit",
    pattern: new RegExp(`^/real-estate/types/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.type',
    action: "update",
    description: "ویرایش نوع ملک",
  }),
  createRule({
    id: "property-states",
    pattern: /^\/real-estate\/states\/?$/,
    module: 'real_estate.state',
    action: "read",
    description: "لیست وضعیت‌های ملک",
  }),
  createRule({
    id: "property-state-create",
    pattern: /^\/real-estate\/states\/create\/?$/,
    module: 'real_estate.state',
    action: "create",
    description: "ایجاد وضعیت ملک",
  }),
  createRule({
    id: "property-state-edit",
    pattern: new RegExp(`^/real-estate/states/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.state',
    action: "update",
    description: "ویرایش وضعیت ملک",
  }),
  createRule({
    id: "property-labels",
    pattern: /^\/real-estate\/labels\/?$/,
    module: 'real_estate.label',
    action: "read",
    description: "لیست برچسب‌های ملک",
  }),
  createRule({
    id: "property-label-create",
    pattern: /^\/real-estate\/labels\/create\/?$/,
    module: 'real_estate.label',
    action: "create",
    description: "ایجاد برچسب ملک",
  }),
  createRule({
    id: "property-label-edit",
    pattern: new RegExp(`^/real-estate/labels/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.label',
    action: "update",
    description: "ویرایش برچسب ملک",
  }),
  createRule({
    id: "property-features",
    pattern: /^\/real-estate\/features\/?$/,
    module: 'real_estate.feature',
    action: "read",
    description: "لیست ویژگی‌های ملک",
  }),
  createRule({
    id: "property-feature-create",
    pattern: /^\/real-estate\/features\/create\/?$/,
    module: 'real_estate.feature',
    action: "create",
    description: "ایجاد ویژگی ملک",
  }),
  createRule({
    id: "property-feature-edit",
    pattern: new RegExp(`^/real-estate/features/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.feature',
    action: "update",
    description: "ویرایش ویژگی ملک",
  }),
  createRule({
    id: "property-tags",
    pattern: /^\/real-estate\/tags\/?$/,
    module: 'real_estate.tag',
    action: "read",
    description: "لیست تگ‌های ملک",
  }),
  createRule({
    id: "property-tag-create",
    pattern: /^\/real-estate\/tags\/create\/?$/,
    module: 'real_estate.tag',
    action: "create",
    description: "ایجاد تگ ملک",
  }),
  createRule({
    id: "property-tag-edit",
    pattern: new RegExp(`^/real-estate/tags/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.tag',
    action: "update",
    description: "ویرایش تگ ملک",
  }),
  createRule({
    id: "property-agents",
    pattern: /^\/real-estate\/agents\/?$/,
    module: 'real_estate.agent',
    action: "read",
    description: "لیست نمایندگان",
  }),
  createRule({
    id: "property-agent-create",
    pattern: /^\/real-estate\/agents\/create\/?$/,
    module: 'real_estate.agent',
    action: "create",
    description: "ایجاد نماینده",
  }),
  createRule({
    id: "property-agent-edit",
    pattern: new RegExp(`^/real-estate/agents/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.agent',
    action: "update",
    description: "ویرایش نماینده",
  }),
  createRule({
    id: "real-estate-agencies",
    pattern: /^\/real-estate\/agencies\/?$/,
    module: 'real_estate.agency',
    action: "read",
    description: "لیست آژانس‌ها",
  }),
  createRule({
    id: "real-estate-agency-create",
    pattern: /^\/real-estate\/agencies\/create\/?$/,
    module: 'real_estate.agency',
    action: "create",
    description: "ایجاد آژانس",
  }),
  createRule({
    id: "real-estate-agency-edit",
    pattern: new RegExp(`^/real-estate/agencies/${ID_SEGMENT}/edit/?$`),
    module: 'real_estate.agency',
    action: "update",
    description: "ویرایش آژانس",
  }),
  createRule({
    id: "real-estate-provinces",
    pattern: /^\/real-estate\/provinces\/?$/,
    module: 'real_estate.location',
    action: "read",
    description: "لیست استان‌ها",
  }),
  createRule({
    id: "real-estate-cities",
    pattern: /^\/real-estate\/cities\/?$/,
    module: 'real_estate.location',
    action: "read",
    description: "لیست شهرها",
  }),
  createRule({
    id: "real-estate-regions",
    pattern: /^\/real-estate\/regions\/?$/,
    module: 'real_estate.location',
    action: "read",
    description: "لیست مناطق",
  }),
];
