export type PropertySearchFilters = {
  search: string;
  status: string;
  is_featured: boolean | null;
  is_public: boolean | null;
  is_active: boolean | null;
  property_type: number | null;
  state: number | null;
  city: number | null;
  province: number | null;
  city_slug: string;
  province_slug: string;
  region: number | null;
  min_price: number | null;
  max_price: number | null;
  min_area: number | null;
  max_area: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  kitchens: number | null;
  living_rooms: number | null;
  year_built: number | null;
  parking_spaces: number | null;
  storage_rooms: number | null;
  has_parking: boolean | null;
  has_storage: boolean | null;
  has_elevator: boolean | null;
  created_after: string;
  created_before: string;
  type_slug: string;
  state_slug: string;
  tag_slug: string;
  label_slug: string;
  label_public_id: string;
  feature_public_id: string;
  order_by: string;
  order_desc: boolean;
  page: number;
};
