PUBLIC_GENERAL_SETTINGS_TTL = 300
PUBLIC_CONTACT_TTL = 300
PUBLIC_FOOTER_TTL = 900
PUBLIC_FOOTER_ABOUT_TTL = 900
PUBLIC_BRANDING_LOGO_TTL = 300
PUBLIC_BRANDING_SLIDERS_TTL = 120

ADMIN_GENERAL_SETTINGS_TTL = 60
ADMIN_LIST_TTL = 60
SINGLETON_MODEL_PK_TTL = 3600
