USER_PERMISSION_CACHE_TTL = 300
USER_SIMPLE_PERMISSIONS_TTL = 600
USER_PERMISSION_MAP_TTL = 3600
USER_PERMISSION_DISPLAY_NAME_TTL = 86400

USER_ADMIN_PROFILE_CACHE_TTL = 300
USER_SUPERADMIN_PROFILE_CACHE_TTL = 1800

USER_ADMIN_PERMISSION_CHECK_SUPERADMIN_TTL = 600
USER_ADMIN_PERMISSION_CHECK_READ_TTL = 300
USER_ADMIN_PERMISSION_CHECK_WRITE_TTL = 60

USER_ADMIN_SESSION_CHECK_TTL = 5

USER_LOCATION_PROVINCES_TTL = 3600
USER_LOCATION_PROVINCES_LIST_TTL = 1800
USER_LOCATION_PROVINCE_CITIES_TTL = 3600
USER_LOCATION_DROPDOWN_TTL = 7200
USER_LOCATION_CITIES_BY_PROVINCE_LIST_TTL = 1800
USER_LOCATION_ALL_CITIES_LIST_TTL = 900
USER_LOCATION_CITIES_DROPDOWN_TTL = 7200
