USER_PERMISSION_CACHE_TTL = 300
USER_SIMPLE_PERMISSIONS_TTL = 600
USER_PERMISSION_MAP_TTL = 3600
USER_PERMISSION_DISPLAY_NAME_TTL = 86400

USER_ADMIN_PROFILE_CACHE_TTL = 300
USER_SUPERADMIN_PROFILE_CACHE_TTL = 1800

USER_ADMIN_PERMISSION_CHECK_SUPERADMIN_TTL = 600
USER_ADMIN_PERMISSION_CHECK_READ_TTL = 300
USER_ADMIN_PERMISSION_CHECK_WRITE_TTL = 60
