# Generated by Django 6.0 on 2025-12-30 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('mobile', models.CharField(blank=True, help_text="User's mobile number, unique and used as primary identifier", max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Enter a valid Iranian mobile number')], verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, help_text="User's email address, optional but unique", max_length=254, null=True, unique=True, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin User')], db_index=True, default='user', help_text='Type of user: user (website) or admin (panel)', max_length=10, verbose_name='User Type')),
                ('is_staff', models.BooleanField(db_index=True, default=False, help_text='Designates whether user can log into admin panel', verbose_name='Staff Status')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, help_text='Designates that user has all permissions without explicitly assigning them', verbose_name='Superuser Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user should be treated as active', verbose_name='Active Status')),
                ('is_admin_active', models.BooleanField(db_index=True, default=False, help_text='Designates whether user can access admin panel', verbose_name='Admin Active Status')),
                ('is_admin_full', models.BooleanField(db_index=True, default=False, help_text='Designates admin with full access and bypass all permissions', verbose_name='Full Admin Access')),
                ('last_login_admin', models.DateTimeField(blank=True, db_index=True, help_text='Last time user logged into admin panel', null=True, verbose_name='Last Admin Login')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when user was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when user was last updated', verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('first_name', models.CharField(blank=True, help_text="Admin's first name", max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text="Admin's last name", max_length=50, null=True, verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, help_text='Brief description about the admin', null=True, verbose_name='Biography')),
                ('address', models.TextField(blank=True, help_text="Admin's address", null=True, verbose_name='Address')),
                ('birth_date', models.DateField(blank=True, help_text="Admin's birth date", null=True, verbose_name='Birth Date')),
                ('national_id', models.CharField(blank=True, db_index=True, help_text="Admin's national ID (unique)", max_length=20, null=True, unique=True, verbose_name='National ID')),
                ('phone', models.CharField(blank=True, db_index=True, help_text="Admin's additional phone number (different from mobile for authentication)", max_length=15, null=True, unique=True, verbose_name='Phone Number')),
                ('admin_user', models.OneToOneField(help_text='The admin user this profile belongs to', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
                ('city', models.ForeignKey(blank=True, help_text="Admin's city", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='core.city', verbose_name='City')),
                ('profile_picture', models.ForeignKey(blank=True, help_text="Admin's profile picture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='media.imagemedia', verbose_name='Profile Picture')),
                ('province', models.ForeignKey(blank=True, help_text="Admin's province", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='core.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_profiles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Role name for admin panel (can be custom or predefined)', max_length=50, unique=True, verbose_name='Role Name')),
                ('display_name', models.CharField(help_text='Human-readable role name', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this role', verbose_name='Description')),
                ('permissions', models.JSONField(default=dict, help_text="JSON structure: {'modules': ['users', 'media'], 'actions': ['read', 'create', 'update']}", verbose_name='Permissions')),
                ('level', models.PositiveIntegerField(db_index=True, default=5, help_text='Role hierarchy level (1=highest, 10=lowest)', verbose_name='Role Level')),
                ('is_system_role', models.BooleanField(db_index=True, default=True, help_text='System roles cannot be deleted', verbose_name='System Role')),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'db_table': 'admin_roles',
                'ordering': ['level', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name', 'is_active'], name='admin_roles_name_fc278a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminUserRole',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('permissions_cache', models.JSONField(blank=True, default=dict, help_text='Cached permissions for performance', verbose_name='Permissions Cache')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when role was assigned', verbose_name='Assigned At')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiry date for this role assignment', null=True, verbose_name='Expires At')),
                ('last_cache_update', models.DateTimeField(auto_now=True, help_text='Date and time when permissions cache was last updated', verbose_name='Last Cache Update')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Super admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('role', models.ForeignKey(help_text='Role assigned to the admin user', on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_roles', to='user.adminrole', verbose_name='Admin Role')),
                ('user', models.ForeignKey(help_text='Admin user for this role assignment', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'Admin User Role',
                'verbose_name_plural': 'Admin User Roles',
                'db_table': 'admin_user_roles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Permission name', max_length=255, verbose_name='Name')),
                ('codename', models.CharField(db_index=True, help_text='Unique code name for the permission', max_length=100, unique=True, verbose_name='Code Name')),
                ('description', models.TextField(blank=True, help_text='Permission description', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission (Legacy)',
                'verbose_name_plural': 'Permissions (Legacy)',
                'db_table': 'custom_permissions',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['codename', 'name'], name='custom_perm_codenam_f797e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Role name', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Role description', null=True, verbose_name='Description')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, help_text='Designates whether this role has superuser privileges', verbose_name='Superuser')),
            ],
            options={
                'verbose_name': 'Role (Legacy)',
                'verbose_name_plural': 'Roles (Legacy)',
                'db_table': 'roles',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_superuser', 'name'], name='roles_is_supe_df0e96_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('permission', models.ForeignKey(help_text='Permission assigned to the role', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_role_permissions', to='user.custompermission', verbose_name='Permission')),
                ('role', models.ForeignKey(help_text='Role assigned to this permission', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_role_permissions', to='user.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role Permission (Legacy)',
                'verbose_name_plural': 'Role Permissions (Legacy)',
                'db_table': 'role_permissions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('first_name', models.CharField(blank=True, help_text='The first name of the user', max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='The last name of the user', max_length=30, null=True, verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, help_text='A short biography or description about the user', null=True, verbose_name='Biography')),
                ('address', models.TextField(blank=True, help_text='The address of the user', null=True, verbose_name='Address')),
                ('birth_date', models.DateField(blank=True, help_text='The birth date of the user', null=True, verbose_name='Birth Date')),
                ('national_id', models.CharField(blank=True, db_index=True, help_text='The national ID of the user (unique)', max_length=20, null=True, unique=True, verbose_name='National ID')),
                ('phone', models.CharField(blank=True, db_index=True, help_text="User's additional phone number (different from mobile for authentication)", max_length=15, null=True, unique=True, verbose_name='Phone Number')),
                ('city', models.ForeignKey(blank=True, help_text="User's city", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.city', verbose_name='City')),
                ('profile_picture', models.ForeignKey(blank=True, help_text="User's profile picture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='media.imagemedia', verbose_name='Profile Picture')),
                ('province', models.ForeignKey(blank=True, help_text="User's province", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.province', verbose_name='Province')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_user_roles', to='user.role', verbose_name='Role')),
                ('user', models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Role (Legacy)',
                'verbose_name_plural': 'User Roles (Legacy)',
                'db_table': 'user_roles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_admin_active', '-created_at'], name='user_type_admin_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'is_admin_active', '-created_at'], name='user_staff_admin_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', '-created_at'], name='user_active_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('mobile__isnull', False), ('email__isnull', False), _connector='OR'), name='user_mobile_or_email_required'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_admin_full', False), models.Q(('is_admin_full', True), ('is_staff', True), ('is_admin_active', True)), _connector='OR'), name='super_admin_must_be_staff_with_panel_access'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['province', 'city'], name='admin_profi_provinc_002a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserrole',
            index=models.Index(fields=['user', 'is_active'], name='admin_user__user_id_94d71d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserrole',
            index=models.Index(fields=['role', 'is_active'], name='admin_user__role_id_4e81bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adminuserrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='role_permis_role_id_acd841_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='role_permis_permiss_822e1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['province', 'city'], name='user_profil_provinc_bdbba0_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='user_roles_user_id_4ec42c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='user_roles_role_id_57352b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
