# Generated by Django 6.0 on 2025-12-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_province_city_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='cities_provinc_e3ddcb_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='cities_is_acti_f2e5d6_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text="User's city", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text="Admin's city", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='core.city', verbose_name='City'),
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='provinces_is_acti_d6b5a4_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.ForeignKey(blank=True, help_text="User's province", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='province',
            field=models.ForeignKey(blank=True, help_text="Admin's province", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='core.province', verbose_name='Province'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
