# Generated by Django 5.2.7 on 2025-10-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text="Admin's additional phone number (different from mobile for authentication)", max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text="User's additional phone number (different from mobile for authentication)", max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
