# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
        ('user', '0002_alter_adminprofile_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Profile', 'verbose_name_plural': 'Admin Profiles'},
        ),
        migrations.AlterModelOptions(
            name='adminuserrole',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin User Role', 'verbose_name_plural': 'Admin User Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Role Permission (Legacy)', 'verbose_name_plural': 'Role Permissions (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Role (Legacy)', 'verbose_name_plural': 'User Roles (Legacy)'},
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_national_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_public_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_pic_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_province_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminprofile',
            name='admin_profile_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminrole',
            name='admin_role_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminrole',
            name='admin_role_public_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminuserrole',
            name='adm_usr_role_exp_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminuserrole',
            name='adm_usr_role_pub_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='city_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='city_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='city_public_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='province_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='province_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='province_public_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_type_admin_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_admin_full_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_mobile_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_last_login_admin_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_public_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_active_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_staff_admin_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_national_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_public_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_pic_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_province_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_city_idx',
        ),
        migrations.RenameIndex(
            model_name='adminrole',
            new_name='admin_roles_name_fc278a_idx',
            old_name='admin_role_name_active_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserrole',
            new_name='admin_user__user_id_94d71d_idx',
            old_name='adm_usr_role_usr_act_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserrole',
            new_name='admin_user__role_id_4e81bc_idx',
            old_name='adm_usr_role_role_act_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cities_provinc_e3ddcb_idx',
            old_name='city_province_name_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cities_is_acti_f2e5d6_idx',
            old_name='city_active_province_idx',
        ),
        migrations.RenameIndex(
            model_name='province',
            new_name='provinces_is_acti_d6b5a4_idx',
            old_name='province_active_name_idx',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Admin's address", null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_user',
            field=models.OneToOneField(help_text='The admin user this profile belongs to', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Admin User'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description about the admin', null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Admin's birth date", null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text="Admin's first name", max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text="Admin's last name", max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text="Admin's national ID (unique)", max_length=20, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='is_system_role',
            field=models.BooleanField(db_index=True, default=True, help_text='System roles cannot be deleted', verbose_name='System Role'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when role was assigned', verbose_name='Assigned At'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Super admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='last_cache_update',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when permissions cache was last updated', verbose_name='Last Cache Update'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='role',
            field=models.ForeignKey(help_text='Role assigned to the admin user', on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_roles', to='user.adminrole', verbose_name='Admin Role'),
        ),
        migrations.AlterField(
            model_name='adminuserrole',
            name='user',
            field=models.ForeignKey(help_text='Admin user for this role assignment', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Admin User'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(db_index=True, help_text='Unique code name for the permission', max_length=100, unique=True, verbose_name='Code Name'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='description',
            field=models.TextField(blank=True, help_text='Permission description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(db_index=True, help_text='Permission name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='province',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='province',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Role description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this role has superuser privileges', verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, help_text='Role name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(help_text='Permission assigned to the role', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_role_permissions', to='user.custompermission', verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(help_text='Role assigned to this permission', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_role_permissions', to='user.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='The address of the user', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography or description about the user', null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='The birth date of the user', null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first name of the user', max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the user', max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='The national ID of the user (unique)', max_length=20, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_user_roles', to='user.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['province', 'city'], name='admin_profi_provinc_002a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='custompermission',
            index=models.Index(fields=['codename', 'name'], name='custom_perm_codenam_f797e4_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_superuser', 'name'], name='roles_is_supe_df0e96_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='role_permis_role_id_acd841_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='role_permis_permiss_822e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_admin_active', '-created_at'], name='user_type_admin_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'is_admin_active', '-created_at'], name='user_staff_admin_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', '-created_at'], name='user_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['province', 'city'], name='user_profil_provinc_bdbba0_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='user_roles_user_id_4ec42c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='user_roles_role_id_57352b_idx'),
        ),
    ]
