type ColorMode = "light" | "dark";

export type ColorScheme = {
    surface: string;
    border: string;
    text: string;
    mutedText: string;
    accent: string;
    accentText: string;
    iconBg: string;
    icon: string;
    highlight: string;
};

export type ColorPaletteItem = {
    name: string;
    title: string;
    description: string;
    usage: string[];
    colors: Record<ColorMode, ColorScheme>;
};

export const colorPaletteShowcase: ColorPaletteItem[] = [
    {
        name: "emerald-glow",
        title: "Emerald Glow",
        description: "مناسب برای موفقیت، وضعیت‌های مالی مثبت و اعلان‌های تایید شده.",
        usage: ["موفقیت عملیات", "کارت‌های مالی", "نمودار رشد"],
        colors: {
            light: {
                surface: "#ECFDF5",
                border: "#A7F3D0",
                text: "#065F46",
                mutedText: "#0F172A",
                accent: "#10B981",
                accentText: "#FFFFFF",
                iconBg: "#34D399",
                icon: "#FFFFFF",
                highlight: "#DCFCE7",
            },
            dark: {
                surface: "#022C22",
                border: "#064E3B",
                text: "#A7F3D0",
                mutedText: "#D1FAE5",
                accent: "#10B981",
                accentText: "#022C22",
                iconBg: "#34D399",
                icon: "#022C22",
                highlight: "#064E3B",
            },
        },
    },
    {
        name: "ocean-drive",
        title: "Ocean Drive",
        description: "برای داده‌های تحلیلی، وضعیت پایدار و پیام‌های اطلاع‌رسانی.",
        usage: ["کارت آمار", "وضعیت سرویس", "نمودار آب و هوا"],
        colors: {
            light: {
                surface: "#EFF6FF",
                border: "#BFDBFE",
                text: "#1E3A8A",
                mutedText: "#1F2937",
                accent: "#3B82F6",
                accentText: "#FFFFFF",
                iconBg: "#2563EB",
                icon: "#FFFFFF",
                highlight: "#DBEAFE",
            },
            dark: {
                surface: "#0B1B34",
                border: "#1E3A8A",
                text: "#DBEAFE",
                mutedText: "#93C5FD",
                accent: "#3B82F6",
                accentText: "#0B1B34",
                iconBg: "#2563EB",
                icon: "#0B1B34",
                highlight: "#1E3A8A",
            },
        },
    },
    {
        name: "royal-grape",
        title: "Royal Grape",
        description: "برای ویژگی‌های ویژه، بخش‌های VIP و کارت‌های معرفی تیم.",
        usage: ["سطح دسترسی", "پروموشن ویژه", "تگ پروفایل"],
        colors: {
            light: {
                surface: "#F5F3FF",
                border: "#DDD6FE",
                text: "#4C1D95",
                mutedText: "#312E81",
                accent: "#8B5CF6",
                accentText: "#F8FAFC",
                iconBg: "#7C3AED",
                icon: "#F8FAFC",
                highlight: "#EDE9FE",
            },
            dark: {
                surface: "#261148",
                border: "#4C1D95",
                text: "#EDE9FE",
                mutedText: "#C4B5FD",
                accent: "#8B5CF6",
                accentText: "#1E1B4B",
                iconBg: "#7C3AED",
                icon: "#EDE9FE",
                highlight: "#3B1D70",
            },
        },
    },
    {
        name: "sunset-amber",
        title: "Sunset Amber",
        description: "برای اعلان‌های مهم، هشدارهای ملایم و کارت‌های فعالیت.",
        usage: ["هشدار نرم", "برجسته‌سازی KPI", "وضعیت در انتظار"],
        colors: {
            light: {
                surface: "#FFF7ED",
                border: "#FED7AA",
                text: "#9A3412",
                mutedText: "#B45309",
                accent: "#F97316",
                accentText: "#1F2937",
                iconBg: "#FB923C",
                icon: "#1F2937",
                highlight: "#FFEDD5",
            },
            dark: {
                surface: "#431407",
                border: "#92400E",
                text: "#FDE68A",
                mutedText: "#F97316",
                accent: "#F97316",
                accentText: "#431407",
                iconBg: "#FB923C",
                icon: "#431407",
                highlight: "#78350F",
            },
        },
    },
    {
        name: "blush-rose",
        title: "Blush Rose",
        description: "برای کمپین‌های بازاریابی، اعلان‌های دوستانه و تگ‌های شخصی.",
        usage: ["کمپین بازاریابی", "تگ مشتری", "باخبرسازی دوستانه"],
        colors: {
            light: {
                surface: "#FFF1F2",
                border: "#FECDD3",
                text: "#9D174D",
                mutedText: "#9F1239",
                accent: "#F43F5E",
                accentText: "#FFFFFF",
                iconBg: "#FB7185",
                icon: "#FFFFFF",
                highlight: "#FFE4E6",
            },
            dark: {
                surface: "#4C0519",
                border: "#9F1239",
                text: "#FBCFE8",
                mutedText: "#FDA4AF",
                accent: "#F43F5E",
                accentText: "#4C0519",
                iconBg: "#FB7185",
                icon: "#4C0519",
                highlight: "#881337",
            },
        },
    },
    {
        name: "slate-mist",
        title: "Slate Mist",
        description: "برای وضعیت‌های خنثی، داده‌های آرشیوی و کارت‌های ثبات سیستم.",
        usage: ["وضعیت خنثی", "برچسب آرشیو", "گزارش‌های داخلی"],
        colors: {
            light: {
                surface: "#F8FAFC",
                border: "#E2E8F0",
                text: "#0F172A",
                mutedText: "#475569",
                accent: "#94A3B8",
                accentText: "#0F172A",
                iconBg: "#CBD5F5",
                icon: "#0F172A",
                highlight: "#E2E8F0",
            },
            dark: {
                surface: "#111827",
                border: "#1F2937",
                text: "#E2E8F0",
                mutedText: "#94A3B8",
                accent: "#64748B",
                accentText: "#E2E8F0",
                iconBg: "#334155",
                icon: "#E2E8F0",
                highlight: "#1F2937",
            },
        },
    },
    {
        name: "midnight-sky",
        title: "Midnight Sky",
        description: "برای داشبوردهای تاریک، کارت‌های امنیتی و وضعیت بحرانی.",
        usage: ["امنیت سیستم", "وضعیت بحرانی", "کارت‌های حرفه‌ای"],
        colors: {
            light: {
                surface: "#1E293B",
                border: "#334155",
                text: "#E2E8F0",
                mutedText: "#94A3B8",
                accent: "#0EA5E9",
                accentText: "#F8FAFC",
                iconBg: "#0284C7",
                icon: "#E0F2FE",
                highlight: "#0F172A",
            },
            dark: {
                surface: "#0B1220",
                border: "#1E293B",
                text: "#BAE6FD",
                mutedText: "#7DD3FC",
                accent: "#0EA5E9",
                accentText: "#031525",
                iconBg: "#0284C7",
                icon: "#BAE6FD",
                highlight: "#12263A",
            },
        },
    },
    {
        name: "arctic-cyan",
        title: "Arctic Cyan",
        description: "برای ماژول‌های تکنیکال، دیتاهای API و کامپوننت‌های توسعه.",
        usage: ["حالت توسعه", "وضعیت API", "کارت‌های تکنیکال"],
        colors: {
            light: {
                surface: "#ECFEFF",
                border: "#A5F3FC",
                text: "#0E7490",
                mutedText: "#155E75",
                accent: "#06B6D4",
                accentText: "#FFFFFF",
                iconBg: "#0891B2",
                icon: "#E0F2FE",
                highlight: "#CFFAFE",
            },
            dark: {
                surface: "#083344",
                border: "#155E75",
                text: "#BAE6FD",
                mutedText: "#7DD3FC",
                accent: "#06B6D4",
                accentText: "#042F3E",
                iconBg: "#0E7490",
                icon: "#BAE6FD",
                highlight: "#164E63",
            },
        },
    },
    {
        name: "forest-mist",
        title: "Forest Mist",
        description: "برای ماژول‌های منابع انسانی، سلامت و کارت‌های وضعیت کارمندان.",
        usage: ["وضعیت کارمند", "پیشرفت شخصی", "کارت‌های سلامت"],
        colors: {
            light: {
                surface: "#F0FDF4",
                border: "#BBF7D0",
                text: "#14532D",
                mutedText: "#166534",
                accent: "#22C55E",
                accentText: "#0E1C10",
                iconBg: "#16A34A",
                icon: "#F8FAFC",
                highlight: "#DCFCE7",
            },
            dark: {
                surface: "#052E16",
                border: "#14532D",
                text: "#DCFCE7",
                mutedText: "#86EFAC",
                accent: "#22C55E",
                accentText: "#052E16",
                iconBg: "#15803D",
                icon: "#DCFCE7",
                highlight: "#166534",
            },
        },
    },
    {
        name: "golden-hour",
        title: "Golden Hour",
        description: "برای هوش مصنوعی، کارت‌های امتیاز و صفحات معرفی محصول.",
        usage: ["امتیاز AI", "معرفی ویژگی", "نمودار فعالیت"],
        colors: {
            light: {
                surface: "#FEFCE8",
                border: "#FDE68A",
                text: "#854D0E",
                mutedText: "#92400E",
                accent: "#EAB308",
                accentText: "#1E1B4B",
                iconBg: "#D97706",
                icon: "#FEF3C7",
                highlight: "#FEF3C7",
            },
            dark: {
                surface: "#422006",
                border: "#92400E",
                text: "#FDE68A",
                mutedText: "#FACC15",
                accent: "#EAB308",
                accentText: "#422006",
                iconBg: "#D97706",
                icon: "#FDE68A",
                highlight: "#713F12",
            },
        },
    },
    {
        name: "crimson-alert",
        title: "Crimson Alert",
        description: "برای هشدارهای بحرانی، اعلان‌های امنیتی و لاگ‌های خطا.",
        usage: ["هشدار امنیتی", "رخداد بحرانی", "وضعیت خطا"],
        colors: {
            light: {
                surface: "#FEF2F2",
                border: "#FECACA",
                text: "#7F1D1D",
                mutedText: "#991B1B",
                accent: "#DC2626",
                accentText: "#FEF2F2",
                iconBg: "#F87171",
                icon: "#7F1D1D",
                highlight: "#FEE2E2",
            },
            dark: {
                surface: "#450A0A",
                border: "#7F1D1D",
                text: "#FECACA",
                mutedText: "#FCA5A5",
                accent: "#DC2626",
                accentText: "#450A0A",
                iconBg: "#B91C1C",
                icon: "#FECACA",
                highlight: "#7F1D1D",
            },
        },
    },
    {
        name: "cyber-lime",
        title: "Cyber Lime",
        description: "برای بخش‌های فناوری، مانیتورینگ ریل‌تایم و وضعیت‌های زنده.",
        usage: ["داشبورد لحظه‌ای", "وضعیت سرورها", "گزارش DevOps"],
        colors: {
            light: {
                surface: "#F7FEE7",
                border: "#D9F99D",
                text: "#3F6212",
                mutedText: "#4D7C0F",
                accent: "#84CC16",
                accentText: "#1A2E05",
                iconBg: "#65A30D",
                icon: "#F7FEE7",
                highlight: "#ECFCCB",
            },
            dark: {
                surface: "#1A2E05",
                border: "#3F6212",
                text: "#D9F99D",
                mutedText: "#BEF264",
                accent: "#84CC16",
                accentText: "#1A2E05",
                iconBg: "#65A30D",
                icon: "#D9F99D",
                highlight: "#365314",
            },
        },
    },
    {
        name: "inkwell",
        title: "Inkwell",
        description: "برای ماژول‌های اسناد، آرشیو گزارش و مدیریت دانش.",
        usage: ["مستندات", "تاریخچه فعالیت", "پیوست‌ها"],
        colors: {
            light: {
                surface: "#F4F4F5",
                border: "#E4E4E7",
                text: "#18181B",
                mutedText: "#3F3F46",
                accent: "#71717A",
                accentText: "#18181B",
                iconBg: "#A1A1AA",
                icon: "#18181B",
                highlight: "#E4E4E7",
            },
            dark: {
                surface: "#18181B",
                border: "#27272A",
                text: "#F4F4F5",
                        mutedText: "#D4D4D8",
                accent: "#71717A",
                accentText: "#F4F4F5",
                iconBg: "#3F3F46",
                icon: "#F9FAFB",
                highlight: "#27272A",
            },
        },
    },
    {
        name: "azure-pulse",
        title: "Azure Pulse",
        description: "برای اپلیکیشن‌های SaaS، آنالیتیکس و نمودارهای لحظه‌ای.",
        usage: ["پالس داده", "اعلان عمومی", "داشبورد SaaS"],
        colors: {
            light: {
                surface: "#F0F9FF",
                border: "#BAE6FD",
                text: "#0C4A6E",
                mutedText: "#0E7490",
                accent: "#38BDF8",
                accentText: "#082F49",
                iconBg: "#0EA5E9",
                icon: "#F0F9FF",
                highlight: "#E0F2FE",
            },
            dark: {
                surface: "#082F49",
                border: "#0C4A6E",
                text: "#E0F2FE",
                mutedText: "#BAE6FD",
                accent: "#38BDF8",
                accentText: "#082F49",
                iconBg: "#0EA5E9",
                icon: "#E0F2FE",
                highlight: "#0C4A6E",
            },
        },
    },
    {
        name: "ember-heat",
        title: "Ember Heat",
        description: "برای پروژه‌های خلاقانه، رویدادها و کمپین‌های تبلیغاتی.",
        usage: ["رویداد ویژه", "کمپین", "پروژه خلاقانه"],
        colors: {
            light: {
                surface: "#FFF4ED",
                border: "#FED7AA",
                text: "#7C2D12",
                mutedText: "#C2410C",
                accent: "#FB5F1B",
                accentText: "#FEF3C7",
                iconBg: "#F97316",
                icon: "#FEF3C7",
                highlight: "#FFE7D5",
            },
            dark: {
                surface: "#2E0F05",
                border: "#7C2D12",
                text: "#FECBA1",
                mutedText: "#FDBA74",
                accent: "#FB5F1B",
                accentText: "#2E0F05",
                iconBg: "#EA580C",
                icon: "#FED7AA",
                highlight: "#7C2D12",
            },
        },
    },
    {
        name: "velvet-noir",
        title: "Velvet Noir",
        description: "برای صفحات پروفایل، بخش‌های لوکس و محتوای پریمیوم.",
        usage: ["پروفایل حرفه‌ای", "پلن پریمیوم", "صفحه درباره ما"],
        colors: {
            light: {
                surface: "#F8F5FF",
                border: "#E9D8FD",
                text: "#3B0764",
                mutedText: "#5B21B6",
                accent: "#A855F7",
                accentText: "#F8F5FF",
                iconBg: "#7C3AED",
                icon: "#F8F5FF",
                highlight: "#EEE8FF",
            },
            dark: {
                surface: "#2B1744",
                border: "#4C1D95",
                text: "#E9D8FD",
                mutedText: "#C4B5FD",
                accent: "#A855F7",
                accentText: "#2B1744",
                iconBg: "#7C3AED",
                icon: "#F8F5FF",
                highlight: "#3B216B",
            },
        },
    },
    {
        name: "glacier-silver",
        title: "Glacier Silver",
        description: "برای ماژول‌های گزارش‌گیری، کارت‌های KPI و تب‌های خلاصه مدیریتی.",
        usage: ["KPI", "خلاصه مدیریتی", "گزارش روزانه"],
        colors: {
            light: {
                surface: "#F5F8FF",
                border: "#E0E7FF",
                text: "#1E293B",
                mutedText: "#475569",
                accent: "#818CF8",
                accentText: "#1E293B",
                iconBg: "#6366F1",
                icon: "#F5F8FF",
                highlight: "#E8EDFF",
            },
            dark: {
                surface: "#1C2240",
                border: "#2E3A6C",
                text: "#E0E7FF",
                mutedText: "#C7D2FE",
                accent: "#818CF8",
                accentText: "#111428",
                iconBg: "#6366F1",
                icon: "#E0E7FF",
                highlight: "#2E3A6C",
            },
        },
    },
    {
        name: "vista-horizon",
        title: "Vista Horizon",
        description: "ترکیب آبی ویستا با زرد درخشان برای استارتاپ‌ها و صفحات آنالیز.",
        usage: ["داشبورد عمومی", "صفحات معرفی محصول", "بنرهای KPI"],
        colors: {
            light: {
                surface: "#F0F9FF",
                border: "#BFDBFE",
                text: "#0F172A",
                mutedText: "#1D4ED8",
                accent: "#2563EB",
                accentText: "#FFFFFF",
                iconBg: "#FACC15",
                icon: "#0F172A",
                highlight: "#FEF3C7",
            },
            dark: {
                surface: "#0B1C33",
                border: "#1E40AF",
                text: "#E0F2FE",
                mutedText: "#BFDBFE",
                accent: "#2563EB",
                accentText: "#0B1C33",
                iconBg: "#FACC15",
                icon: "#0B1C33",
                highlight: "#1F2937",
            },
        },
    },
    {
        name: "lunar-sky",
        title: "Lunar Sky",
        description: "پالت ترکیبی خاکستری قمری و آبی آسمانی برای محیط‌های حرفه‌ای.",
        usage: ["پروفایل سازمانی", "گزارش‌های رسمی", "مدیریت کاربران"],
        colors: {
            light: {
                surface: "#F2F4F8",
                border: "#D0D5DD",
                text: "#1F2933",
                mutedText: "#3E4C59",
                accent: "#3B82F6",
                accentText: "#FFFFFF",
                iconBg: "#E2E8F0",
                icon: "#1F2933",
                highlight: "#EAF1FF",
            },
            dark: {
                surface: "#1A202C",
                border: "#2D3748",
                text: "#E2E8F0",
                mutedText: "#A0AEC0",
                accent: "#60A5FA",
                accentText: "#0F172A",
                iconBg: "#2C5282",
                icon: "#E2E8F0",
                highlight: "#243447",
            },
        },
    },
    {
        name: "neon-orchid",
        title: "Neon Orchid",
        description: "پالت پویا با بنفش نئونی برای بخش‌های خلاقانه و ماژول‌های AI.",
        usage: ["ماژول‌های هوش مصنوعی", "گالری‌ها", "ویدجت‌های خلاق"],
        colors: {
            light: {
                surface: "#F8F5FF",
                border: "#E0C8FF",
                text: "#581C87",
                mutedText: "#6D28D9",
                accent: "#C084FC",
                accentText: "#2E1065",
                iconBg: "#A855F7",
                icon: "#F8F5FF",
                highlight: "#F3E8FF",
            },
            dark: {
                surface: "#2B1744",
                border: "#4C1D95",
                text: "#F3E8FF",
                mutedText: "#D8B4FE",
                accent: "#C084FC",
                accentText: "#2B1744",
                iconBg: "#9333EA",
                icon: "#F3E8FF",
                highlight: "#3D1A5D",
            },
        },
    },
    {
        name: "terra-cotta",
        title: "Terra Cotta",
        description: "رنگ‌های کرمی و خاکی برای صفحات لوکس، مینیمال و برندینگ.",
        usage: ["صفحه درباره ما", "پروفایل‌های مدیریتی", "گزارش‌های سالانه"],
        colors: {
            light: {
                surface: "#FEF9F4",
                border: "#F4E1D2",
                text: "#4B2E2B",
                mutedText: "#7C4A3A",
                accent: "#D97745",
                accentText: "#FEF9F4",
                iconBg: "#E8B286",
                icon: "#4B2E2B",
                highlight: "#FCE3C8",
            },
            dark: {
                surface: "#2D1A17",
                border: "#4B2E2B",
                text: "#FCE3C8",
                mutedText: "#F0B999",
                accent: "#D97745",
                accentText: "#2D1A17",
                iconBg: "#B66132",
                icon: "#FCE3C8",
                highlight: "#3F2622",
            },
        },
    },
    {
        name: "chromatic-flare",
        title: "Chromatic Flare",
        description: "پالت با درخشش نئون برای نمودارهای زنده، مانیتورینگ و DevOps.",
        usage: ["صفحات مانیتورینگ", "وضعیت ریل‌تایم", "نمودارهای عملکرد"],
        colors: {
            light: {
                surface: "#F2FBFF",
                border: "#BAE6FF",
                text: "#012A4A",
                mutedText: "#0369A1",
                accent: "#00E5FF",
                accentText: "#042F49",
                iconBg: "#38BDF8",
                icon: "#012A4A",
                highlight: "#CCFBF1",
            },
            dark: {
                surface: "#062230",
                border: "#0B3B4C",
                text: "#CFFAFE",
                mutedText: "#7DD3FC",
                accent: "#00E5FF",
                accentText: "#062230",
                iconBg: "#0891B2",
                icon: "#CFFAFE",
                highlight: "#0F3F4F",
            },
        },
    },
    {
        name: "aurora-mist",
        title: "Aurora Mist",
        description: "پالت آرام با سبز نعناعی و آبی یخی برای فرم‌ها و صفحات اطلاعاتی.",
        usage: ["فرم‌های تماس", "صفحات پشتیبانی", "تب‌های تنظیمات"],
        colors: {
            light: {
                surface: "#F3FFFB",
                border: "#C9F5E8",
                text: "#0F3D3E",
                mutedText: "#14746F",
                accent: "#2DD4BF",
                accentText: "#043938",
                iconBg: "#5EEAD4",
                icon: "#043938",
                highlight: "#E0FFF8",
            },
            dark: {
                surface: "#063A38",
                border: "#0F4F4B",
                text: "#D1FAF5",
                mutedText: "#99F6E4",
                accent: "#2DD4BF",
                accentText: "#063A38",
                iconBg: "#14B8A6",
                icon: "#D1FAF5",
                highlight: "#0F504D",
            },
        },
    },
];

