# Generated by Django 5.2.8 on 2025-11-21 00:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Is Enabled')),
                ('welcome_message', models.CharField(default='سلام! چطور می\u200cتونم کمکتون کنم؟', max_length=500, verbose_name='Welcome Message')),
                ('default_message', models.CharField(default='متأسفانه متوجه نشدم. لطفاً سوال خود را واضح\u200cتر بپرسید.', max_length=500, verbose_name='Default Message')),
                ('rate_limit_per_minute', models.IntegerField(default=5, verbose_name='Rate Limit Per Minute')),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
                'indexes': [models.Index(fields=['is_enabled'], name='chatbot_settings_enabled_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Keywords')),
                ('patterns', models.TextField(blank=True, verbose_name='Patterns')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='chatbot_faq_active_order_idx'), models.Index(fields=['question'], name='chatbot_faq_question_idx')],
            },
        ),
    ]
