# Generated by Django 6.0 on 2025-12-29 21:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether the chatbot is enabled', verbose_name='Is Enabled')),
                ('welcome_message', models.CharField(default='Hello! How can I help you?', help_text='Message displayed when chatbot starts', max_length=500, verbose_name='Welcome Message')),
                ('default_message', models.CharField(default="Sorry, I didn't understand. Please ask your question more clearly.", help_text="Message displayed when chatbot doesn't understand the query", max_length=500, verbose_name='Default Message')),
                ('rate_limit_per_minute', models.IntegerField(default=5, help_text='Maximum number of requests per minute per user', verbose_name='Rate Limit Per Minute')),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
                'db_table': 'chatbot_settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('question', models.CharField(db_index=True, help_text='Frequently asked question', max_length=500, verbose_name='Question')),
                ('answer', models.TextField(help_text='Answer to the question', verbose_name='Answer')),
                ('keywords', models.CharField(blank=True, help_text='Keywords for matching user queries', max_length=500, verbose_name='Keywords')),
                ('patterns', models.TextField(blank=True, help_text='Patterns for matching user queries', verbose_name='Patterns')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in FAQ list (lower numbers appear first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'chatbot_faqs',
                'ordering': ['order', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='chatbot_faq_is_acti_000e74_idx')],
            },
        ),
    ]
