# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chatbot Settings', 'verbose_name_plural': 'Chatbot Settings'},
        ),
        migrations.RemoveIndex(
            model_name='chatbotsettings',
            name='chatbot_settings_enabled_idx',
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='chatbot_faq_question_idx',
        ),
        migrations.RenameIndex(
            model_name='faq',
            new_name='chatbot_faq_is_acti_000e74_idx',
            old_name='chatbot_faq_active_order_idx',
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='default_message',
            field=models.CharField(default="Sorry, I didn't understand. Please ask your question more clearly.", help_text="Message displayed when chatbot doesn't understand the query", max_length=500, verbose_name='Default Message'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the chatbot is enabled', verbose_name='Is Enabled'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='rate_limit_per_minute',
            field=models.IntegerField(default=5, help_text='Maximum number of requests per minute per user', verbose_name='Rate Limit Per Minute'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='welcome_message',
            field=models.CharField(default='Hello! How can I help you?', help_text='Message displayed when chatbot starts', max_length=500, verbose_name='Welcome Message'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='Answer to the question', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords for matching user queries', max_length=500, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in FAQ list (lower numbers appear first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='patterns',
            field=models.TextField(blank=True, help_text='Patterns for matching user queries', verbose_name='Patterns'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(db_index=True, help_text='Frequently asked question', max_length=500, verbose_name='Question'),
        ),
        migrations.AlterModelTable(
            name='chatbotsettings',
            table='chatbot_settings',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='chatbot_faqs',
        ),
    ]
