# Generated by Django 6.0 on 2025-12-29 21:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='نام کشور (مثلاً: ایران، آلمان)', max_length=100, unique=True, verbose_name='نام کشور')),
                ('code', models.CharField(db_index=True, help_text='کد ISO کشور (مثلاً: IRN، USA)', max_length=3, unique=True, verbose_name='کد کشور')),
                ('phone_code', models.CharField(blank=True, help_text='کد تلفن بین\u200cالمللی (مثلاً: +98)', max_length=5, verbose_name='کد تلفن')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
                'db_table': 'countries',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'name'], name='countries_is_acti_3c018c_idx'), models.Index(fields=['code'], name='countries_code_df63e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Key')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'core_feature_flag',
                'ordering': ['key'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='core_featur_is_acti_31f4f0_idx'), models.Index(fields=['key', 'is_active'], name='core_featur_key_614ae5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='نام استان (مثلاً: تهران، اصفهان)', max_length=50, unique=True, verbose_name='نام استان')),
                ('code', models.CharField(db_index=True, help_text='کد یکتای استان', max_length=3, unique=True, verbose_name='کد استان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='عرض جغرافیایی مرکز استان', max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='طول جغرافیایی مرکز استان', max_digits=11, null=True, verbose_name='طول جغرافیایی')),
                ('country', models.ForeignKey(help_text='کشور مربوط به این استان', on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='core.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'db_table': 'provinces',
                'ordering': ['country__name', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='نام شهر (مثلاً: تهران، شیراز)', max_length=50, verbose_name='نام شهر')),
                ('code', models.CharField(db_index=True, help_text='کد یکتای شهر در استان', max_length=5, verbose_name='کد شهر')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='عرض جغرافیایی مرکز شهر', max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='طول جغرافیایی مرکز شهر', max_digits=11, null=True, verbose_name='طول جغرافیایی')),
                ('province', models.ForeignKey(help_text='استان مربوط به این شهر', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'db_table': 'cities',
                'ordering': ['province__name', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['is_active', 'name'], name='provinces_is_acti_d6b5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'is_active'], name='provinces_country_1e06e1_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['code'], name='provinces_code_f1a622_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'name'], name='cities_provinc_e3ddcb_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active', 'province'], name='cities_is_acti_f2e5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['code'], name='cities_code_a89448_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'code')},
        ),
    ]
