# Generated by Django 6.0 on 2025-12-26 08:24
# Modified to handle existing tables from user app

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # استفاده از SeparateDatabaseAndState برای جداسازی تغییرات دیتابیس از state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # State operations: Django فکر می‌کند مدل‌ها ایجاد شدند
                migrations.CreateModel(
                    name='Country',
                    fields=[
                        ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                        ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                        ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                        ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                        ('name', models.CharField(db_index=True, help_text='نام کشور (مثلاً: ایران، آلمان)', max_length=100, unique=True, verbose_name='نام کشور')),
                        ('code', models.CharField(db_index=True, help_text='کد ISO کشور (مثلاً: IRN، USA)', max_length=3, unique=True, verbose_name='کد کشور')),
                        ('phone_code', models.CharField(blank=True, help_text='کد تلفن بین‌المللی (مثلاً: +98)', max_length=5, verbose_name='کد تلفن')),
                    ],
                    options={
                        'verbose_name': 'کشور',
                        'verbose_name_plural': 'کشورها',
                        'db_table': 'countries',
                        'ordering': ['name'],
                        'abstract': False,
                        'indexes': [models.Index(fields=['is_active', 'name'], name='countries_is_acti_3c018c_idx'), models.Index(fields=['code'], name='countries_code_df63e8_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='Province',
                    fields=[
                        ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                        ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                        ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                        ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                        ('name', models.CharField(db_index=True, help_text='نام استان (مثلاً: تهران، اصفهان)', max_length=50, unique=True, verbose_name='نام استان')),
                        ('code', models.CharField(db_index=True, help_text='کد یکتای استان', max_length=3, unique=True, verbose_name='کد استان')),
                        ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='عرض جغرافیایی مرکز استان', max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                        ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='طول جغرافیایی مرکز استان', max_digits=11, null=True, verbose_name='طول جغرافیایی')),
                        ('country', models.ForeignKey(help_text='کشور مربوط به این استان', on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='core.country', verbose_name='کشور')),
                    ],
                    options={
                        'verbose_name': 'استان',
                        'verbose_name_plural': 'استان‌ها',
                        'db_table': 'provinces',
                        'ordering': ['country__name', 'name'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='City',
                    fields=[
                        ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                        ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                        ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                        ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                        ('name', models.CharField(db_index=True, help_text='نام شهر (مثلاً: تهران، شیراز)', max_length=50, verbose_name='نام شهر')),
                        ('code', models.CharField(db_index=True, help_text='کد یکتای شهر در استان', max_length=5, verbose_name='کد شهر')),
                        ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='عرض جغرافیایی مرکز شهر', max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                        ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='طول جغرافیایی مرکز شهر', max_digits=11, null=True, verbose_name='طول جغرافیایی')),
                        ('province', models.ForeignKey(help_text='استان مربوط به این شهر', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.province', verbose_name='استان')),
                    ],
                    options={
                        'verbose_name': 'شهر',
                        'verbose_name_plural': 'شهرها',
                        'db_table': 'cities',
                        'ordering': ['province__name', 'name'],
                        'abstract': False,
                    },
                ),
                migrations.AddIndex(
                    model_name='province',
                    index=models.Index(fields=['is_active', 'name'], name='provinces_is_acti_d6b5a4_idx'),
                ),
                migrations.AddIndex(
                    model_name='province',
                    index=models.Index(fields=['country', 'is_active'], name='provinces_country_1e06e1_idx'),
                ),
                migrations.AddIndex(
                    model_name='province',
                    index=models.Index(fields=['code'], name='provinces_code_f1a622_idx'),
                ),
                migrations.AddIndex(
                    model_name='city',
                    index=models.Index(fields=['province', 'name'], name='cities_provinc_e3ddcb_idx'),
                ),
                migrations.AddIndex(
                    model_name='city',
                    index=models.Index(fields=['is_active', 'province'], name='cities_is_acti_f2e5d6_idx'),
                ),
                migrations.AddIndex(
                    model_name='city',
                    index=models.Index(fields=['code'], name='cities_code_a89448_idx'),
                ),
                migrations.AlterUniqueTogether(
                    name='city',
                    unique_together={('province', 'code')},
                ),
            ],
            # Database operations: عملیات واقعی دیتابیس (خالی چون جداول قبلاً وجود دارند)
            database_operations=[
                # جداول قبلاً توسط user app ایجاد شده‌اند
                # فقط باید اطمینان حاصل کنیم که country وجود دارد
                migrations.RunSQL(
                    # Create countries table if not exists
                    sql="""
                    CREATE TABLE IF NOT EXISTS countries (
                        id SERIAL PRIMARY KEY,
                        public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        name VARCHAR(100) NOT NULL UNIQUE,
                        code VARCHAR(3) NOT NULL UNIQUE,
                        phone_code VARCHAR(5) NOT NULL DEFAULT ''
                    );
                    
                    CREATE INDEX IF NOT EXISTS countries_is_acti_3c018c_idx ON countries (is_active, name);
                    CREATE INDEX IF NOT EXISTS countries_code_df63e8_idx ON countries (code);
                    CREATE INDEX IF NOT EXISTS countries_public_id_idx ON countries (public_id);
                    CREATE INDEX IF NOT EXISTS countries_is_active_idx ON countries (is_active);
                    CREATE INDEX IF NOT EXISTS countries_created_at_idx ON countries (created_at);
                    
                    -- اضافه کردن ایران اگر وجود نداشته باشد
                    INSERT INTO countries (name, code, phone_code, is_active, created_at, updated_at)
                    VALUES ('ایران', 'IRN', '+98', TRUE, NOW(), NOW())
                    ON CONFLICT (code) DO NOTHING;
                    """,
                    reverse_sql="-- No reverse needed, keep the table"
                ),
                # اضافه کردن ستون country_id به provinces اگر وجود نداشته باشد
                migrations.RunSQL(
                    sql="""
                    -- اضافه کردن ستون country_id اگر وجود نداشته باشد
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name='provinces' AND column_name='country_id'
                        ) THEN
                            ALTER TABLE provinces ADD COLUMN country_id INTEGER;
                            
                            -- تنظیم کشور برای تمام استان‌ها به ایران
                            UPDATE provinces SET country_id = (SELECT id FROM countries WHERE code = 'IRN' LIMIT 1);
                            
                            -- اضافه کردن constraint
                            ALTER TABLE provinces ALTER COLUMN country_id SET NOT NULL;
                            ALTER TABLE provinces ADD CONSTRAINT provinces_country_id_fk 
                                FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT;
                            
                            CREATE INDEX IF NOT EXISTS provinces_country_1e06e1_idx ON provinces (country_id, is_active);
                        END IF;
                    END $$;
                    """,
                    reverse_sql="-- No reverse needed"
                ),
            ],
        ),
    ]
