# Generated by Django 6.0 on 2025-12-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_feature_flag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='core_featur_is_acti_31f4f0_idx',
            old_name='core_featur_is_acti_created_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='core_featur_key_614ae5_idx',
            old_name='core_featur_key_is_a_idx',
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Key'),
        ),
    ]
