# Generated by Django 6.0.2 on 2026-02-20 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_created_by_country_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='اسلاگ انگلیسی/URL-friendly برای استفاده در وب\u200cسایت', max_length=140, verbose_name='اسلاگ شهر'),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='اسلاگ انگلیسی/URL-friendly برای استفاده در وب\u200cسایت', max_length=120, verbose_name='اسلاگ استان'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='cities_slug_905566_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['slug'], name='provinces_slug_1152e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('province', 'slug'), name='uq_city_province_slug_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='uq_province_slug_non_empty'),
        ),
    ]
