
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year for these statistics', verbose_name='Year')),
                ('month', models.IntegerField(db_index=True, help_text='Month for these statistics (1-12)', verbose_name='Month')),
                ('active_agents', models.IntegerField(default=0, help_text='Number of active agents this month', verbose_name='Active Agents')),
                ('properties_listed', models.IntegerField(default=0, help_text='Total properties listed by agency this month', verbose_name='Properties Listed')),
                ('properties_sold', models.IntegerField(default=0, help_text='Total properties sold this month', verbose_name='Properties Sold')),
                ('properties_rented', models.IntegerField(default=0, help_text='Total properties rented this month', verbose_name='Properties Rented')),
                ('total_sales_value', models.BigIntegerField(default=0, help_text='Total value of all sales this month', verbose_name='Total Sales Value')),
                ('total_commissions', models.BigIntegerField(default=0, help_text='Total commissions earned by agency this month', verbose_name='Total Commissions')),
                ('new_clients', models.IntegerField(default=0, help_text='Number of new clients acquired this month', verbose_name='New Clients')),
            ],
            options={
                'verbose_name': 'Agency Statistics',
                'verbose_name_plural': 'Agency Statistics',
                'db_table': 'real_estate_agency_statistics',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AgentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Year for these statistics', verbose_name='Year')),
                ('month', models.IntegerField(db_index=True, help_text='Month for these statistics (1-12)', verbose_name='Month')),
                ('properties_listed', models.IntegerField(default=0, help_text='Number of properties listed this month', verbose_name='Properties Listed')),
                ('properties_sold', models.IntegerField(default=0, help_text='Number of properties sold this month', verbose_name='Properties Sold')),
                ('properties_rented', models.IntegerField(default=0, help_text='Number of properties rented this month', verbose_name='Properties Rented')),
                ('total_sales_value', models.BigIntegerField(default=0, help_text='Total value of sales this month', verbose_name='Total Sales Value')),
                ('total_commissions', models.BigIntegerField(default=0, help_text='Total commissions earned this month', verbose_name='Total Commissions')),
            ],
            options={
                'verbose_name': 'Agent Statistics',
                'verbose_name_plural': 'Agent Statistics',
                'db_table': 'real_estate_agent_statistics',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAudio',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this audio should be displayed', verbose_name='Display Order')),
                ('autoplay', models.BooleanField(default=False, help_text='Whether the audio should autoplay', verbose_name='Autoplay')),
                ('loop', models.BooleanField(default=False, help_text='Whether the audio should loop', verbose_name='Loop')),
            ],
            options={
                'verbose_name': 'Property Audio',
                'verbose_name_plural': 'Property Audios',
                'db_table': 'real_estate_property_audios',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('title', models.CharField(blank=True, help_text='Custom title for this document (optional)', max_length=255, null=True, verbose_name='Title')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this document should be displayed', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'db_table': 'real_estate_property_documents',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('title', models.CharField(db_index=True, help_text='Feature title (e.g., Parking, Elevator)', max_length=100, unique=True, verbose_name='Title')),
                ('category', models.CharField(blank=True, db_index=True, help_text='Feature category (e.g., Interior, Exterior, Amenities)', max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
                'db_table': 'real_estate_property_features',
                'ordering': ['category', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text='Designates whether this is the main image for the property', verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this image should be displayed', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'real_estate_property_images',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('inquiry_type', models.CharField(choices=[('info', 'Request Information'), ('visit', 'Schedule Visit'), ('offer', 'Make Offer'), ('other', 'Other')], default='info', max_length=50, verbose_name='Inquiry Type')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
            ],
            options={
                'verbose_name': 'Property Inquiry',
                'verbose_name_plural': 'Property Inquiries',
                'db_table': 'real_estate_property_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLabel',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('title', models.CharField(db_index=True, help_text='Label title (e.g., Featured, Hot Deal)', max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', help_text='URL-friendly identifier for the property label', max_length=100, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name': 'Property Label',
                'verbose_name_plural': 'Property Labels',
                'db_table': 'real_estate_property_labels',
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyState',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('title', models.CharField(db_index=True, help_text='Property state title (e.g., For Sale, For Rent)', max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the property state', max_length=100, unique=True, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name': 'Property State',
                'verbose_name_plural': 'Property States',
                'db_table': 'real_estate_property_states',
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for these statistics', verbose_name='Date')),
                ('views', models.IntegerField(default=0, help_text='Total views on this date', verbose_name='Views')),
                ('unique_views', models.IntegerField(default=0, help_text='Unique views on this date', verbose_name='Unique Views')),
                ('favorites', models.IntegerField(default=0, help_text='Number of favorites on this date', verbose_name='Favorites')),
                ('inquiries', models.IntegerField(default=0, help_text='Number of inquiries on this date', verbose_name='Inquiries')),
                ('shares', models.IntegerField(default=0, help_text='Number of shares on this date', verbose_name='Shares')),
            ],
            options={
                'verbose_name': 'Property Statistics',
                'verbose_name_plural': 'Property Statistics',
                'db_table': 'real_estate_property_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data')),
                ('hreflang_data', models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data')),
                ('title', models.CharField(db_index=True, help_text='Tag title', max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the tag', max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Tag description', null=True, verbose_name='Description')),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Designates whether this tag is publicly visible', verbose_name='Public')),
            ],
            options={
                'verbose_name': 'Property Tag',
                'verbose_name_plural': 'Property Tags',
                'db_table': 'real_estate_property_tags',
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(db_index=True, help_text='Property type title (e.g., پیش فروش, آپارتمان و سوئیت)', max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the property type', max_length=150, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this property type', verbose_name='Description')),
                ('display_order', models.IntegerField(db_index=True, default=0, help_text='Order for display in lists (within same level)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'db_table': 'real_estate_property_types',
                'ordering': ['path'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this video should be displayed', verbose_name='Display Order')),
                ('autoplay', models.BooleanField(default=False, help_text='Whether the video should autoplay', verbose_name='Autoplay')),
                ('mute', models.BooleanField(default=True, help_text='Whether the video should be muted by default', verbose_name='Mute')),
                ('show_cover', models.BooleanField(default=True, help_text='Whether to show the cover image before playback', verbose_name='Show Cover')),
            ],
            options={
                'verbose_name': 'Property Video',
                'verbose_name_plural': 'Property Videos',
                'db_table': 'real_estate_property_videos',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the viewer', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, help_text='URL of the referrer page', null=True, verbose_name='Referrer')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
            ],
            options={
                'verbose_name': 'Property View Log',
                'verbose_name_plural': 'Property View Logs',
                'db_table': 'real_estate_property_view_logs',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateAgency',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data')),
                ('hreflang_data', models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data')),
                ('name', models.CharField(db_index=True, help_text='Agency name', max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the agency', max_length=200, unique=True, verbose_name='URL Slug')),
                ('license_number', models.CharField(blank=True, db_index=True, help_text='Agent license number', max_length=100, null=True, unique=True, verbose_name='License Number')),
                ('license_expire_date', models.DateField(blank=True, db_index=True, help_text='Date when the license expires', null=True, verbose_name='License Expiry Date')),
                ('phone', models.CharField(db_index=True, help_text='Contact phone number', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Contact email address', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, help_text='Agency website URL', verbose_name='Website')),
                ('address', models.TextField(blank=True, help_text='Full address of the agency', verbose_name='Address')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Designates whether this agency is verified', verbose_name='Verified')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Agency rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews', verbose_name='Total Reviews')),
                ('description', models.TextField(blank=True, help_text='Agency description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Real Estate Agency',
                'verbose_name_plural': 'Real Estate Agencies',
                'db_table': 'real_estate_agencies',
                'ordering': ['-rating', '-is_verified', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealEstateFloorPlan',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('title', models.CharField(db_index=True, help_text="Floor plan title (e.g., 'First Floor - Type A', 'Duplex VIP')", max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A unique URL-friendly identifier for this floor plan', max_length=250, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this floor plan', verbose_name='Description')),
                ('floor_size', models.DecimalField(decimal_places=2, help_text='Total floor area (e.g., 1267 sqft)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Floor Size (sqft/sqm)')),
                ('size_unit', models.CharField(choices=[('sqft', 'Square Feet'), ('sqm', 'Square Meters')], default='sqm', help_text='Unit of measurement for floor size', max_length=10, verbose_name='Size Unit')),
                ('bedrooms', models.SmallIntegerField(blank=True, help_text='Number of bedrooms in this floor plan', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bedrooms')),
                ('bathrooms', models.SmallIntegerField(blank=True, help_text='Number of bathrooms in this floor plan', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bathrooms')),
                ('price', models.BigIntegerField(blank=True, db_index=True, help_text='Price for this floor plan (e.g., $1,650 per month or total price)', null=True, verbose_name='Price')),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, IRR, etc.)', max_length=3, verbose_name='Currency')),
                ('floor_number', models.SmallIntegerField(blank=True, help_text='Which floor this plan is for (optional)', null=True, verbose_name='Floor Number')),
                ('unit_type', models.CharField(blank=True, help_text="Unit type identifier (e.g., 'Type A', 'Type B', 'VIP')", max_length=50, verbose_name='Unit Type')),
                ('display_order', models.IntegerField(db_index=True, default=0, help_text='Order for displaying floor plans', verbose_name='Display Order')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Whether this floor plan is currently available', verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Real Estate Floor Plan',
                'verbose_name_plural': 'Real Estate Floor Plans',
                'db_table': 'real_estate_floor_plans',
                'ordering': ['property_obj', 'display_order', 'floor_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityRegion',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Example: منطقه 1، منطقه 2', max_length=50, verbose_name='Region Name')),
                ('code', models.IntegerField(help_text='Numeric code: 1، 2، 3، ...', verbose_name='Region Code')),
                ('city', models.ForeignKey(help_text='The city this region belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'City Region',
                'verbose_name_plural': 'City Regions',
                'db_table': 'real_estate_city_regions',
                'ordering': ['city', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorPlanImage',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text='Designates whether this is the main image for the floor plan', verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this image should be displayed', verbose_name='Display Order')),
                ('title', models.CharField(blank=True, help_text="Optional title for this image (e.g., '2D Blueprint', '3D Render')", max_length=200, verbose_name='Image Title')),
                ('description', models.TextField(blank=True, help_text='Optional description for this image', verbose_name='Description')),
                ('image', models.ForeignKey(help_text='Image media file (blueprint, 3D render, or photo)', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_links', to='media.imagemedia', verbose_name='Image File')),
            ],
            options={
                'verbose_name': 'Floor Plan Image',
                'verbose_name_plural': 'Floor Plan Images',
                'db_table': 'real_estate_floor_plan_images',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data')),
                ('hreflang_data', models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='URL Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=8, help_text='Geographic latitude for map display', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=8, help_text='Geographic longitude for map display', max_digits=11, null=True, verbose_name='Longitude')),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('sale_price', models.BigIntegerField(blank=True, null=True)),
                ('pre_sale_price', models.BigIntegerField(blank=True, null=True)),
                ('price_per_sqm', models.IntegerField(blank=True, editable=False, null=True)),
                ('monthly_rent', models.BigIntegerField(blank=True, null=True)),
                ('rent_amount', models.BigIntegerField(blank=True, null=True)),
                ('mortgage_amount', models.BigIntegerField(blank=True, null=True)),
                ('security_deposit', models.BigIntegerField(blank=True, null=True)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('built_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.SmallIntegerField(choices=[(0, 'Studio'), (1, '1 Bedroom'), (2, '2 Bedrooms'), (3, '3 Bedrooms'), (4, '4 Bedrooms'), (5, '5 Bedrooms'), (6, '6 Bedrooms'), (7, '7 Bedrooms'), (8, '8 Bedrooms'), (9, '9 Bedrooms'), (10, '10 Bedrooms'), (11, '11 Bedrooms'), (12, '12 Bedrooms'), (13, '13 Bedrooms'), (14, '14 Bedrooms'), (15, '15 Bedrooms'), (16, '16 Bedrooms'), (17, '17 Bedrooms'), (18, '18 Bedrooms'), (19, '19 Bedrooms'), (20, '20+ Bedrooms')], db_index=True, default=1, help_text='Number of bedrooms (0 = Studio)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Bedrooms')),
                ('bathrooms', models.SmallIntegerField(choices=[(0, 'No Bathroom'), (1, '1 Bathroom'), (2, '2 Bathrooms'), (3, '3 Bathrooms'), (4, '4 Bathrooms'), (5, '5 Bathrooms'), (6, '6 Bathrooms'), (7, '7 Bathrooms'), (8, '8 Bathrooms'), (9, '9 Bathrooms'), (10, '10 Bathrooms'), (11, '11 Bathrooms'), (12, '12 Bathrooms'), (13, '13 Bathrooms'), (14, '14 Bathrooms'), (15, '15 Bathrooms'), (16, '16 Bathrooms'), (17, '17 Bathrooms'), (18, '18 Bathrooms'), (19, '19 Bathrooms'), (20, '20+ Bathrooms')], db_index=True, default=1, help_text='Number of bathrooms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Bathrooms')),
                ('capacity', models.SmallIntegerField(blank=True, choices=[(1, '1 Person'), (2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 People'), (6, '6 People'), (7, '7 People'), (8, '8 People'), (9, '9 People'), (10, '10 People'), (12, '12 People'), (15, '15 People'), (20, '20 People'), (25, '25 People'), (30, '30+ People')], help_text='Maximum number of people (mainly for short-term rentals)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Capacity')),
                ('kitchens', models.SmallIntegerField(choices=[(0, 'No Kitchen'), (1, '1 Kitchen'), (2, '2 Kitchens'), (3, '3 Kitchens'), (4, '4 Kitchens'), (5, '5 Kitchens'), (6, '6 Kitchens'), (7, '7 Kitchens'), (8, '8 Kitchens'), (9, '9 Kitchens'), (10, '10 Kitchens')], default=1, help_text='Number of kitchens', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Kitchens')),
                ('living_rooms', models.SmallIntegerField(choices=[(0, 'No Living Room'), (1, '1 Living Room'), (2, '2 Living Rooms'), (3, '3 Living Rooms'), (4, '4 Living Rooms'), (5, '5 Living Rooms'), (6, '6 Living Rooms'), (7, '7 Living Rooms'), (8, '8 Living Rooms'), (9, '9 Living Rooms'), (10, '10 Living Rooms')], default=1, help_text='Number of living rooms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Living Rooms')),
                ('year_built', models.SmallIntegerField(blank=True, db_index=True, help_text='Year the property was built in Solar calendar (e.g., 1402). Updated automatically.', null=True, verbose_name='Year Built (Shamsi)')),
                ('build_years', models.SmallIntegerField(blank=True, help_text='Number of years since the property was built', null=True, verbose_name='Build Years')),
                ('floors_in_building', models.SmallIntegerField(blank=True, help_text='Total floors in the building', null=True, verbose_name='Floors in Building')),
                ('floor_number', models.SmallIntegerField(blank=True, choices=[(-2, '2nd Basement'), (-1, 'Basement'), (0, 'Ground Floor'), (1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor'), (4, '4th Floor'), (5, '5th Floor'), (6, '6th Floor'), (7, '7th Floor'), (8, '8th Floor'), (9, '9th Floor'), (10, '10th Floor'), (11, '11th Floor'), (12, '12th Floor'), (13, '13th Floor'), (14, '14th Floor'), (15, '15th Floor'), (16, '16th Floor'), (17, '17th Floor'), (18, '18th Floor'), (19, '19th Floor'), (20, '20th Floor'), (21, '21st Floor'), (22, '22nd Floor'), (23, '23rd Floor'), (24, '24th Floor'), (25, '25th Floor'), (30, '30th Floor'), (35, '35th Floor'), (40, '40th Floor'), (45, '45th Floor'), (50, '50+ Floor')], help_text='Floor number of the property (-2 to 50, -1=Basement, 0=Ground floor)', null=True, verbose_name='Floor Number')),
                ('parking_spaces', models.SmallIntegerField(choices=[(0, 'No Parking'), (1, '1 Parking'), (2, '2 Parkings'), (3, '3 Parkings'), (4, '4 Parkings'), (5, '5 Parkings'), (6, '6 Parkings'), (7, '7 Parkings'), (8, '8 Parkings'), (9, '9 Parkings'), (10, '10 Parkings'), (11, '11 Parkings'), (12, '12 Parkings'), (13, '13 Parkings'), (14, '14 Parkings'), (15, '15 Parkings'), (16, '16 Parkings'), (17, '17 Parkings'), (18, '18 Parkings'), (19, '19 Parkings'), (20, '20+ Parkings')], db_index=True, default=0, help_text='Number of parking spaces', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Parking Spaces')),
                ('storage_rooms', models.SmallIntegerField(choices=[(0, 'No Storage'), (1, '1 Storage'), (2, '2 Storages'), (3, '3 Storages'), (4, '4 Storages'), (5, '5 Storages'), (6, '6 Storages'), (7, '7 Storages'), (8, '8 Storages'), (9, '9 Storages'), (10, '10+ Storages')], db_index=True, default=0, help_text='Number of storage rooms (0 = No storage)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Storage Rooms')),
                ('document_type', models.CharField(blank=True, db_index=True, help_text='Type of property ownership document (official, contract, cooperative, etc.)', max_length=32, null=True, verbose_name='Document Type')),
                ('has_document', models.BooleanField(default=True, help_text='Whether the property has any ownership document', verbose_name='Has Document')),
                ('is_published', models.BooleanField(default=False, help_text='Whether property is published', verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether property is featured', verbose_name='Featured')),
                ('is_public', models.BooleanField(default=True, help_text='Designates whether this property is publicly visible', verbose_name='Public')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether property is verified', verbose_name='Verified')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when property was published', null=True, verbose_name='Published At')),
                ('views_count', models.IntegerField(db_index=True, default=0, help_text='Total number of views', verbose_name='Views Count')),
                ('favorites_count', models.IntegerField(default=0, help_text='Total number of favorites', verbose_name='Favorites Count')),
                ('inquiries_count', models.IntegerField(default=0, help_text='Total number of inquiries', verbose_name='Inquiries Count')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector (PostgreSQL)', null=True, verbose_name='Search Vector')),
                ('extra_attributes', models.JSONField(blank=True, default=dict, help_text='Flexible attributes for specific property types', verbose_name='Extra Attributes')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_properties', to='core.city')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_properties', to='core.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.cityregion')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'real_estate_properties',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyAgent',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data')),
                ('hreflang_data', models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data')),
                ('license_number', models.CharField(db_index=True, help_text='Agent license number', max_length=100, unique=True, verbose_name='License Number')),
                ('license_expire_date', models.DateField(blank=True, db_index=True, help_text='Date when the license expires', null=True, verbose_name='License Expiry Date')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the agent', max_length=200, unique=True, verbose_name='URL Slug')),
                ('specialization', models.CharField(blank=True, help_text='Specialization (e.g., Residential, Commercial)', max_length=200, verbose_name='Specialization')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Designates whether this agent is verified', verbose_name='Verified')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Agent rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('total_sales', models.IntegerField(default=0, help_text='Total number of sales completed', verbose_name='Total Sales')),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews', verbose_name='Total Reviews')),
                ('bio', models.TextField(blank=True, help_text='Agent biography', verbose_name='Biography')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
                ('profile_picture', models.ForeignKey(blank=True, help_text='Agent profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agent_profiles', to='media.imagemedia', verbose_name='Profile Picture')),
            ],
            options={
                'verbose_name': 'Property Agent',
                'verbose_name_plural': 'Property Agents',
                'db_table': 'real_estate_agents',
                'ordering': ['-rating', '-total_sales', 'user__admin_profile__last_name'],
                'abstract': False,
            },
        ),
    ]
