# Generated by Django 6.0 on 2025-12-25 02:16

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyagent',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(help_text='Agent responsible for this property', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertyagent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='agent',
            field=models.ForeignKey(help_text='Agent these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='real_estate.propertyagent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='propertyaudio',
            name='audio',
            field=models.ForeignKey(help_text='Audio media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.audiomedia', verbose_name='Audio File'),
        ),
        migrations.AddField(
            model_name='propertyaudio',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_property_audio_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='propertyaudio',
            name='property',
            field=models.ForeignKey(help_text='Property this audio belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_property_document_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='document',
            field=models.ForeignKey(help_text='Document media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.documentmedia', verbose_name='Document File'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(help_text='Property this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['is_active', 'category', 'title'], name='real_estate_is_acti_627f23_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Property features (Parking, Elevator, etc.)', related_name='properties', to='real_estate.propertyfeature', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ForeignKey(help_text='Image media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.imagemedia', verbose_name='Image File'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(help_text='Property this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='propertylabel',
            index=models.Index(fields=['is_active', 'title'], name='real_estate_is_acti_4c4b57_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Property labels (Featured, Hot Deal, etc.)', related_name='properties', to='real_estate.propertylabel', verbose_name='Labels'),
        ),
        migrations.AddIndex(
            model_name='propertystate',
            index=models.Index(fields=['is_active', 'title'], name='real_estate_is_acti_2c5781_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(help_text='Property state (For Sale, For Rent, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertystate', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='propertystatistics',
            name='property',
            field=models.ForeignKey(help_text='Property these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertytag',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Flexible tags for the property', related_name='properties', to='real_estate.propertytag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['is_active', 'display_order'], name='real_estate_is_acti_2aed4c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['title'], name='real_estate_title_010c71_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertytype',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='property_type_display_order_non_negative'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(help_text='Type of property (Apartment, Villa, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertytype', verbose_name='Property Type'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_property_video_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(help_text='Property this video belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='video',
            field=models.ForeignKey(help_text='Video media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.videomedia', verbose_name='Video File'),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_views', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(help_text='The country this province belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='real_estate.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(help_text='Province where property is located (denormalized for performance)', on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_properties', to='real_estate.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(help_text='The province this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='real_estate.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='city',
            field=models.ForeignKey(help_text='City where the agency is located', on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='real_estate.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Agency cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agency_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Agency logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agency_logos', to='media.imagemedia', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AddField(
            model_name='propertyagent',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this agent belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='real_estate.realestateagency', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this property belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.realestateagency', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='agencystatistics',
            name='agency',
            field=models.ForeignKey(help_text='Agency these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='real_estate.realestateagency', verbose_name='Agency'),
        ),
        migrations.AddIndex(
            model_name='realestatefloorplan',
            index=models.Index(fields=['title'], name='real_estate_title_c6a77a_idx'),
        ),
        migrations.AddIndex(
            model_name='cityregion',
            index=models.Index(fields=['city', 'code'], name='real_estate_city_id_403448_idx'),
        ),
        migrations.AddIndex(
            model_name='cityregion',
            index=models.Index(fields=['is_active', 'city'], name='real_estate_is_acti_4e414b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cityregion',
            unique_together={('city', 'code')},
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['agent', '-year', '-month'], name='real_estate_agent_i_832436_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['year', 'month'], name='real_estate_year_6498d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentstatistics',
            unique_together={('agent', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='propertyaudio',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_754a6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyaudio',
            constraint=models.UniqueConstraint(fields=('property', 'audio'), name='unique_property_audio'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_4a96b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertydocument',
            constraint=models.UniqueConstraint(fields=('property', 'document'), name='unique_property_document'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_main'], name='real_estate_propert_07c07f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_75569c_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(fields=('property', 'image'), name='unique_property_image'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['property', '-created_at'], name='real_estate_propert_d6ccdd_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['status', '-created_at'], name='real_estate_status_124cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['-created_at'], name='real_estate_created_8e5db9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystatistics',
            index=models.Index(fields=['property', '-date'], name='real_estate_propert_2ea26c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystatistics',
            index=models.Index(fields=['date'], name='real_estate_date_a4f099_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystatistics',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='real_estate_date_c325f4_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='propertystatistics',
            unique_together={('property', 'date')},
        ),
        migrations.AddIndex(
            model_name='propertytag',
            index=models.Index(fields=['is_public', 'is_active', 'title'], name='real_estate_is_publ_e4d3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytag',
            index=models.Index(fields=['slug'], name='real_estate_slug_1526e6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_d70baa_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyvideo',
            constraint=models.UniqueConstraint(fields=('property', 'video'), name='unique_property_video'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=models.Index(fields=['property', '-viewed_at'], name='real_estate_propert_d335ba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=models.Index(fields=['user', '-viewed_at'], name='real_estate_user_id_6862bf_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=models.Index(fields=['-viewed_at'], name='real_estate_viewed__6dddba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['viewed_at'], name='real_estate_viewed__4417f8_brin'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['is_active', 'name'], name='real_estate_is_acti_f842b0_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'is_active'], name='real_estate_country_ff202f_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['code'], name='real_estate_code_87c569_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'name'], name='real_estate_provinc_a7f326_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active', 'province'], name='real_estate_is_acti_fac252_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['code'], name='real_estate_code_6a1708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'code')},
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['is_active', 'is_verified', '-rating'], name='real_estate_is_acti_b92444_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['city', 'is_active'], name='real_estate_city_id_b62393_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['license_number'], name='real_estate_license_0dd782_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['slug'], name='real_estate_slug_7b717e_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['-rating', '-total_reviews'], name='real_estate_rating_c3df1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='realestateagency',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='agency_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='realestateagency',
            constraint=models.CheckConstraint(condition=models.Q(('total_reviews__gte', 0)), name='agency_total_reviews_non_negative'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['is_active', 'is_verified', '-rating'], name='real_estate_is_acti_bed37a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['agency', 'is_active'], name='real_estate_agency__4f42d1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['city', 'is_active'], name='real_estate_city_id_7ed578_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['user', 'is_active'], name='real_estate_user_id_5ba590_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['license_number'], name='real_estate_license_691aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['slug'], name='real_estate_slug_d0bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['last_name', 'first_name'], name='real_estate_last_na_053bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['-rating', '-total_sales'], name='real_estate_rating_79e112_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='agent_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('total_sales__gte', 0)), name='agent_total_sales_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('total_reviews__gte', 0)), name='agent_total_reviews_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('experience_years__gte', 0)), name='agent_experience_years_non_negative'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['province', 'city', 'is_published'], name='real_estate_provinc_40765f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'region', 'is_published'], name='real_estate_city_id_bc9d55_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood'], name='real_estate_city_id_5bd6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type', 'bedrooms'], name='real_estate_city_id_b3e2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'city', 'property_type', '-price'], name='real_estate_is_publ_c702eb_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'state', '-published_at'], name='real_estate_is_publ_2aedd3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'is_featured', '-views_count'], name='real_estate_is_publ_9fc019_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent', 'is_published', 'is_public', '-created_at'], name='real_estate_agent_i_7b1380_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agency', 'is_published', 'is_public', '-created_at'], name='real_estate_agency__c1a724_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'price'], name='real_estate_is_publ_b22926_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'sale_price'], name='real_estate_is_publ_f2d3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'monthly_rent'], name='real_estate_is_publ_01f0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_public', 'rent_amount'], name='real_estate_is_publ_59c40b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['land_area', 'built_area'], name='real_estate_land_ar_3782fa_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='real_estate_latitud_ea2cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='real_estate_search__79cba3_gin'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='real_estate_created_7f9661_brin'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='property_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='property_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('pre_sale_price__isnull', True), ('pre_sale_price__gte', 0), _connector='OR'), name='property_pre_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__isnull', True), ('monthly_rent__gte', 0), _connector='OR'), name='property_monthly_rent_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('rent_amount__isnull', True), ('rent_amount__gte', 0), _connector='OR'), name='property_rent_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('mortgage_amount__isnull', True), ('mortgage_amount__gte', 0), _connector='OR'), name='property_mortgage_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('land_area__gte', 0)), name='property_land_area_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('built_area__gte', 0)), name='property_built_area_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__gte', 0), ('bedrooms__lte', 50)), name='property_bedrooms_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__gte', 0), ('bathrooms__lte', 50)), name='property_bathrooms_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('parking_spaces__gte', 0)), name='property_parking_spaces_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('storage_rooms__gte', 0)), name='property_storage_rooms_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('security_deposit__isnull', True), ('security_deposit__gte', 0), _connector='OR'), name='property_security_deposit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('kitchens__gte', 0)), name='property_kitchens_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('living_rooms__gte', 0)), name='property_living_rooms_non_negative'),
        ),
        migrations.AddIndex(
            model_name='agencystatistics',
            index=models.Index(fields=['agency', '-year', '-month'], name='real_estate_agency__04f14a_idx'),
        ),
        migrations.AddIndex(
            model_name='agencystatistics',
            index=models.Index(fields=['year', 'month'], name='real_estate_year_b14bcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencystatistics',
            unique_together={('agency', 'year', 'month')},
        ),
    ]
