# Generated by Django 6.0 on 2025-12-29 21:56

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('media', '0001_initial'),
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyagent',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertyagent'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='agent',
            field=models.ForeignKey(help_text='Agent these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='real_estate.propertyagent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='propertyaudio',
            name='audio',
            field=models.ForeignKey(help_text='Audio media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.audiomedia', verbose_name='Audio File'),
        ),
        migrations.AddField(
            model_name='propertyaudio',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_property_audio_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='propertyaudio',
            name='property',
            field=models.ForeignKey(help_text='Property this audio belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_property_document_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='document',
            field=models.ForeignKey(help_text='Document media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.documentmedia', verbose_name='Document File'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(help_text='Property this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['is_active', 'category', 'title'], name='real_estate_is_acti_627f23_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='real_estate.propertyfeature'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ForeignKey(help_text='Image media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.imagemedia', verbose_name='Image File'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(help_text='Property this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='propertylabel',
            index=models.Index(fields=['is_active', 'title'], name='real_estate_is_acti_4c4b57_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylabel',
            index=models.Index(fields=['slug'], name='real_estate_slug_c59624_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='properties', to='real_estate.propertylabel'),
        ),
        migrations.AddIndex(
            model_name='propertystate',
            index=models.Index(fields=['is_active', 'title'], name='real_estate_is_acti_2c5781_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystate',
            index=models.Index(fields=['slug'], name='real_estate_slug_c5211a_idx'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertystate'),
        ),
        migrations.AddField(
            model_name='propertystatistics',
            name='property',
            field=models.ForeignKey(help_text='Property these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertytag',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='properties', to='real_estate.propertytag'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['path'], name='real_estate_path_7f38ba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['depth'], name='real_estate_depth_93274b_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['is_active', 'path'], name='real_estate_is_acti_b95580_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['slug'], name='real_estate_slug_e0eb97_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertytype',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='property_type_display_order_non_negative'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertytype'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_property_video_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(help_text='Property this video belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='video',
            field=models.ForeignKey(help_text='Video media file', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_property_links', to='media.videomedia', verbose_name='Video File'),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_views', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City where the agency is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='core.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='profile_picture',
            field=models.ForeignKey(blank=True, help_text='Agency profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agency_profiles', to='media.imagemedia', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Province where the agency is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='core.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='propertyagent',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this agent belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='real_estate.realestateagency', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.realestateagency'),
        ),
        migrations.AddField(
            model_name='agencystatistics',
            name='agency',
            field=models.ForeignKey(help_text='Agency these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='real_estate.realestateagency', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='realestatefloorplan',
            name='property_obj',
            field=models.ForeignKey(help_text='The property this floor plan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='real_estate.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='floorplanimage',
            name='floor_plan',
            field=models.ForeignKey(help_text='Floor plan this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.realestatefloorplan', verbose_name='Floor Plan'),
        ),
        migrations.AddIndex(
            model_name='cityregion',
            index=models.Index(fields=['city', 'code'], name='real_estate_city_id_403448_idx'),
        ),
        migrations.AddIndex(
            model_name='cityregion',
            index=models.Index(fields=['is_active', 'city'], name='real_estate_is_acti_4e414b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cityregion',
            unique_together={('city', 'code')},
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['agent', '-year', '-month'], name='real_estate_agent_i_832436_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['year', 'month'], name='real_estate_year_6498d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentstatistics',
            unique_together={('agent', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='propertyaudio',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_754a6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyaudio',
            constraint=models.UniqueConstraint(fields=('property', 'audio'), name='unique_property_audio'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_4a96b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertydocument',
            constraint=models.UniqueConstraint(fields=('property', 'document'), name='unique_property_document'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_main'], name='real_estate_propert_07c07f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_75569c_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(fields=('property', 'image'), name='unique_property_image'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['property', '-created_at'], name='real_estate_propert_d6ccdd_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['status', '-created_at'], name='real_estate_status_124cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['-created_at'], name='real_estate_created_8e5db9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystatistics',
            index=models.Index(fields=['property', '-date'], name='real_estate_propert_2ea26c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystatistics',
            index=models.Index(fields=['date'], name='real_estate_date_a4f099_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystatistics',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='real_estate_date_c325f4_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='propertystatistics',
            unique_together={('property', 'date')},
        ),
        migrations.AddIndex(
            model_name='propertytag',
            index=models.Index(fields=['is_public', 'is_active', 'title'], name='real_estate_is_publ_e4d3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytag',
            index=models.Index(fields=['slug'], name='real_estate_slug_1526e6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvideo',
            index=models.Index(fields=['property', 'order'], name='real_estate_propert_d70baa_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyvideo',
            constraint=models.UniqueConstraint(fields=('property', 'video'), name='unique_property_video'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=models.Index(fields=['property', '-viewed_at'], name='real_estate_propert_d335ba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=models.Index(fields=['user', '-viewed_at'], name='real_estate_user_id_6862bf_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=models.Index(fields=['-viewed_at'], name='real_estate_viewed__6dddba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewlog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['viewed_at'], name='real_estate_viewed__4417f8_brin'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['is_active', 'is_verified', '-rating'], name='real_estate_is_acti_b92444_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['province', 'is_active'], name='real_estate_provinc_439c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['city', 'is_active'], name='real_estate_city_id_b62393_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['license_number'], name='real_estate_license_0dd782_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['slug'], name='real_estate_slug_7b717e_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['-rating', '-total_reviews'], name='real_estate_rating_c3df1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='realestateagency',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='agency_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='realestateagency',
            constraint=models.CheckConstraint(condition=models.Q(('total_reviews__gte', 0)), name='agency_total_reviews_non_negative'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['is_active', 'is_verified', '-rating'], name='real_estate_is_acti_bed37a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['agency', 'is_active'], name='real_estate_agency__4f42d1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['user', 'is_active'], name='real_estate_user_id_5ba590_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['license_number'], name='real_estate_license_691aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['slug'], name='real_estate_slug_d0bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagent',
            index=models.Index(fields=['-rating', '-total_sales'], name='real_estate_rating_79e112_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='agent_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('total_sales__gte', 0)), name='agent_total_sales_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertyagent',
            constraint=models.CheckConstraint(condition=models.Q(('total_reviews__gte', 0)), name='agent_total_reviews_non_negative'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_active', True), ('is_public', True), ('is_published', True)), fields=['is_published', 'is_public', 'city', 'property_type', 'bedrooms', '-price'], name='idx_main_search'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_public', True), ('is_published', True)), fields=['city', 'region', 'neighborhood', '-created_at'], name='idx_location_search'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_public', True), ('is_published', True)), fields=['is_published', 'is_public', 'price', 'sale_price', 'monthly_rent'], name='idx_price_range'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_published', True), ('year_built__isnull', False)), fields=['city', 'year_built', 'floor_number', 'parking_spaces', 'storage_rooms'], name='idx_property_details'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_public', True), ('is_published', True)), fields=['city', 'document_type', '-price'], name='idx_document_type'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_featured', True), ('is_public', True), ('is_published', True)), fields=['is_featured', '-views_count', '-created_at'], name='idx_featured_props'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent', 'is_published', '-created_at'], name='idx_agent_dashboard'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agency', 'is_published', '-created_at'], name='idx_agency_dashboard'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('latitude__isnull', False), ('longitude__isnull', False)), fields=['latitude', 'longitude', 'city'], name='idx_map_search'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_gin_fulltext'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extra_attributes'], name='idx_gin_json_attrs'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='idx_brin_created', pages_per_range=128),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['published_at'], name='idx_brin_published', pages_per_range=128),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='property_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='property_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('pre_sale_price__isnull', True), ('pre_sale_price__gte', 0), _connector='OR'), name='property_pre_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__isnull', True), ('monthly_rent__gte', 0), _connector='OR'), name='property_monthly_rent_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('rent_amount__isnull', True), ('rent_amount__gte', 0), _connector='OR'), name='property_rent_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('mortgage_amount__isnull', True), ('mortgage_amount__gte', 0), _connector='OR'), name='property_mortgage_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('land_area__gte', 0)), name='property_land_area_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('built_area__gte', 0)), name='property_built_area_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__gte', 0), ('bedrooms__lte', 20)), name='property_bedrooms_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__gte', 0), ('bathrooms__lte', 20)), name='property_bathrooms_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('parking_spaces__gte', 0), ('parking_spaces__lte', 20)), name='property_parking_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('year_built__isnull', True), models.Q(('year_built__gte', 1300), ('year_built__lte', 1500)), _connector='OR'), name='property_year_built_safe_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('storage_rooms__gte', 0)), name='property_storage_rooms_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('security_deposit__isnull', True), ('security_deposit__gte', 0), _connector='OR'), name='property_security_deposit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('kitchens__gte', 0)), name='property_kitchens_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('living_rooms__gte', 0)), name='property_living_rooms_non_negative'),
        ),
        migrations.AddIndex(
            model_name='agencystatistics',
            index=models.Index(fields=['agency', '-year', '-month'], name='real_estate_agency__04f14a_idx'),
        ),
        migrations.AddIndex(
            model_name='agencystatistics',
            index=models.Index(fields=['year', 'month'], name='real_estate_year_b14bcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencystatistics',
            unique_together={('agency', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='realestatefloorplan',
            index=models.Index(fields=['property_obj', 'is_active'], name='real_estate_propert_7abed6_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatefloorplan',
            index=models.Index(fields=['property_obj', 'display_order'], name='real_estate_propert_aa19c6_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatefloorplan',
            index=models.Index(fields=['is_available', 'is_active'], name='real_estate_is_avai_0f0434_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatefloorplan',
            index=models.Index(fields=['slug'], name='real_estate_slug_4fbc76_idx'),
        ),
        migrations.AddConstraint(
            model_name='realestatefloorplan',
            constraint=models.CheckConstraint(condition=models.Q(('floor_size__gte', 0)), name='floor_plan_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='realestatefloorplan',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='floor_plan_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='floorplanimage',
            index=models.Index(fields=['floor_plan', 'is_main'], name='real_estate_floor_p_6fee64_idx'),
        ),
        migrations.AddIndex(
            model_name='floorplanimage',
            index=models.Index(fields=['floor_plan', 'order'], name='real_estate_floor_p_ff51fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorplanimage',
            constraint=models.UniqueConstraint(fields=('floor_plan', 'image'), name='unique_floor_plan_image'),
        ),
    ]
