# Generated by Django 6.0 on 2025-12-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('media', '0001_initial'),
        ('real_estate', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='idx_usage_document',
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_public', True), ('is_published', True)), fields=['city', 'document_type', '-price'], name='idx_document_type'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='usage_type',
        ),
    ]
