# Generated by Django 6.0 on 2025-12-31 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Property agent (auto-assigned if not provided)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='real_estate.propertyagent'),
        ),
    ]
