# Generated by Django 6.0 on 2025-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Center latitude of the city', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Center longitude of the city', max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Center latitude of the province', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Center longitude of the province', max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
