# Generated by Django 6.0 on 2025-12-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('real_estate', '0003_city_latitude_city_longitude_province_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyagent',
            options={'ordering': ['-rating', '-total_sales', 'user__admin_profile__last_name'], 'verbose_name': 'Property Agent', 'verbose_name_plural': 'Property Agents'},
        ),
        migrations.RemoveConstraint(
            model_name='propertyagent',
            name='agent_experience_years_non_negative',
        ),
        migrations.RemoveIndex(
            model_name='propertyagent',
            name='real_estate_city_id_7ed578_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyagent',
            name='real_estate_last_na_053bcc_idx',
        ),
        migrations.RemoveField(
            model_name='realestateagency',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='realestateagency',
            name='longitude',
        ),
        migrations.AddField(
            model_name='propertyagent',
            name='license_expire_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when the license expires', null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='license_expire_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when the license expires', null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Province where the agency is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='real_estate.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='license_number',
            field=models.CharField(db_index=True, help_text='Agent license number', max_length=100, unique=True, verbose_name='License Number'),
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['province', 'is_active'], name='real_estate_provinc_439c4e_idx'),
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='propertyagent',
            name='whatsapp',
        ),
    ]
