# Generated by Django 6.0 on 2025-12-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_province_city_and_more'),
        ('real_estate', '0004_alter_propertyagent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='real_estate_provinc_a7f326_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='real_estate_is_acti_fac252_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='real_estate_code_6a1708_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(help_text='City where property is located (denormalized for performance)', on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_properties', to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='city',
            field=models.ForeignKey(help_text='City where the agency is located', on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='cityregion',
            name='city',
            field=models.ForeignKey(help_text='The city this region belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.city', verbose_name='City'),
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='real_estate_is_acti_0b1af2_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='real_estate_code_bb01ef_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(help_text='Country where property is located (denormalized for performance)', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.country', verbose_name='Country'),
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='real_estate_is_acti_f842b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='real_estate_country_ff202f_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='real_estate_code_87c569_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.ForeignKey(help_text='Province where property is located (denormalized for performance)', on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_properties', to='core.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Province where the agency is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='core.province', verbose_name='Province'),
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
