# Generated by Django 6.0 on 2025-12-31 02:35

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_make_areas_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='Full-text search vector (PostgreSQL)', null=True, verbose_name='Search Vector'),
        ),
    ]
