# Generated by Django 6.0 on 2025-12-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_province_city_and_more'),
        ('real_estate', '0005_alter_city_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateagency',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the agency', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City where the agency is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_agencies', to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Contact email address', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='license_number',
            field=models.CharField(blank=True, db_index=True, help_text='Agent license number', max_length=100, null=True, unique=True, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
    ]
