# Generated by Django 6.0 on 2025-12-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('real_estate', '0006_alter_realestateagency_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateagency',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='realestateagency',
            name='logo',
        ),
        migrations.AddField(
            model_name='propertyagent',
            name='profile_picture',
            field=models.ForeignKey(blank=True, help_text='Agent profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agent_profiles', to='media.imagemedia', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='propertylabel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='URL-friendly identifier for the property label', max_length=100, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='propertystate',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='URL-friendly identifier for the property state', max_length=100, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='URL-friendly identifier for the property type', max_length=100, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='realestateagency',
            name='profile_picture',
            field=models.ForeignKey(blank=True, help_text='Agency profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agency_profiles', to='media.imagemedia', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='propertyagent',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', help_text='URL-friendly identifier for the agent', max_length=200, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the agency', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddIndex(
            model_name='propertylabel',
            index=models.Index(fields=['slug'], name='real_estate_slug_c59624_idx'),
        ),
        migrations.AddIndex(
            model_name='propertystate',
            index=models.Index(fields=['slug'], name='real_estate_slug_c5211a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['slug'], name='real_estate_slug_e0eb97_idx'),
        ),
    ]
