# Generated by Django 6.0 on 2025-12-31 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_update_property_type_with_seo_and_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='storage_rooms',
            field=models.SmallIntegerField(choices=[(0, 'No Storage'), (1, '1 Storage'), (2, '2 Storages'), (3, '3 Storages'), (4, '4 Storages'), (5, '5 Storages'), (6, '6 Storages'), (7, '7 Storages'), (8, '8 Storages'), (9, '9 Storages'), (10, '10+ Storages')], db_index=True, default=0, help_text='Number of storage rooms (0 = No storage)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Storage Rooms'),
        ),
    ]
