# Generated by Django 6.0 on 2025-12-31 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_update_storage_rooms_max_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking_spaces',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No Parking'), (1, '1 Parking'), (2, '2 Parkings'), (3, '3 Parkings'), (4, '4 Parkings'), (5, '5 Parkings'), (6, '6 Parkings'), (7, '7 Parkings'), (8, '8 Parkings'), (9, '9 Parkings'), (10, '10 Parkings'), (11, '11 Parkings'), (12, '12 Parkings'), (13, '13 Parkings'), (14, '14 Parkings'), (15, '15 Parkings'), (16, '16 Parkings'), (17, '17 Parkings'), (18, '18 Parkings'), (19, '19 Parkings'), (20, '20+ Parkings')], db_index=True, default=0, help_text='Number of parking spaces (optional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Parking Spaces'),
        ),
        migrations.AlterField(
            model_name='property',
            name='storage_rooms',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No Storage'), (1, '1 Storage'), (2, '2 Storages'), (3, '3 Storages'), (4, '4 Storages'), (5, '5 Storages'), (6, '6 Storages'), (7, '7 Storages'), (8, '8 Storages'), (9, '9 Storages'), (10, '10+ Storages')], db_index=True, default=0, help_text='Number of storage rooms (optional, 0 = No storage)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Storage Rooms'),
        ),
    ]
