# Generated by Django 6.0 on 2025-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('media', '0001_initial'),
        ('real_estate', '0008_allow_null_parking_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestateagency',
            options={'ordering': ['-rating', 'name'], 'verbose_name': 'Real Estate Agency', 'verbose_name_plural': 'Real Estate Agencies'},
        ),
        migrations.RemoveIndex(
            model_name='realestateagency',
            name='real_estate_is_acti_b92444_idx',
        ),
        migrations.AddIndex(
            model_name='realestateagency',
            index=models.Index(fields=['is_active', '-rating'], name='real_estate_is_acti_ff0dfb_idx'),
        ),
        migrations.RemoveField(
            model_name='realestateagency',
            name='is_verified',
        ),
    ]
