# Generated by Django 6.0 on 2026-01-05 10:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('real_estate', '0010_alter_propertyfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='agencystatistics',
            name='avg_deal_time',
            field=models.IntegerField(default=0, verbose_name='Avg Deal Time (Days)'),
        ),
        migrations.AddField(
            model_name='agencystatistics',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Agency Conversion Rate (%)'),
        ),
        migrations.AddField(
            model_name='agencystatistics',
            name='market_share_growth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Market Share Growth (%)'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='avg_deal_time',
            field=models.IntegerField(default=0, help_text='Average days from listing to closing', verbose_name='Avg Deal Time (Days)'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of inquiries converted to deals', max_digits=5, verbose_name='Conversion Rate (%)'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='failure_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of cancelled/failed deals', max_digits=5, verbose_name='Deal Failure Rate (%)'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='lead_to_contract_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Lead-to-Contract Rate (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='app_views_count',
            field=models.IntegerField(default=0, help_text='Number of views from the application', verbose_name='App Views'),
        ),
        migrations.AddField(
            model_name='property',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when property was sold or rented', null=True, verbose_name='Closed At'),
        ),
        migrations.AddField(
            model_name='property',
            name='web_views_count',
            field=models.IntegerField(default=0, help_text='Number of views from the website', verbose_name='Web Views'),
        ),
        migrations.AddField(
            model_name='propertystatistics',
            name='app_views',
            field=models.IntegerField(default=0, help_text='Views from app on this date', verbose_name='App Views'),
        ),
        migrations.AddField(
            model_name='propertystatistics',
            name='countries',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertystatistics',
            name='platforms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertystatistics',
            name='web_views',
            field=models.IntegerField(default=0, help_text='Views from website on this date', verbose_name='Web Views'),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=5),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='device',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='site_id',
            field=models.CharField(db_index=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='propertyviewlog',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('app', 'Mobile Application'), ('desktop', 'Desktop Software'), ('bot', 'Bot/Scraper'), ('other', 'Other')], db_index=True, default='web', max_length=10, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(db_index=True, default=0, help_text='Total number of views (Web + App)', verbose_name='Total Views'),
        ),
        migrations.AlterField(
            model_name='propertyviewlog',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, help_text='IP address of the viewer', verbose_name='IP Address'),
        ),
        migrations.CreateModel(
            name='PropertyStateStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='real_estate.propertystate')),
            ],
            options={
                'db_table': 'real_estate_property_state_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['state', '-date'], name='real_estate_state_i_19e143_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='real_estate_date_d7547b_brin')],
                'unique_together': {('state', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='real_estate.propertytype')),
            ],
            options={
                'db_table': 'real_estate_property_type_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['property_type', '-date'], name='real_estate_propert_99dc99_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='real_estate_date_a73f6e_brin')],
                'unique_together': {('property_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RegionalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('avg_price_sale', models.BigIntegerField(default=0)),
                ('avg_rent_monthly', models.BigIntegerField(default=0)),
                ('total_active_listings', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.cityregion')),
            ],
            options={
                'db_table': 'real_estate_regional_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['province', 'city', 'region', '-date'], name='real_estate_provinc_345f9b_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='real_estate_date_324168_brin')],
                'unique_together': {('province', 'city', 'region', 'date')},
            },
        ),
    ]
