# Generated by Django 6.0 on 2026-01-26 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_alter_property_description_alter_property_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.SmallIntegerField(choices=[(0, 'No Bathroom'), (1, '1 Bathroom'), (2, '2 Bathroom'), (3, '3 Bathroom'), (4, '4 Bathroom'), (5, '5 Bathroom'), (6, '6 Bathroom'), (7, '7 Bathroom'), (8, '8 Bathroom'), (9, '9 Bathroom'), (10, '10 Bathroom'), (11, '11 Bathroom'), (12, '12 Bathroom'), (13, '13 Bathroom'), (14, '14 Bathroom'), (15, '15 Bathroom'), (16, '16 Bathroom'), (17, '17 Bathroom'), (18, '18 Bathroom'), (19, '19 Bathroom'), (20, '20+ Bathroom')], db_index=True, default=1, help_text='Number of bathrooms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.SmallIntegerField(choices=[(0, 'Studio'), (1, '1 Bedroom'), (2, '2 Bedroom'), (3, '3 Bedroom'), (4, '4 Bedroom'), (5, '5 Bedroom'), (6, '6 Bedroom'), (7, '7 Bedroom'), (8, '8 Bedroom'), (9, '9 Bedroom'), (10, '10 Bedroom'), (11, '11 Bedroom'), (12, '12 Bedroom'), (13, '13 Bedroom'), (14, '14 Bedroom'), (15, '15 Bedroom'), (16, '16 Bedroom'), (17, '17 Bedroom'), (18, '18 Bedroom'), (19, '19 Bedroom'), (20, '20+ Bedroom')], db_index=True, default=1, help_text='Number of bedrooms (0 = Studio)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchens',
            field=models.SmallIntegerField(choices=[(0, 'No Kitchen'), (1, '1 Kitchen'), (2, '2 Kitchen'), (3, '3 Kitchen'), (4, '4 Kitchen'), (5, '5 Kitchen'), (6, '6 Kitchen'), (7, '7 Kitchen'), (8, '8 Kitchen'), (9, '9 Kitchen'), (10, '10 Kitchen')], default=1, help_text='Number of kitchens', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Kitchens'),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_rooms',
            field=models.SmallIntegerField(choices=[(0, 'No Living Room'), (1, '1 Living Room'), (2, '2 Living Room'), (3, '3 Living Room'), (4, '4 Living Room'), (5, '5 Living Room'), (6, '6 Living Room'), (7, '7 Living Room'), (8, '8 Living Room'), (9, '9 Living Room'), (10, '10 Living Room')], default=1, help_text='Number of living rooms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Living Rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_spaces',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No Parking'), (1, '1 Parking'), (2, '2 Parking'), (3, '3 Parking'), (4, '4 Parking'), (5, '5 Parking'), (6, '6 Parking'), (7, '7 Parking'), (8, '8 Parking'), (9, '9 Parking'), (10, '10 Parking'), (11, '11 Parking'), (12, '12 Parking'), (13, '13 Parking'), (14, '14 Parking'), (15, '15 Parking'), (16, '16 Parking'), (17, '17 Parking'), (18, '18 Parking'), (19, '19 Parking'), (20, '20+ Parking')], db_index=True, default=0, help_text='Number of parking spaces (optional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Parking Spaces'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.CharField(db_index=True, help_text='Unique URL slug (supports Persian and English)', max_length=120, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='storage_rooms',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No Storage'), (1, '1 Storage'), (2, '2 Storage'), (3, '3 Storage'), (4, '4 Storage'), (5, '5 Storage'), (6, '6 Storage'), (7, '7 Storage'), (8, '8 Storage'), (9, '9 Storage'), (10, '10+ Storage')], db_index=True, default=0, help_text='Number of storage rooms (optional, 0 = No storage)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Storage Rooms'),
        ),
    ]
