# Generated by Django 6.0 on 2026-02-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_alter_property_options_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.propertystate'),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='usage_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('presale', 'پیش\u200cفروش'), ('exchange', 'معاوضه'), ('mortgage', 'رهن'), ('other', 'سایر')], db_index=True, default='other', help_text='System category for analytics (e.g. Sale vs Rent)', max_length=20, verbose_name='Usage Type'),
        ),
    ]
