# Generated by Django 6.0 on 2026-02-17 02:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_audiomedia_created_by_documentmedia_created_by_and_more'),
        ('real_estate', '0017_propertystate_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyAgentSocialMedia',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Social media name (e.g., Instagram, Telegram, LinkedIn)', max_length=100, verbose_name='Social Media Name')),
                ('url', models.URLField(help_text='Full social media page link', max_length=300, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order')),
                ('agent', models.ForeignKey(help_text='Related property agent', on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='real_estate.propertyagent', verbose_name='Property Agent')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('icon', models.ForeignKey(blank=True, help_text='Social media icon or image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agent_social_media_icons', to='media.imagemedia', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Property Agent Social Media',
                'verbose_name_plural': 'Property Agent Social Media',
                'db_table': 'real_estate_agent_social_media',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['agent', 'is_active', 'order'], name='real_estate_agent_i_0217d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateAgencySocialMedia',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Social media name (e.g., Instagram, Telegram, LinkedIn)', max_length=100, verbose_name='Social Media Name')),
                ('url', models.URLField(help_text='Full social media page link', max_length=300, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order')),
                ('agency', models.ForeignKey(help_text='Related real estate agency', on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='real_estate.realestateagency', verbose_name='Real Estate Agency')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('icon', models.ForeignKey(blank=True, help_text='Social media icon or image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_agency_social_media_icons', to='media.imagemedia', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Real Estate Agency Social Media',
                'verbose_name_plural': 'Real Estate Agency Social Media',
                'db_table': 'real_estate_agency_social_media',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['agency', 'is_active', 'order'], name='real_estate_agency__cdff89_idx')],
            },
        ),
    ]
