# Generated by Django 6.0.2 on 2026-02-20 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_slug_province_slug_city_cities_slug_905566_idx_and_more'),
        ('real_estate', '0018_alter_property_property_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cityregion',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='English URL-friendly slug for website filtering', max_length=160, verbose_name='Region Slug'),
        ),
        migrations.AddIndex(
            model_name='cityregion',
            index=models.Index(fields=['slug'], name='real_estate_slug_d0ac33_idx'),
        ),
        migrations.AddConstraint(
            model_name='cityregion',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('city', 'slug'), name='uq_city_region_city_slug_non_empty'),
        ),
    ]
