# Generated by Django 6.0.2 on 2026-02-22 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_audiomedia_created_by_documentmedia_created_by_and_more'),
        ('real_estate', '0022_propertystate_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertystate',
            name='real_estate_is_acti_2c5781_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertystate',
            name='real_estate_slug_c5211a_idx',
        ),
        migrations.RenameModel(
            old_name='PropertyState',
            new_name='ListingType',
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['slug'], name='real_estate_slug_11f321_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfeature',
            index=models.Index(fields=['parent'], name='real_estate_parent__098582_idx'),
        ),
        migrations.RenameModel(
            old_name='PropertyStateStatistics',
            new_name='ListingTypeStatistics',
        ),
        migrations.AlterField(
            model_name='listingtypestatistics',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='real_estate.listingtype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.listingtype'),
        ),
        migrations.AddIndex(
            model_name='listingtype',
            index=models.Index(fields=['is_active', 'title'], name='real_estate_is_acti_2c5781_idx'),
        ),
        migrations.AddIndex(
            model_name='listingtype',
            index=models.Index(fields=['slug'], name='real_estate_slug_c5211a_idx'),
        ),
    ]
