# Generated by Django 6.0.2 on 2026-02-26 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_slug_province_slug_city_cities_slug_905566_idx_and_more'),
        ('media', '0002_audiomedia_created_by_documentmedia_created_by_and_more'),
        ('real_estate', '0025_propertyagent_team_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingtype',
            options={'ordering': ['title'], 'verbose_name': 'Listing Type', 'verbose_name_plural': 'Listing Types'},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_public_has_parking',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_public_has_storage',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_public_has_elevator',
        ),
        migrations.RenameIndex(
            model_name='propertyagent',
            new_name='real_estate_is_acti_c257aa_idx',
            old_name='real_estate_is_acti_8db51f_idx',
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main image for this listing type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_type_images', to='media.imagemedia', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Short summary text for this listing type', max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the listing type', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='title',
            field=models.CharField(db_index=True, help_text='Listing type title (e.g., For Sale, For Rent)', max_length=50, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='usage_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('rent', 'رهن و اجاره'), ('presale', 'پیش\u200cفروش'), ('exchange', 'معاوضه'), ('mortgage', 'رهن کامل'), ('other', 'سایر')], db_index=True, default='other', help_text='System category for analytics (e.g. Sale vs Rent)', max_length=20, verbose_name='Usage Type'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_public', True), ('is_published', True), ('parking_spaces__gt', 0)), fields=['city', '-created_at'], name='idx_public_has_parking'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('is_public', True), ('is_published', True), ('storage_rooms__gt', 0)), fields=['city', '-created_at'], name='idx_public_has_storage'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(condition=models.Q(('has_elevator', True), ('is_public', True), ('is_published', True)), fields=['city', '-created_at'], name='idx_public_has_elevator'),
        ),
    ]
