PUBLIC_TICKET_LIST_TTL = 30
PUBLIC_TICKET_DETAIL_TTL = 60
PUBLIC_TICKET_MESSAGES_TTL = 30

ADMIN_TICKET_LIST_TTL = 15
ADMIN_TICKET_DETAIL_TTL = 20
ADMIN_TICKET_MESSAGES_TTL = 15
ADMIN_TICKET_STATS_TTL = 10
