# Generated by Django 5.2.7 on 2025-11-07 01:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0009_remove_aiimageprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('email', models.EmailField(help_text='آدرس ایمیل تماس', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('label', models.CharField(blank=True, help_text='برچسب برای ایمیل (مثلاً: پشتیبانی، فروش، اطلاعات)', max_length=100, verbose_name='برچسب')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش در لیست (اعداد کمتر اول نمایش داده می\u200cشوند)', verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ایمیل تماس',
                'verbose_name_plural': 'ایمیل\u200cهای تماس',
                'db_table': 'settings_contact_email',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_co_is_acti_065bc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMobile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('mobile_number', models.CharField(help_text='شماره موبایل - باید با 09 شروع شود (مثال: 09123456789)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 یا +989 شروع شود و 11 رقم باشد', regex='^(09|\\+989)[0-9]{9}$')], verbose_name='شماره موبایل')),
                ('label', models.CharField(blank=True, help_text='برچسب برای شماره موبایل (مثلاً: پشتیبانی، فروش)', max_length=100, verbose_name='برچسب')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش در لیست (اعداد کمتر اول نمایش داده می\u200cشوند)', verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شماره موبایل',
                'verbose_name_plural': 'شماره\u200cهای موبایل',
                'db_table': 'settings_contact_mobile',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_co_is_acti_5a1b91_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('phone_number', models.CharField(help_text='شماره تماس (ثابت) - مثال: 021-12345678', max_length=20, validators=[django.core.validators.RegexValidator(message='شماره تماس باید شامل اعداد، +، -، () و فاصله باشد', regex='^[0-9+\\-\\s()]+$')], verbose_name='شماره تماس')),
                ('label', models.CharField(blank=True, help_text='برچسب برای شماره تماس (مثلاً: دفتر مرکزی، پشتیبانی)', max_length=100, verbose_name='برچسب')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش در لیست (اعداد کمتر اول نمایش داده می\u200cشوند)', verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
                'db_table': 'settings_contact_phone',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_co_is_acti_bd96d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('site_name', models.CharField(help_text='نام سیستم یا برند', max_length=200, verbose_name='نام سیستم')),
                ('copyright_text', models.CharField(blank=True, help_text='متن کپی رایت (مثلاً: تمام حقوق محفوظ است © ۱۴۰۴)', max_length=500, verbose_name='متن کپی رایت')),
                ('copyright_link', models.URLField(blank=True, help_text='لینک مربوط به کپی رایت (اختیاری)', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='لینک کپی رایت')),
                ('enamad_image', models.ForeignKey(blank=True, help_text='تصویر نماد اعتماد الکترونیک', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enamad_settings', to='media.imagemedia', verbose_name='تصویر اینماد')),
                ('favicon_image', models.ForeignKey(blank=True, help_text='آیکون نمایش داده شده در تب مرورگر', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon_settings', to='media.imagemedia', verbose_name='تصویر Favicon')),
                ('logo_image', models.ForeignKey(blank=True, help_text='لوگوی اصلی سیستم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_settings', to='media.imagemedia', verbose_name='تصویر لوگو')),
            ],
            options={
                'verbose_name': 'تنظیمات عمومی',
                'verbose_name_plural': 'تنظیمات عمومی',
                'db_table': 'settings_general',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['public_id'], name='settings_ge_public__13e0c8_idx'), models.Index(fields=['is_active', 'created_at'], name='settings_ge_is_acti_9e4ba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='نام شبکه اجتماعی (مثلاً: اینستاگرام، تلگرام، لینکدین)', max_length=100, verbose_name='نام شبکه اجتماعی')),
                ('url', models.URLField(help_text='لینک کامل صفحه شبکه اجتماعی', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='لینک')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش در لیست (اعداد کمتر اول نمایش داده می\u200cشوند)', verbose_name='ترتیب نمایش')),
                ('icon', models.ForeignKey(blank=True, help_text='آیکون یا تصویر شبکه اجتماعی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_icons', to='media.imagemedia', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'db_table': 'settings_social_media',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_so_is_acti_a2e081_idx')],
            },
        ),
    ]
