# Generated by Django 6.0 on 2025-12-24 01:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('email', models.EmailField(db_index=True, help_text='Contact email address', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('label', models.CharField(blank=True, help_text='Label for email (e.g., Support, Sales, Info)', max_length=100, verbose_name='Label')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Contact Email',
                'verbose_name_plural': 'Contact Emails',
                'db_table': 'settings_contact_email',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_co_is_acti_065bc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMobile',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('mobile_number', models.CharField(db_index=True, help_text='Mobile number - must start with 09 (example: 09123456789)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must start with 09 or +989 and be 11 digits.', regex='^(09|\\+989)[0-9]{9}$')], verbose_name='Mobile Number')),
                ('label', models.CharField(blank=True, help_text='Label for mobile number (e.g., Support, Sales)', max_length=100, verbose_name='Label')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Contact Mobile',
                'verbose_name_plural': 'Contact Mobiles',
                'db_table': 'settings_contact_mobile',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_co_is_acti_5a1b91_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number (landline) - example: 021-12345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, +, -, (), and spaces.', regex='^[0-9+\\-\\s()]+$')], verbose_name='Phone Number')),
                ('label', models.CharField(blank=True, help_text='Label for phone number (e.g., Main Office, Support)', max_length=100, verbose_name='Label')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Contact Phone',
                'verbose_name_plural': 'Contact Phones',
                'db_table': 'settings_contact_phone',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_co_is_acti_bd96d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('site_name', models.CharField(db_index=True, help_text='System or brand name', max_length=200, verbose_name='Site Name')),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text (e.g., All rights reserved © 2024)', max_length=500, verbose_name='Copyright Text')),
                ('copyright_link', models.URLField(blank=True, help_text='Copyright related link (optional)', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Copyright Link')),
                ('enamad_image', models.ForeignKey(blank=True, help_text='Electronic trust symbol image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enamad_settings', to='media.imagemedia', verbose_name='Enamad Image')),
                ('favicon_image', models.ForeignKey(blank=True, help_text='Icon displayed in browser tab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon_settings', to='media.imagemedia', verbose_name='Favicon Image')),
                ('logo_image', models.ForeignKey(blank=True, help_text='Main system logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_settings', to='media.imagemedia', verbose_name='Logo Image')),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
                'db_table': 'settings_general',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Social media name (e.g., Instagram, Telegram, LinkedIn)', max_length=100, verbose_name='Social Media Name')),
                ('url', models.URLField(help_text='Full social media page link', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order')),
                ('icon', models.ForeignKey(blank=True, help_text='Social media icon or image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_icons', to='media.imagemedia', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'db_table': 'settings_social_media',
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='settings_so_is_acti_a2e081_idx')],
            },
        ),
    ]
