# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactemail',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Contact Email', 'verbose_name_plural': 'Contact Emails'},
        ),
        migrations.AlterModelOptions(
            name='contactmobile',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Contact Mobile', 'verbose_name_plural': 'Contact Mobiles'},
        ),
        migrations.AlterModelOptions(
            name='contactphone',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Contact Phone', 'verbose_name_plural': 'Contact Phones'},
        ),
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.RemoveIndex(
            model_name='generalsettings',
            name='settings_ge_public__13e0c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='generalsettings',
            name='settings_ge_is_acti_9e4ba8_idx',
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='email',
            field=models.EmailField(db_index=True, help_text='Contact email address', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='label',
            field=models.CharField(blank=True, help_text='Label for email (e.g., Support, Sales, Info)', max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='contactmobile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactmobile',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmobile',
            name='label',
            field=models.CharField(blank=True, help_text='Label for mobile number (e.g., Support, Sales)', max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='contactmobile',
            name='mobile_number',
            field=models.CharField(db_index=True, help_text='Mobile number - must start with 09 (example: 09123456789)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must start with 09 or +989 and be 11 digits.', regex='^(09|\\+989)[0-9]{9}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='contactmobile',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='label',
            field=models.CharField(blank=True, help_text='Label for phone number (e.g., Main Office, Support)', max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Phone number (landline) - example: 021-12345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits, +, -, (), and spaces.', regex='^[0-9+\\-\\s()]+$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='copyright_link',
            field=models.URLField(blank=True, help_text='Copyright related link (optional)', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Copyright Link'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='copyright_text',
            field=models.CharField(blank=True, help_text='Copyright text (e.g., All rights reserved © 2024)', max_length=500, verbose_name='Copyright Text'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='enamad_image',
            field=models.ForeignKey(blank=True, help_text='Electronic trust symbol image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enamad_settings', to='media.imagemedia', verbose_name='Enamad Image'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='favicon_image',
            field=models.ForeignKey(blank=True, help_text='Icon displayed in browser tab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon_settings', to='media.imagemedia', verbose_name='Favicon Image'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='logo_image',
            field=models.ForeignKey(blank=True, help_text='Main system logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_settings', to='media.imagemedia', verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(db_index=True, help_text='System or brand name', max_length=200, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Social media icon or image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_icons', to='media.imagemedia', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(db_index=True, help_text='Social media name (e.g., Instagram, Telegram, LinkedIn)', max_length=100, verbose_name='Social Media Name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order in list (lower numbers appear first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(help_text='Full social media page link', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
    ]
