# Generated by Django 6.0 on 2026-01-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_audiomedia_created_by_documentmedia_created_by_and_more'),
        ('settings', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_image', to='media.imagemedia', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_video', to='media.videomedia', verbose_name='video'),
        ),
    ]
