# Generated by Django 6.0 on 2026-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_mapsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsettings',
            name='cedarmaps_api_key',
        ),
        migrations.RemoveField(
            model_name='mapsettings',
            name='google_maps_api_key',
        ),
        migrations.RemoveField(
            model_name='mapsettings',
            name='neshan_api_key',
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='configs',
            field=models.JSONField(blank=True, default=dict, help_text='Stores API keys and optional settings like Map ID in JSON format.', verbose_name='Provider Configurations'),
        ),
    ]
