# Generated by GitHub Copilot on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_mapsettings_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='footer_about',
            field=models.TextField(blank=True, help_text='Short text shown in website footer', verbose_name='Footer About'),
        ),
    ]
