# Generated by Django 5.2.8 on 2025-11-14 17:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0010_alter_audiomedia_options_alter_documentmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(blank=True, default='index,follow', max_length=50, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict, null=True)),
                ('hreflang_data', models.JSONField(blank=True, default=dict, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.imagemedia', verbose_name='Main Image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'blog_categories',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(blank=True, default='index,follow', max_length=50, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict, null=True)),
                ('hreflang_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(db_index=True, max_length=60)),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
                ('categories', models.ManyToManyField(blank=True, related_name='blog_categories', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'blog_listings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogDocument',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.blog')),
                ('cover_image', models.ForeignKey(blank=True, help_text='کاور خاص برای این سند در این نمونه\u200cکار. اگر تنظیم نشود، از کاور سند استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_document_covers', to='media.imagemedia', verbose_name='Cover Image')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.documentmedia')),
            ],
            options={
                'verbose_name': 'Blog Document',
                'verbose_name_plural': 'Blog Documents',
                'db_table': 'blog_documents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text='فقط یک تصویر می\u200cتواند تصویر اصلی نمونه\u200cکار باشد.', verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('blog', models.ForeignKey(help_text='نمونه\u200cکاری که این تصویر به آن تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog', verbose_name='Blog')),
                ('image', models.ForeignKey(help_text='فایل تصویر مربوط به نمونه\u200cکار.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.imagemedia', verbose_name='Image File')),
            ],
            options={
                'verbose_name': 'Blog Image',
                'verbose_name_plural': 'Blog Images',
                'db_table': 'blog_images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('meta_title', models.CharField(blank=True, db_index=True, help_text='SEO title for search engines (max 70 characters)', max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines (max 300 characters)', max_length=300, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=70, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=300, null=True, verbose_name='Open Graph Description')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(blank=True, default='index,follow', max_length=50, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict, null=True)),
                ('hreflang_data', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image')),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'db_table': 'blog_tags',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_tags', to='blog.blogtag'),
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('autoplay', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=True)),
                ('show_cover', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.blog')),
                ('cover_image', models.ForeignKey(blank=True, help_text='کاور خاص برای این ویدیو در این نمونه\u200cکار. اگر تنظیم نشود، از کاور ویدیو استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_video_covers', to='media.imagemedia', verbose_name='Cover Image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.videomedia')),
            ],
            options={
                'verbose_name': 'Blog Video',
                'verbose_name_plural': 'Blog Videos',
                'db_table': 'blog_videos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogAudio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for public-facing operations', unique=True, verbose_name='Public ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record should be treated as active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('autoplay', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.audiomedia')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='blog.blog')),
                ('cover_image', models.ForeignKey(blank=True, help_text='کاور خاص برای این فایل صوتی در این نمونه\u200cکار. اگر تنظیم نشود، از کاور فایل صوتی استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_audio_covers', to='media.imagemedia', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Blog Audio',
                'verbose_name_plural': 'Blog Audios',
                'db_table': 'blog_audios',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['blog', 'order'], name='blog_audios_blog_id_c59ea9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['path'], name='blog_catego_path_efdbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['depth'], name='blog_catego_depth_bc0c59_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['name'], name='blog_catego_name_ff4202_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='blog_catego_slug_ca79bd_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['public_id'], name='blog_catego_public__56b10e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['is_public'], name='blog_catego_is_publ_a52d69_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['meta_title'], name='blog_catego_meta_ti_b11398_idx'),
        ),
        migrations.AddIndex(
            model_name='blogdocument',
            index=models.Index(fields=['blog', 'order'], name='blog_docume_blog_id_292bab_idx'),
        ),
        migrations.AddIndex(
            model_name='blogimage',
            index=models.Index(fields=['blog', 'is_main'], name='blog_images_blog_id_63307e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogimage',
            index=models.Index(fields=['blog', 'order'], name='blog_images_blog_id_6a2f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['name'], name='blog_tags_name_1a032c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['slug'], name='blog_tags_slug_720acc_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['public_id'], name='blog_tags_public__06630a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['is_public'], name='blog_tags_is_publ_583610_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['meta_title'], name='blog_tags_meta_ti_d627f7_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'is_public'], name='blog_listin_status_1d336b_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='blog_listin_title_400638_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_listin_slug_59a3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['public_id'], name='blog_listin_public__409a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_featured', 'status'], name='blog_listin_is_feat_1ca972_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='blog_listin_created_5f5563_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['meta_title'], name='blog_listin_meta_ti_e05eee_idx'),
        ),
        migrations.AddIndex(
            model_name='blogvideo',
            index=models.Index(fields=['blog', 'order'], name='blog_videos_blog_id_032d20_idx'),
        ),
    ]
