# Generated by Django 6.0 on 2026-01-05 10:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='app_views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views from the application', verbose_name='App Views'),
        ),
        migrations.AddField(
            model_name='blog',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of favorites', verbose_name='Favorites Count'),
        ),
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total number of views (Web + App)', verbose_name='Total Views'),
        ),
        migrations.AddField(
            model_name='blog',
            name='web_views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of views from the website', verbose_name='Web Views'),
        ),
        migrations.CreateModel(
            name='BlogStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for these statistics', verbose_name='Date')),
                ('views', models.IntegerField(default=0, help_text='Total views on this date', verbose_name='Views')),
                ('unique_views', models.IntegerField(default=0, help_text='Unique views on this date', verbose_name='Unique Views')),
                ('favorites', models.IntegerField(default=0, help_text='Number of favorites on this date', verbose_name='Favorites')),
                ('shares', models.IntegerField(default=0, help_text='Number of shares on this date', verbose_name='Shares')),
                ('web_views', models.IntegerField(default=0, help_text='Views from website on this date', verbose_name='Web Views')),
                ('app_views', models.IntegerField(default=0, help_text='Views from app on this date', verbose_name='App Views')),
                ('countries', models.JSONField(blank=True, default=dict)),
                ('platforms', models.JSONField(blank=True, default=dict)),
                ('blog', models.ForeignKey(help_text='Blog post these statistics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Statistics',
                'verbose_name_plural': 'Blog Statistics',
                'db_table': 'blog_statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['blog', '-date'], name='blog_statis_blog_id_6bf199_idx'), models.Index(fields=['date'], name='blog_statis_date_f9ed42_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='blog_statis_date_d537fe_brin')],
                'unique_together': {('blog', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BlogViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'Website'), ('app', 'Mobile Application'), ('desktop', 'Desktop Software'), ('bot', 'Bot/Scraper'), ('other', 'Other')], db_index=True, default='web', max_length=10, verbose_name='Source')),
                ('site_id', models.CharField(db_index=True, default='default', max_length=50)),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('country', models.CharField(blank=True, db_index=True, max_length=5)),
                ('device', models.CharField(blank=True, db_index=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, help_text='URL of the referrer page', null=True, verbose_name='Referrer')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='blog.blog', verbose_name='Blog')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blog View Log',
                'verbose_name_plural': 'Blog View Logs',
                'db_table': 'blog_view_logs',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['blog', '-viewed_at'], name='blog_view_l_blog_id_c38fe6_idx'), models.Index(fields=['user', '-viewed_at'], name='blog_view_l_user_id_ba4a19_idx'), models.Index(fields=['-viewed_at'], name='blog_view_l_viewed__b0a8c9_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['viewed_at'], name='blog_view_l_viewed__92936a_brin')],
            },
        ),
    ]
