# Generated by Django 5.2.8 on 2025-12-04 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('media', '0011_remove_audiomedia_media_audio_is_acti_a95424_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blogaudio',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Blog Audio', 'verbose_name_plural': 'Blog Audios'},
        ),
        migrations.AlterModelOptions(
            name='blogdocument',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Blog Document', 'verbose_name_plural': 'Blog Documents'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ['name'], 'verbose_name': 'Blog Tag', 'verbose_name_plural': 'Blog Tags'},
        ),
        migrations.AlterModelOptions(
            name='blogvideo',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Blog Video', 'verbose_name_plural': 'Blog Videos'},
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_status_1d336b_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_title_400638_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_slug_59a3f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_public__409a8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_is_feat_1ca972_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_created_5f5563_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_listin_meta_ti_e05eee_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='blog_catego_name_ff4202_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='blog_catego_slug_ca79bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='blog_catego_public__56b10e_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='blog_catego_is_publ_a52d69_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='blog_catego_meta_ti_b11398_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogtag',
            name='blog_tags_name_1a032c_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogtag',
            name='blog_tags_slug_720acc_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogtag',
            name='blog_tags_public__06630a_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogtag',
            name='blog_tags_is_publ_583610_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogtag',
            name='blog_tags_meta_ti_d627f7_idx',
        ),
        migrations.AlterField(
            model_name='blog',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories associated with this blog post', related_name='blog_categories', to='blog.blogcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, help_text='Full content of the blog post', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this blog post is featured', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this blog post is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief summary of the blog post', max_length=300, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the blog post', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Publication status of the blog post', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this blog post', related_name='blog_tags', to='blog.blogtag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, help_text='Blog post title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='audio',
            field=models.ForeignKey(help_text='Audio media file', on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.audiomedia', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Whether the audio should autoplay', verbose_name='Autoplay'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='blog',
            field=models.ForeignKey(help_text='Blog post this audio belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_audio_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='loop',
            field=models.BooleanField(default=False, help_text='Whether the audio should loop', verbose_name='Loop'),
        ),
        migrations.AlterField(
            model_name='blogaudio',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this audio should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main image for this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_category_images', to='media.imagemedia', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this category is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(db_index=True, help_text='Category name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the category', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='blog',
            field=models.ForeignKey(help_text='Blog post this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_document_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='document',
            field=models.ForeignKey(help_text='Document media file', on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.documentmedia', verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this document should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='blogdocument',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title for this document (optional)', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(help_text='Blog post this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ForeignKey(help_text='Image media file', on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.imagemedia', verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this is the main image for the blog post', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this image should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='description',
            field=models.TextField(blank=True, help_text='Tag description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=dict, help_text='Hreflang data for multilingual SEO', null=True, verbose_name='Hreflang Data'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this tag is publicly visible', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(db_index=True, help_text='Tag name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='media.imagemedia', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='robots_meta',
            field=models.CharField(blank=True, default='index,follow', help_text='Robots meta tag content', max_length=50, null=True, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL-friendly identifier for the tag', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data', null=True, verbose_name='Structured Data'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Whether the video should autoplay', verbose_name='Autoplay'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='blog',
            field=models.ForeignKey(help_text='Blog post this video belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_video_covers', to='media.imagemedia', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='id',
            field=models.AutoField(editable=False, help_text='Primary key identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='mute',
            field=models.BooleanField(default=True, help_text='Whether the video should be muted by default', verbose_name='Mute'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this video should be displayed', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='show_cover',
            field=models.BooleanField(default=True, help_text='Whether to show the cover image before playback', verbose_name='Show Cover'),
        ),
        migrations.AlterField(
            model_name='blogvideo',
            name='video',
            field=models.ForeignKey(help_text='Video media file', on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='media.videomedia', verbose_name='Video File'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'is_public', '-created_at'], name='blog_listin_status_60f6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_featured', 'status', '-created_at'], name='blog_listin_is_feat_ecb30c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['is_public', 'path'], name='blog_catego_is_publ_0aaefc_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtag',
            index=models.Index(fields=['is_public', 'name'], name='blog_tags_is_publ_29d019_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogaudio',
            constraint=models.UniqueConstraint(fields=('blog', 'audio'), name='unique_blog_audio'),
        ),
        migrations.AddConstraint(
            model_name='blogdocument',
            constraint=models.UniqueConstraint(fields=('blog', 'document'), name='unique_blog_document'),
        ),
        migrations.AddConstraint(
            model_name='blogimage',
            constraint=models.UniqueConstraint(fields=('blog', 'image'), name='unique_blog_image'),
        ),
        migrations.AddConstraint(
            model_name='blogvideo',
            constraint=models.UniqueConstraint(fields=('blog', 'video'), name='unique_blog_video'),
        ),
    ]
