from .classes import (
    AdminRolePermission,
    RequireModuleAccess,
    RequireAdminRole,
    UserManagementPermission,
    SimpleAdminPermission,
    SuperAdminOnly,
    RequirePermission,
    AdminPermissionCache,
    IsAdminUser,  # ✅ اضافه شد
    IsSuperAdmin,  # ✅ اضافه شد
    # Decorators
    require_admin_roles,
    require_module_access,
    # Views
    AdminRoleView,
    AdminPermissionView,
    # Utilities
    create_default_admin_roles,
    ensure_admin_roles_exist,
    get_role_summary,
    blog_permission,
    portfolio_permission,
    analytics_permission,
    analytics_any_permission,
    media_permission,
    user_permission,
    admin_permission,
    ai_permission,
    ai_any_permission,
    panel_permission,
    email_permission,
    ticket_permission,
    chatbot_permission,
    form_permission,
    page_permission,
    real_estate_permission,
    settings_permission,  # Added
    super_admin_permission,
)

from .mixins import PermissionRequiredMixin, RealEstatePermissionMixin

from .definitions import (
    Permission,
    PermissionRegistry,
    PermissionValidator,
    PermissionHelper,
    PERMISSIONS,
    SYSTEM_ROLES,
    AVAILABLE_MODULES,
    AVAILABLE_ACTIONS,
    BASE_ADMIN_PERMISSIONS,
    RoleConfig,
    get_all_permissions,
    get_permission,
    get_permissions_by_module,
    get_permissions_by_action,
    get_role_config,
    get_role_display_name,
    get_default_permissions,
    is_super_admin_role,
    get_system_roles,
    get_available_roles,
    get_user_role_display_text,
    get_module_display_name,
    get_action_display_name,
    validate_role_permissions,
    get_role_permissions_for_creation,
    get_all_role_configs,
    CONSULTANT_RESTRICTIONS,
    is_role_forbidden_for_consultant,
)

__all__ = [
    "AdminRolePermission",
    "RequireModuleAccess",
    "RequireAdminRole",
    "UserManagementPermission",
    "SimpleAdminPermission",
    "SuperAdminOnly",
    "RequirePermission",
    "AdminPermissionCache",
    "IsAdminUser",  # ✅ اضافه شد
    "IsSuperAdmin",  # ✅ اضافه شد
    "require_admin_roles",
    "require_module_access",
    "AdminRoleView",
    "AdminPermissionView",
    "create_default_admin_roles",
    "ensure_admin_roles_exist",
    "get_role_summary",
    "blog_permission",
    "portfolio_permission",
    "analytics_permission",
    "analytics_any_permission",
    "media_permission",
    "user_permission",
    "admin_permission",
    "ai_permission",
    "ai_any_permission",
    "panel_permission",
    "email_permission",
    "ticket_permission",
    "chatbot_permission",
    "form_permission",
    "page_permission",
    "real_estate_permission",
    "settings_permission",  # Added
    "super_admin_permission",
    
    # ==================== Permission Definitions ====================
    "Permission",
    "PermissionRegistry",
    "PermissionValidator",
    "PermissionHelper",
    "PERMISSIONS",
    "SYSTEM_ROLES",
    "AVAILABLE_MODULES",
    "AVAILABLE_ACTIONS",
    "BASE_ADMIN_PERMISSIONS",
    "ADMIN_ROLE_PERMISSIONS",
    "RoleConfig",
    "get_all_permissions",
    "get_permission",
    "get_permissions_by_module",
    "get_permissions_by_action",
    "get_role_config",
    "get_role_display_name",
    "get_default_permissions",
    "is_super_admin_role",
    "get_system_roles",
    "get_available_roles",
    "get_user_role_display_text",
    "get_module_display_name",
    "get_action_display_name",
    "validate_role_permissions",
    "get_role_permissions_for_creation",
    "get_all_role_configs",
    "CONSULTANT_RESTRICTIONS",
    "is_role_forbidden_for_consultant",
]
